HΦ: CalcSpectrumByFullDiag.c File Reference
CalcSpectrumByFullDiag.c File Reference
Functions to perform spectrum calculations with the full-diagonalization method.
#include <complex.h>
#include "global.h"
#include <time.h>
#include "struct.h"
#include "lapack_diag.h"
#include "makeHam.h"
#include "CalcTime.h"
Functions
void zcopy_ (int *n, double complex *x, int *incx, double complex *y, int *incy)
void zdotc_ (double complex *xy, int *n, double complex *x, int *incx, double complex *y, int *incy)
int CalcSpectrumByFullDiag (struct EDMainCalStruct *X, int Nomega, double complex *dcSpectrum, double complex *dcomega)
Compute the Green function with the Lehmann representation and FD
\[ G(z) = \sum_n \frac{|\langle n|c|0\rangle|^2}{z - E_n} \]
.
Detailed Description
Functions to perform spectrum calculations with the full-diagonalization method.
Definition in file CalcSpectrumByFullDiag.c.
Function Documentation
CalcSpectrumByFullDiag()
int CalcSpectrumByFullDiag (struct EDMainCalStruct * X, int Nomega, double complex * dcSpectrum, double complex * dcomega)
Compute the Green function with the Lehmann representation and FD
\[ G(z) = \sum_n \frac{|\langle n|c|0\rangle|^2}{z - E_n} \]
.
Author
Mitsuaki Kawamura (The University of Tokyo)
Generate fully stored Hamiltonian. Because v0 & v1 are overwritten, copy v0 into vg.
v0 becomes eigenvalues in lapack_diag(), and L_vec becomes eigenvectors
Compute \(|\langle n|c|0\rangle|^2\) for all \(n\) and store them into v1, where \(c|0\rangle\) is vg.
Compute spectrum
\[ \sum_n \frac{|\langle n|c|0\rangle|^2}{z - E_n} \]
Parameters
[in,out] X
[in] Nomega Number of frequencies
[out] dcSpectrum [Nomega] Spectrum
[in] dcomega [Nomega] Frequency
Definition at line 37 of file CalcSpectrumByFullDiag.c.
References EDMainCalStruct::Bind, BindStruct::Check, CheckList::idim_max, L_vec, lapack_diag(), makeHam(), StartTimer(), StopTimer(), TRUE, v0, v1, vg, X, and zcopy_().
Referenced by CalcSpectrum().
 {
   int idim, jdim, iomega;
   int idim_max_int;
   int incr=1;
   idim_max_int = (int)X->Bind.Check.idim_max;
   zcopy_(&idim_max_int, &v0[1], &incr, &vg[0], &incr);
   StartTimer(6301);
   makeHam(&(X->Bind));
   StopTimer(6301);
   StartTimer(6302);
   lapack_diag(&(X->Bind));
   StopTimer(6302);
   StartTimer(6303);
   for (idim = 0; idim < idim_max_int; idim++) {
     v1[idim] = 0.0;
     for (jdim = 0; jdim < idim_max_int; jdim++) v1[idim] += conj(vg[jdim]) * L_vec[idim][jdim];
     //zdotc_(&v1[idim], &idim_max_int, &vg[0], &incr, &L_vec[idim][0], &incr);
     v1[idim] = conj(v1[idim]) * v1[idim];
   }/*for (idim = 0; idim < idim_max_int; idim++)*/
   StopTimer(6303);
   StartTimer(6304);
   for (iomega = 0; iomega < Nomega; iomega++) {
     dcSpectrum[iomega] = 0.0;
     for (idim = 0; idim < idim_max_int; idim++) {
       dcSpectrum[iomega] += v1[idim] / (dcomega[iomega] - v0[idim]);
     }/*for (idim = 0; idim < idim_max_int; idim++)*/
   }/*for (iomega = 0; iomega < Nomega; iomega++)*/
   StopTimer(6304);
   return TRUE;
 }/*CalcSpectrumByFullDiag*/
zcopy_()
void zcopy_ (int * n, double complex * x, int * incx, double complex * y, int * incy)
Referenced by CalcSpectrumByFullDiag().
zdotc_()
void zdotc_ (double complex * xy, int * n, double complex * x, int * incx, double complex * y, int * incy)