HΦ: CalcByFullDiag.c File Reference
CalcByFullDiag.c File Reference
#include "CalcByFullDiag.h"
#include "input.h"
#include "wrapperMPI.h"
#include "CalcTime.h"
Functions
int CalcByFullDiag (struct EDMainCalStruct *X)
Parent function for FullDiag mode.
Function Documentation
int CalcByFullDiag (struct EDMainCalStruct * X)
Parent function for FullDiag mode.
Parameters
X [in,out] Struct to get information about file header names, dimension of hirbert space, calc type, physical quantities.
Return values
TRUE(=1) normally finished.
FALSE(=0) abnormally finished.
Definition at line 26 of file CalcByFullDiag.c.
References EDMainCalStruct::Bind, BindStruct::Check, cLogFinish, cLogFullDiag_End, cLogFullDiag_ExpecValue_End, cLogFullDiag_ExpecValue_Start, cLogFullDiag_InputHam_End, cLogFullDiag_InputHam_Start, cLogFullDiag_OutputHam_End, cLogFullDiag_OutputHam_Start, cLogFullDiag_SetHam_End, cLogFullDiag_SetHam_Start, cLogFullDiag_Start, BindStruct::Def, FALSE, CheckList::idim_max, DefineList::iInputHam, inputHam(), DefineList::iOutputHam, lapack_diag(), makeHam(), output(), outputHam(), phys(), DefineList::St, StartTimer(), stdoutMPI, StopTimer(), and TRUE.
Referenced by main().
 {
   int iret=0;
   fprintf(stdoutMPI, "%s", cLogFullDiag_SetHam_Start);
   StartTimer(5100);
   if(X->Bind.Def.iInputHam==FALSE){
     makeHam(&(X->Bind));
   }
   else if(X->Bind.Def.iInputHam==TRUE){
     fprintf(stdoutMPI, "%s", cLogFullDiag_InputHam_Start);
     inputHam(&(X->Bind));
     fprintf(stdoutMPI, "%s", cLogFullDiag_InputHam_End);
   }
   StopTimer(5100);
   fprintf(stdoutMPI, "%s", cLogFullDiag_SetHam_End);
   if(iret != 0) return FALSE;
   if(X->Bind.Def.iOutputHam == TRUE){
     fprintf(stdoutMPI, "%s", cLogFullDiag_OutputHam_Start);
     StartTimer(5500);
     iret=outputHam(&(X->Bind));
     StopTimer(5500);
     fprintf(stdoutMPI, "%s", cLogFullDiag_OutputHam_End);
     if(iret != 0) return FALSE;
     return TRUE;
   }
   fprintf(stdoutMPI, "%s", cLogFullDiag_Start);
   StartTimer(5200);
   iret=lapack_diag(&(X->Bind));
   StopTimer(5200);
   fprintf(stdoutMPI, "%s", cLogFullDiag_End);
   if(iret != 0) return FALSE;
   X->Bind.Def.St=0;
   fprintf(stdoutMPI, "%s", cLogFullDiag_ExpecValue_Start);
   StartTimer(5300);
   phys(&(X->Bind), X->Bind.Check.idim_max);
   StopTimer(5300);
   fprintf(stdoutMPI, "%s", cLogFullDiag_ExpecValue_End);
   StartTimer(5400);
   iret=output(&(X->Bind));
   StopTimer(5400);
   fprintf(stdoutMPI, "%s", cLogFinish);
   if(iret != 0) return FALSE;
   return TRUE;
 }