HΦ: FileIO.c File Reference
FileIO.c File Reference
Functions to open file(s) in output/ directory.
#include "FileIO.h"
#include "wrapperMPI.h"
Functions
int childfopenMPI (const char *_cPathChild, const char *_cmode, FILE **_fp)
Only the root process open file in output/ directory.
int childfopenALL (const char *_cPathChild, const char *_cmode, FILE **_fp)
All processes open file in output/ directory.
Detailed Description
Functions to open file(s) in output/ directory.
Definition in file FileIO.c.
Function Documentation
childfopenALL()
int childfopenALL (const char * _cPathChild, const char * _cmode, FILE ** _fp)
All processes open file in output/ directory.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Returns
-1 if file cannot be opened, 0 if not.
Parameters
[in] _cPathChild File name
[in] _cmode "w", "r", etc.
[in,out] _fp File pointr
Definition at line 50 of file FileIO.c.
References cErrFIOpen, cParentOutputFolder, and D_FileNameMax.
Referenced by CalcByLanczos(), CalcByLOBPCG(), CalcByTEM(), CalcByTPQ(), CalcSpectrum(), CalcSpectrumByBiCG(), CalcSpectrumByTPQ(), Initialize_wave(), Output_restart(), OutputLanczosVector(), ReadInitialVector(), and ReadTMComponents_BiCG().
   {
   char ctmpPath[D_FileNameMax]="";
   strcat(ctmpPath, cParentOutputFolder);
   strcat(ctmpPath, _cPathChild);
   *_fp = fopen(ctmpPath, _cmode);
   if(*_fp == NULL){
     fprintf(stdout, cErrFIOpen, ctmpPath);
     return -1;
   }
   return 0;
 }/*int childfopenALL*/
childfopenMPI()
int childfopenMPI (const char * _cPathChild, const char * _cmode, FILE ** _fp)
Only the root process open file in output/ directory.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Returns
-1 if file cannot be opened, 0 if not.
Parameters
[in] _cPathChild File name
[in] _cmode "w", "r", etc.
[in,out] _fp File pointer
Definition at line 27 of file FileIO.c.
References cErrFIOpen, cParentOutputFolder, D_FileNameMax, fopenMPI(), and stdoutMPI.
Referenced by CalcByLanczos(), CalcByLOBPCG(), CalcByTEM(), CalcByTPQ(), CalcSpectrumByBiCG(), CG_EigenVector(), check(), diagonalcalc(), expec_cisajs(), expec_cisajscktaltdc(), HPhiTrans(), inputHam(), Lanczos_EigenValue(), lapack_diag(), LOBPCG_Main(), output(), output_list(), outputHam(), OutputTimer(), OutputTMComponents(), OutputTMComponents_BiCG(), Read_sz(), ReadTMComponents(), SetOmega(), sz(), TimeKeeper(), TimeKeeperWithRandAndStep(), and TimeKeeperWithStep().
  {
   char ctmpPath[D_FileNameMax]="";
   strcat(ctmpPath, cParentOutputFolder);
   strcat(ctmpPath, _cPathChild);
   *_fp = fopenMPI(ctmpPath, _cmode);
   if(*_fp == NULL){
     fprintf(stdoutMPI, cErrFIOpen, ctmpPath);
     return -1;
   }
   return 0;
 }/*int childfopenMPI*/