HΦ: Multiply.c File Reference
Multiply.c File Reference
File for giving multiplying functions to the wave vectors for TPQ and TE method.
#include "Common.h"
#include "diagonalcalc.h"
#include "Multiply.h"
#include "wrapperMPI.h"
#include "mltply.h"
Functions
int Multiply (struct BindStruct *X)
Function of calculating the i-th step norm as
\[ N^{(i)} = |L v_1^{(i)}-v_0^{(i)}/N_s | \]
and update the i+1-th wave vector as
\[ v_0^{(i+1)} = \frac{L v_1^{(i)}-v_0^{(i)}/N_s}{N^{(i)}} \]
for TPQ calculation.
int MultiplyForTEM (struct BindStruct *X)
Function of multiplying Hamiltonian for Time Evolution.
Detailed Description
File for giving multiplying functions to the wave vectors for TPQ and TE method.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Kota Ido (The University of Tokyo)
Definition in file Multiply.c.
Function Documentation
int Multiply (struct BindStruct * X)
Function of calculating the i-th step norm as
\[ N^{(i)} = |L v_1^{(i)}-v_0^{(i)}/N_s | \]
and update the i+1-th wave vector as
\[ v_0^{(i+1)} = \frac{L v_1^{(i)}-v_0^{(i)}/N_s}{N^{(i)}} \]
for TPQ calculation.
Parameters
X [in] data list for calculation (idim_max and NsiteMPI)
Return values
0 normally finished
-1 unnormally finished
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Definition at line 43 of file Multiply.c.
References BindStruct::Check, BindStruct::Def, global_norm, CheckList::idim_max, LargeValue, MultiplyForTEM(), DefineList::NsiteMPI, SumMPI_dc(), v0, and v1.
Referenced by CalcByTPQ().
 {
   long int i,i_max;
   double complex dnorm;
   double Ns;
   i_max=X->Check.idim_max;
   Ns = 1.0*X->Def.NsiteMPI;
  // mltply is in expec_energy.c v0=H*v1
   dnorm=0.0;
 #pragma omp parallel for default(none) reduction(+: dnorm) private(i) shared(v0, v1) firstprivate(i_max, Ns, LargeValue)
   for(i = 1; i <= i_max; i++){
     v0[i]=LargeValue*v1[i]-v0[i]/Ns;  //v0=(l-H/Ns)*v1
     dnorm += conj(v0[i])*v0[i];
   }
   dnorm=SumMPI_dc(dnorm);
   dnorm=sqrt(dnorm);
   global_norm = dnorm;
 #pragma omp parallel for default(none) private(i) shared(v0) firstprivate(i_max, dnorm)
   for(i=1;i<=i_max;i++){
     v0[i] = v0[i]/dnorm;
   }
   return 0;
 }
int MultiplyForTEM (struct BindStruct * X)
Function of multiplying Hamiltonian for Time Evolution.
Make \(|v_0 \rangle = |\psi(t+dt) \rangle \) from \(|v_1 \rangle = | \psi(t) \rangle \) and \(|v_0 \rangle = H |\psi(t) \rangle \).
Parameters
X [in] data list for calculation (idim_max and TimeSlice)
Return values
0 normally finished
-1 unnormally finished
Definition at line 80 of file Multiply.c.
References BindStruct::Check, BindStruct::Def, ParamList::ExpandCoef, global_norm, CheckList::idim_max, mltply(), DefineList::Param, SumMPI_dc(), ParamList::TimeSlice, v0, v1, and v2.
Referenced by CalcByTEM(), and Multiply().
 {
   long int i,i_max;
   int coef;
   double complex dnorm=0.0;
   double complex tmp1 = 1.0;
   double complex tmp2=0.0;
   double dt=X->Def.Param.TimeSlice;
   //Make |v0> = |psi(t+dt)> from |v1> = |psi(t)> and |v0> = H |psi(t)>
   i_max=X->Check.idim_max;
   // mltply is in expec_energy.c v0=H*v1
   if(dt <pow(10.0, -14)){
 #pragma omp parallel for default(none) reduction(+: dnorm) private(i) shared(v0, v1, v2) firstprivate(i_max, dt, tmp2)
     for(i = 1; i <= i_max; i++){
       tmp2 = v0[i];
       v0[i]=v1[i];  //v0=(1-i*dt*H)*v1
       v1[i]=tmp2;
       v2[i]= 0.0 + I*0.0;
     }
     mltply(X, v2, v1);
   }
   else {
     tmp1 *= -I * dt;
 #pragma omp parallel for default(none) reduction(+: dnorm) private(i) shared(v0, v1, v2) firstprivate(i_max, dt, tmp1, tmp2)
     for (i = 1; i <= i_max; i++) {
       tmp2 = v0[i];
       v0[i] = v1[i] + tmp1 * tmp2;  //v0=(1-i*dt*H)*v1
       v1[i] = tmp2;
       v2[i] = 0.0 + I * 0.0;
     }
     for (coef = 2; coef <= X->Def.Param.ExpandCoef; coef++) {
       tmp1 *= -I * dt / (double complex) coef;
       //v2 = H*v1 = H^coef |psi(t)>
       mltply(X, v2, v1);
 #pragma omp parallel for default(none) private(i) shared(v0, v1, v2) firstprivate(i_max, tmp1, myrank)
       for (i = 1; i <= i_max; i++) {
         v0[i] += tmp1 * v2[i];
         v1[i] = v2[i];
         v2[i] = 0.0 + I * 0.0;
       }
     }
   }
   dnorm=0.0;
 #pragma omp parallel for default(none) reduction(+: dnorm) private(i) shared(v0) firstprivate(i_max, dt)
   for(i = 1; i <= i_max; i++){
     dnorm += conj(v0[i])*v0[i];
   }
   dnorm=SumMPI_dc(dnorm);
   dnorm=sqrt(dnorm);
   global_norm = dnorm;
 #pragma omp parallel for default(none) private(i) shared(v0) firstprivate(i_max, dnorm)
   for(i=1;i<=i_max;i++){
     v0[i] = v0[i]/dnorm;
   }
   return 0;
 }