HΦ: SingleEx.c File Reference
SingleEx.c File Reference
Functions to compute singly excited state.
#include "bitcalc.h"
#include "SingleEx.h"
#include "SingleExHubbard.h"
Functions
int GetSingleExcitedState (struct BindStruct *X, double complex *tmp_v0, double complex *tmp_v1)
Calculation of single excited state Target System: Hubbard, Kondo.
Detailed Description
Functions to compute singly excited state.
Definition in file SingleEx.c.
Function Documentation
int GetSingleExcitedState (struct BindStruct * X, double complex * tmp_v0, double complex * tmp_v1)
Calculation of single excited state Target System: Hubbard, Kondo.
Returns
TRUE: Normally finished
FALSE: Abnormally finished
Author
Kazuyoshi Yoshimi
Version
1.2
Parameters
X define list to get and put information of calcuation
[out] tmp_v0 Result v0 = H v1
[in] tmp_v1 v0 = H v1
Definition at line 30 of file SingleEx.c.
References BindStruct::Def, FALSE, GetSingleExcitedStateHubbard(), GetSingleExcitedStateHubbardGC(), DefineList::iCalcModel, DefineList::NSingleExcitationOperator, and TRUE.
Referenced by GetExcitedState().
   {
   int iret = 0;
   //tmp_v0
   if (X->Def.NSingleExcitationOperator == 0) return TRUE;
   switch (X->Def.iCalcModel) {
   case HubbardGC:
     iret = GetSingleExcitedStateHubbardGC(X, tmp_v0, tmp_v1);
     break;
   case KondoGC:
   case Hubbard:
   case Kondo:
     iret = GetSingleExcitedStateHubbard(X, tmp_v0, tmp_v1);
     break;
   case Spin:
   case SpinGC:
     iret = FALSE;
     break;
   default:
     iret = FALSE;
     break;
   }/*switch (X->Def.iCalcModel)*/
   return iret;
 }/*int GetSingleExcitedState*/