HΦ: StdFace/StdFace_ModelUtil.c File Reference
StdFace_ModelUtil.c File Reference
Various utility for constructing models.
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include "StdFace_vals.h"
#include <string.h>
#include <mpi.h>
Functions
void StdFace_exit (int errorcode)
MPI Abortation wrapper.
void StdFace_trans (struct StdIntList *StdI, double complex trans0, int isite, int ispin, int jsite, int jspin)
Add transfer to the list set StdIntList::trans and StdIntList::transindx and increment StdIntList::ntrans.
void StdFace_Hopping (struct StdIntList *StdI, double complex trans0, int isite, int jsite, double *dR)
Add Hopping for the both spin.
void StdFace_HubbardLocal (struct StdIntList *StdI, double mu0, double h0, double Gamma0, double U0, int isite)
Add intra-Coulomb, magnetic field, chemical potential for the itenerant electron.
void StdFace_MagField (struct StdIntList *StdI, int S2, double h, double Gamma, int isite)
Add longitudinal and transvars magnetic field to the list.
void StdFace_intr (struct StdIntList *StdI, double complex intr0, int site1, int spin1, int site2, int spin2, int site3, int spin3, int site4, int spin4)
Add interaction (InterAll) to the list Set StdIntList::intr and StdIntList::intrindx and increase the number of that (StdIntList::nintr).
void StdFace_GeneralJ (struct StdIntList *StdI, double J[3][3], int Si2, int Sj2, int isite, int jsite)
Treat J as a 3*3 matrix [(6S + 1)*(6S' + 1) interactions].
void StdFace_Coulomb (struct StdIntList *StdI, double V, int isite, int jsite)
Add onsite/offsite Coulomb term to the list StdIntList::Cinter and StdIntList::CinterIndx, and increase the number of them (StdIntList::NCinter).
void StdFace_PrintVal_d (char *valname, double *val, double val0)
Print a valiable (real) read from the input file if it is not specified in the input file (=NaN), set the default value.
void StdFace_PrintVal_dd (char *valname, double *val, double val0, double val1)
Print a valiable (real) read from the input file if it is not specified in the input file (=NaN), set the default value.
void StdFace_PrintVal_c (char *valname, double complex *val, double complex val0)
Print a valiable (complex) read from the input file if it is not specified in the input file (=NaN), set the default value.
void StdFace_PrintVal_i (char *valname, int *val, int val0)
Print a valiable (integer) read from the input file if it is not specified in the input file (=2147483647, the upper limt of Int) set the default value.
void StdFace_NotUsed_d (char *valname, double val)
Stop HPhi if a variable (real) not used is specified in the input file (!=NaN).
void StdFace_NotUsed_c (char *valname, double complex val)
Stop HPhi if a variable (complex) not used is specified in the input file (!=NaN).
void StdFace_NotUsed_J (char *valname, double JAll, double J[3][3])
Stop HPhi if variables (real) not used is specified in the input file (!=NaN).
void StdFace_NotUsed_i (char *valname, int val)
Stop HPhi if a variable (integer) not used is specified in the input file (!=2147483647, the upper limt of Int).
void StdFace_RequiredVal_i (char *valname, int val)
Stop HPhi if a variable (integer) which must be specified is absent in the input file (=2147483647, the upper limt of Int).
static void StdFace_FoldSite (struct StdIntList *StdI, int iCellV[3], int nBox[3], int iCellV_fold[3])
Move a site into the original supercell if it is outside the original supercell.
void StdFace_InitSite (struct StdIntList *StdI, FILE *fp, int dim)
Initialize the super-cell where simulation is performed.
void StdFace_FindSite (struct StdIntList *StdI, int iW, int iL, int iH, int diW, int diL, int diH, int isiteUC, int jsiteUC, int *isite, int *jsite, double complex *Cphase, double *dR)
Find the index of transfer and interaction.
void StdFace_SetLabel (struct StdIntList *StdI, FILE *fp, int iW, int iL, int diW, int diL, int isiteUC, int jsiteUC, int *isite, int *jsite, int connect, double complex *Cphase, double *dR)
Set Label in the gnuplot display (Only used in 2D system)
void StdFace_PrintXSF (struct StdIntList *StdI)
Print lattice.xsf (XCrysDen format)
void StdFace_InputSpinNN (struct StdIntList *StdI, double J0[3][3], double J0All, char *J0name)
Input nearest-neighbor spin-spin interaction.
void StdFace_InputSpin (struct StdIntList *StdI, double Jp[3][3], double JpAll, char *Jpname)
Input spin-spin interaction other than nearest-neighbor.
void StdFace_InputCoulombV (struct StdIntList *StdI, double *V0, char *V0name)
Input off-site Coulomb interaction from the input file, if it is not specified, use the default value (0 or the isotropic Coulomb interaction StdIntList::V).
void StdFace_InputHopp (struct StdIntList *StdI, double complex *t0, char *t0name)
Input hopping integral from the input file, if it is not specified, use the default value(0 or the isotropic hopping StdIntList::V).
void StdFace_PrintGeometry (struct StdIntList *StdI)
Print geometry of sites for the pos-process of correlation function.
void StdFace_MallocInteractions (struct StdIntList *StdI, int ntransMax, int nintrMax)
Malloc Arrays for interactions.
Detailed Description
Various utility for constructing models.
Definition in file StdFace_ModelUtil.c.
Function Documentation
StdFace_Coulomb()
void StdFace_Coulomb (struct StdIntList * StdI, double V, int isite, int jsite)
Add onsite/offsite Coulomb term to the list StdIntList::Cinter and StdIntList::CinterIndx, and increase the number of them (StdIntList::NCinter).
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in,out] StdI
[in] V Coulomb integral U, V, etc.
[in] isite i of n_i
[in] jsite j of n_j
Definition at line 396 of file StdFace_ModelUtil.c.
References StdIntList::Cinter, StdIntList::CinterIndx, StdIntList::NCinter, and StdIntList::V.
Referenced by StdFace_Chain(), StdFace_FCOrtho(), StdFace_Honeycomb(), StdFace_Kagome(), StdFace_Ladder(), StdFace_Orthorhombic(), StdFace_Pyrochlore(), StdFace_Tetragonal(), StdFace_Triangular(), and StdFace_Wannier90().
 {
   StdI->Cinter[StdI->NCinter] = V;
   StdI->CinterIndx[StdI->NCinter][0] = isite;
   StdI->CinterIndx[StdI->NCinter][1] = jsite;
   StdI->NCinter += 1;
 }/*void StdFace_Coulomb*/
StdFace_exit()
void StdFace_exit (int errorcode)
MPI Abortation wrapper.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] errorcode
Definition at line 35 of file StdFace_ModelUtil.c.
Referenced by CheckOutputMode(), PrintCalcMod(), PrintExcitation(), StdFace_Chain_Boost(), StdFace_Honeycomb_Boost(), StdFace_InitSite(), StdFace_InputCoulombV(), StdFace_InputHopp(), StdFace_InputSpin(), StdFace_InputSpinNN(), StdFace_Kagome_Boost(), StdFace_Ladder_Boost(), StdFace_main(), StdFace_NotUsed_c(), StdFace_NotUsed_d(), StdFace_NotUsed_i(), StdFace_RequiredVal_i(), StdFace_Wannier90(), StoreWithCheckDup_c(), StoreWithCheckDup_d(), StoreWithCheckDup_i(), StoreWithCheckDup_s(), StoreWithCheckDup_sl(), UnsupportedSystem(), and VectorPotential().
 {
   int ierr = 0;
   fflush(stdout);
   fflush(stderr);
 #ifdef MPI
   fprintf(stdout, "\n\n #######  You DO NOT have to WORRY about the following MPI-ERROR MESSAGE.  #######\n\n");
   ierr = MPI_Abort(MPI_COMM_WORLD, errorcode);
   ierr = MPI_Finalize();
 #endif
   if (ierr != 0) fprintf(stderr, "\n  MPI_Finalize() = %d\n\n", ierr);
   exit(errorcode);
 }
StdFace_FindSite()
void StdFace_FindSite (struct StdIntList * StdI, int iW, int iL, int iH, int diW, int diL, int diH, int isiteUC, int jsiteUC, int * isite, int * jsite, double complex * Cphase, double * dR)
Find the index of transfer and interaction.
Parameters
[in,out] StdI
[in] iW position of initial site
[in] iL position of initial site
[in] iH position of initial site
[in] diW Translation from the initial site
[in] diL Translation from the initial site
[in] diH Translation from the initial site
[in] isiteUC Intrinsic site index of initial site
[in] jsiteUC Intrinsic site index of final site
[out] isite initial site
[out] jsite final site
[out] Cphase Boundary phase, if it across boundary
[out] dR R_i - R_j in the fractional coordinate
Definition at line 823 of file StdFace_ModelUtil.c.
References StdIntList::Cell, StdIntList::ExpPhase, StdIntList::model, StdIntList::NCell, StdIntList::NsiteUC, StdFace_FoldSite(), and StdIntList::tau.
Referenced by StdFace_FCOrtho(), StdFace_Orthorhombic(), StdFace_Pyrochlore(), StdFace_SetLabel(), and StdFace_Wannier90().
 {
   int iCell, jCell, kCell, ii;
   int nBox[3], jCellV[3];
   dR[0] = - (double)diW + StdI->tau[isiteUC][0] - StdI->tau[jsiteUC][0];
   dR[1] = - (double)diL + StdI->tau[isiteUC][1] - StdI->tau[jsiteUC][1];
   dR[2] = - (double)diH + StdI->tau[isiteUC][2] - StdI->tau[jsiteUC][2];
   jCellV[0] = iW + diW;
   jCellV[1] = iL + diL;
   jCellV[2] = iH + diH;
   StdFace_FoldSite(StdI, jCellV, nBox, jCellV);
   *Cphase = 1.0;
   for (ii = 0; ii < 3; ii++) *Cphase *= cpow(StdI->ExpPhase[ii], (double)nBox[ii]);
   for (kCell = 0; kCell < StdI->NCell; kCell++) {
     if (jCellV[0] == StdI->Cell[kCell][0] &&
         jCellV[1] == StdI->Cell[kCell][1] &&
         jCellV[2] == StdI->Cell[kCell][2])
     {
       jCell = kCell;
     }
     if (iW == StdI->Cell[kCell][0] &&
         iL == StdI->Cell[kCell][1] &&
         iH == StdI->Cell[kCell][2])
     {
       iCell = kCell;
     }
   }/*for (iCell = 0; iCell < StdI->NCell; iCell++)*/
   *isite = iCell * StdI->NsiteUC + isiteUC;
   *jsite = jCell * StdI->NsiteUC + jsiteUC;
   if (strcmp(StdI->model, "kondo") == 0) {
     *isite += StdI->NCell * StdI->NsiteUC;
     *jsite += StdI->NCell * StdI->NsiteUC;
   }
 }/*void StdFace_FindSite*/
StdFace_FoldSite()
static void StdFace_FoldSite (struct StdIntList * StdI, int iCellV[3], int nBox[3], int iCellV_fold[3]) static
Move a site into the original supercell if it is outside the original supercell.
Author
Mitsuaki Kawamura (The University of Tokyo)
(1) Transform to fractional coordinate (times NCell).
(2) Search which supercell contains this cell.
(3) Fractional coordinate (times NCell) in the original supercell
Parameters
[in,out] StdI
[in] iCellV The fractional coordinate of a site
[out] nBox the index of supercell
[out] iCellV_fold The fractional coordinate of a site which is moved into the original cell
Definition at line 595 of file StdFace_ModelUtil.c.
References StdIntList::box, StdIntList::NCell, and StdIntList::rbox.
Referenced by StdFace_FindSite(), and StdFace_InitSite().
 {
   int ii, jj, iCellV_frac[3];
   for (ii = 0; ii < 3; ii++) {
     iCellV_frac[ii] = 0;
     for (jj = 0; jj < 3; jj++)iCellV_frac[ii] += StdI->rbox[ii][jj] * iCellV[jj];
   }
   for (ii = 0; ii < 3; ii++)
     nBox[ii] = (iCellV_frac[ii] + StdI->NCell * 1000) / StdI->NCell - 1000;
   for (ii = 0; ii < 3; ii++)
     iCellV_frac[ii] -= StdI->NCell*(nBox[ii]);
   for (ii = 0; ii < 3; ii++) {
     iCellV_fold[ii] = 0;
     for (jj = 0; jj < 3; jj++) iCellV_fold[ii] += StdI->box[jj][ii] * iCellV_frac[jj];
     iCellV_fold[ii] = (iCellV_fold[ii] + StdI->NCell * 1000) / StdI->NCell - 1000;
   }/*for (ii = 0; ii < 3; ii++)*/
 }/*static void StdFace_FoldSite*/
StdFace_GeneralJ()
void StdFace_GeneralJ (struct StdIntList * StdI, double J[3][3], int Si2, int Sj2, int isite, int jsite)
Treat J as a 3*3 matrix [(6S + 1)*(6S' + 1) interactions].
Author
Mitsuaki Kawamura (The University of Tokyo)
If both spins are S=1/2 ...
Set StdIntList::Hund, StdIntList::HundIndx, StdIntList::Cinter, StdIntList::CinterIndx for \(S_{iz} S_{jz}\) term, and increase the number of them (StdIntList::NHund, StdIntList::NCinter). And ...
If there is no off-diagonal term, set StdIntList::Ex, StdIntList::ExIndx, StdIntList::PairLift, StdIntList::PLIndx and increase the number of them (StdIntList::NEx, StdIntList::NPairLift).
If S != 1/2 or there is an off-diagonal interaction, use the InterAll format.
(1)
\[ J_z S_{i z} * S_{j z} = J_z \sum_{\sigma, \sigma' = -S}^S \sigma \sigma' c_{i\sigma}^\dagger c_{i\sigma} c_{j\sigma'}^\dagger c_{j\sigma'} \]
(2)
\[ I S_i^+ S_j^- + I^* S_j^+ S_i^- = \sum_{\sigma, \sigma' = -S}^{S-1} \sqrt{S_i(S_i+1) - \sigma(\sigma+1)}\sqrt{S_j(S_j+1) - \sigma'(\sigma'+1)} (I c_{i\sigma+1}^\dagger c_{i\sigma} c_{j\sigma'}^\dagger c_{j\sigma'+1} + I^* c_{i\sigma}^\dagger c_{i\sigma+1} c_{j\sigma'+1}^\dagger c_{j\sigma'}) \\ I \equiv \frac{J_x + J_y + i(J_{xy} - J_{yx})}{4} \]
(3)
\[ I S_i^+ S_j^+ + I^* S_j^- S_i^- = \sum_{\sigma, \sigma' = -S}^{S-1} \sqrt{S_i(S_i+1) - \sigma(\sigma+1)}\sqrt{S_j(S_j+1) - \sigma'(\sigma'+1)} (I c_{i\sigma+1}^\dagger c_{i\sigma} c_{j\sigma'+1}^\dagger c_{j\sigma'} + I^* c_{i\sigma}^\dagger c_{i\sigma+1} c_{j\sigma'}^\dagger c_{j\sigma'+1}) \\ I \equiv \frac{J_x - J_y - i(J_{xy} + J_{yx})}{4} \]
(4)
\[ I S_i^+ S_{j z} + I^* S_{j z} S_i^-= \sum_{\sigma=-S}^{S-1} \sum_{\sigma' = -S}^{S} \sqrt{S_i(S_i+1) - \sigma(\sigma+1)} (I c_{i\sigma+1}^\dagger c_{i\sigma} c_{j\sigma'}^\dagger c_{j\sigma'} + I^* c_{j\sigma'}^\dagger c_{j\sigma'} c_{i\sigma}^\dagger c_{i\sigma+1}) \\ I \equiv \frac{J_{xz} - i J_{yz}}{2} \]
(5)
\[ I S_{i z} S_j^+ + I^* S_j^- S_{i z} = \sum_{\sigma=-S}^{S} \sum_{\sigma' = -S}^{S-1} \sqrt{S_j(S_j+1) - \sigma'(\sigma'+1)} (I c_{i\sigma}^\dagger c_{i\sigma} c_{j\sigma'+1}^\dagger c_{j\sigma'} + I^* c_{j\sigma'}^\dagger c_{j\sigma'+1} c_{i\sigma}^\dagger c_{i\sigma}) \\ I \equiv \frac{J_{zx} - i J_{zy}}{2} \]
Parameters
[in,out] StdI
[in] J The Spin interaction \(J_x, J_{xy}\), ...
[in] Si2 Spin moment in \(i\) site
[in] Sj2 Spin moment in \(j\) site
[in] isite \(i\) of \(S_i\)
[in] jsite \(j\) of \(S_j\)
Definition at line 223 of file StdFace_ModelUtil.c.
References StdIntList::Cinter, StdIntList::CinterIndx, StdIntList::Ex, StdIntList::ExIndx, StdIntList::Hund, StdIntList::HundIndx, StdIntList::J, StdIntList::model, StdIntList::NCinter, StdIntList::NEx, StdIntList::NHund, StdIntList::NPairLift, StdIntList::PairLift, StdIntList::PLIndx, and StdFace_intr().
Referenced by StdFace_Chain(), StdFace_FCOrtho(), StdFace_Honeycomb(), StdFace_Kagome(), StdFace_Ladder(), StdFace_Orthorhombic(), StdFace_Pyrochlore(), StdFace_Tetragonal(), StdFace_Triangular(), and StdFace_Wannier90().
 {
   int ispin, jspin, ZGeneral, ExGeneral;
   double Si, Sj, Siz, Sjz;
   double complex intr0;
   ZGeneral = 1;
   ExGeneral = 1;
   if (Si2 == 1 || Sj2 == 1) {
     ZGeneral = 0;
     StdI->Hund[StdI->NHund] = -0.5 * J[2][2];
     StdI->HundIndx[StdI->NHund][0] = isite;
     StdI->HundIndx[StdI->NHund][1] = jsite;
     StdI->NHund += 1;
     StdI->Cinter[StdI->NCinter] = -0.25 * J[2][2];
     StdI->CinterIndx[StdI->NCinter][0] = isite;
     StdI->CinterIndx[StdI->NCinter][1] = jsite;
     StdI->NCinter += 1;
     if (fabs(J[0][1]) < 0.000001 && fabs(J[1][0]) < 0.000001
 #if defined(_mVMC)
       && abs(J[0][0] - J[1][1]) < 0.000001
 #endif
       ) {
       ExGeneral = 0;
 #if defined(_mVMC)
       StdI->Ex[StdI->NEx] = - 0.25 * (J[0][0] + J[1][1]);
 #else
       if (strcmp(StdI->model, "kondo") == 0)
         StdI->Ex[StdI->NEx] = -0.25 * (J[0][0] + J[1][1]);
       else
         StdI->Ex[StdI->NEx] = 0.25 * (J[0][0] + J[1][1]);
 #endif
       StdI->ExIndx[StdI->NEx][0] = isite;
       StdI->ExIndx[StdI->NEx][1] = jsite;
       StdI->NEx += 1;
       StdI->PairLift[StdI->NPairLift] = 0.25 * (J[0][0] - J[1][1]);
       StdI->PLIndx[StdI->NPairLift][0] = isite;
       StdI->PLIndx[StdI->NPairLift][1] = jsite;
       StdI->NPairLift += 1;
     }/*if (fabs(J[0][1]) < 0.000001 && fabs(J[1][0]) < 0.000001)*/
   }
   Si = 0.5 * (double)Si2;
   Sj = 0.5 * (double)Sj2;
   for (ispin = 0; ispin <= Si2; ispin++) {
     Siz = (double)ispin - Si;
     for (jspin = 0; jspin <= Sj2; jspin++) {
       Sjz = (double)jspin - Sj;
       if (ZGeneral == 1) {
         intr0 = J[2][2] * Siz * Sjz;
         StdFace_intr(StdI, intr0,
           isite, ispin, isite, ispin, jsite, jspin, jsite, jspin);
       }
       if ((ispin < Si2 && jspin < Sj2) && ExGeneral == 1) {
         intr0 = 0.25 * (J[0][0] + J[1][1] + I*(J[0][1] - J[1][0]))
           * sqrt(Si * (Si + 1.0) - Siz * (Siz + 1.0))
           * sqrt(Sj * (Sj + 1.0) - Sjz * (Sjz + 1.0));
         StdFace_intr(StdI, intr0,
           isite, ispin + 1, isite, ispin, jsite, jspin, jsite, jspin + 1);
         StdFace_intr(StdI, conj(intr0),
           isite, ispin, isite, ispin + 1, jsite, jspin + 1, jsite, jspin);
       }
       if ((ispin < Si2 && jspin < Sj2) && ExGeneral == 1) {
         intr0 = 0.5 * 0.5 * (J[0][0] - J[1][1] - I*(J[0][1] + J[1][0]))
           * sqrt(Si * (Si + 1.0) - Siz * (Siz + 1.0))
           * sqrt(Sj * (Sj + 1.0) - Sjz * (Sjz + 1.0));
         StdFace_intr(StdI, intr0,
           isite, ispin + 1, isite, ispin, jsite, jspin + 1, jsite, jspin);
         StdFace_intr(StdI, conj(intr0),
           isite, ispin, isite, ispin + 1, jsite, jspin, jsite, jspin + 1);
       }
       if (ispin < Si2) {
         intr0 = 0.5 * (J[0][2] - I * J[1][2]) * sqrt(Si * (Si + 1.0) - Siz * (Siz + 1.0)) * Sjz;
         StdFace_intr(StdI, intr0,
           isite, ispin + 1, isite, ispin, jsite, jspin, jsite, jspin);
         StdFace_intr(StdI, conj(intr0),
           jsite, jspin, jsite, jspin, isite, ispin, isite, ispin + 1);
       }/*if (ispin < Si2)*/
       if (jspin < Sj2) {
         intr0 = 0.5 * (J[2][0] - I * J[2][1]) * Siz * sqrt(Sj * (Sj + 1.0) - Sjz * (Sjz + 1.0));
         StdFace_intr(StdI, intr0,
           isite, ispin, isite, ispin, jsite, jspin + 1, jsite, jspin);
         StdFace_intr(StdI, conj(intr0),
           jsite, jspin, jsite, jspin + 1, isite, ispin, isite, ispin);
       }/*if (jspin < Sj2)*/
     }/*for (jspin = 0; jspin <= Sj2; jspin++)*/
   }/*for (ispin = 0; ispin <= Si2; ispin++)*/
 }/*StdFace_GeneralJ*/
StdFace_Hopping()
void StdFace_Hopping (struct StdIntList * StdI, double complex trans0, int isite, int jsite, double * dR)
Add Hopping for the both spin.
Author
Mitsuaki Kawamura (The University of Tokyo)
Both \(c_{i \sigma}^\dagger c_{j \sigma}\) and \(c_{j \sigma}^\dagger c_{i \sigma}\) for every spin channel (\(\sigma\)) is specified
Parameters
[in,out] StdI
[in] trans0 Hopping integral \(t\)
[in] isite \(i\) for \(c_{i \sigma}^\dagger\)
[in] jsite \(j\) for \(c_{j \sigma}\)
[in] dR R_i - R_j
Definition at line 75 of file StdFace_ModelUtil.c.
References StdIntList::At, StdIntList::Lanczos_max, StdIntList::method, StdIntList::npump, StdIntList::pump, StdIntList::PumpBody, StdIntList::pumpindx, and StdFace_trans().
Referenced by StdFace_Chain(), StdFace_FCOrtho(), StdFace_Honeycomb(), StdFace_Kagome(), StdFace_Ladder(), StdFace_Orthorhombic(), StdFace_Pyrochlore(), StdFace_Tetragonal(), StdFace_Triangular(), and StdFace_Wannier90().
 {
   int ispin, it, ii;
   double complex Cphase, coef;
 #if defined(_HPhi)
   if (strcmp(StdI->method, "timeevolution") == 0 && StdI->PumpBody == 1) {
     for (it = 0; it < StdI->Lanczos_max; it++) {
       Cphase = 0.0f;
       for (ii = 0; ii < 3; ii++) Cphase += /*2.0*StdI->pi */ StdI->At[it][ii] * dR[ii];
       coef = cos(Cphase) + I * sin(-Cphase);
       for (ispin = 0; ispin < 2; ispin++) {
         StdI->pump[it][StdI->npump[it]] = coef * trans0;
         StdI->pumpindx[it][StdI->npump[it]][0] = isite;
         StdI->pumpindx[it][StdI->npump[it]][1] = ispin;
         StdI->pumpindx[it][StdI->npump[it]][2] = jsite;
         StdI->pumpindx[it][StdI->npump[it]][3] = ispin;
         StdI->npump[it] = StdI->npump[it] + 1;
         StdI->pump[it][StdI->npump[it]] = conj(coef * trans0);
         StdI->pumpindx[it][StdI->npump[it]][0] = jsite;
         StdI->pumpindx[it][StdI->npump[it]][1] = ispin;
         StdI->pumpindx[it][StdI->npump[it]][2] = isite;
         StdI->pumpindx[it][StdI->npump[it]][3] = ispin;
         StdI->npump[it] = StdI->npump[it] + 1;
       }/*for (ispin = 0; ispin < 2; ispin++)*/
     }/*for (it = 0; it < StdI->Lanczos_max; it++)*/
   }/*if (strcmp(StdI->method, "timeevolution") == 0)*/
   else
 #endif
     for (ispin = 0; ispin < 2; ispin++) {
       StdFace_trans(StdI, trans0, jsite, ispin, isite, ispin);
       StdFace_trans(StdI, conj(trans0), isite, ispin, jsite, ispin);
     }/*for (ispin = 0; ispin < 2; ispin++)*/
 }/*void StdFace_Hopping*/
StdFace_HubbardLocal()
void StdFace_HubbardLocal (struct StdIntList * StdI, double mu0, double h0, double Gamma0, double U0, int isite)
Add intra-Coulomb, magnetic field, chemical potential for the itenerant electron.
Author
Mitsuaki Kawamura (The University of Tokyo)
Set StdIntList::Cintra and StdIntList::CintraIndx with the input argument and increase the number of them (StdIntList::NCintra).
Parameters
[in,out] StdI
[in] mu0 Chemical potential
[in] h0 Longitudinal magnetic feild
[in] Gamma0 Transvers magnetic feild
[in] U0 Intra-site Coulomb potential
[in] isite i for \(c_{i \sigma}^\dagger\)
Definition at line 125 of file StdFace_ModelUtil.c.
References StdIntList::Cintra, StdIntList::CintraIndx, StdIntList::NCintra, and StdFace_trans().
Referenced by StdFace_Chain(), StdFace_FCOrtho(), StdFace_Honeycomb(), StdFace_Kagome(), StdFace_Ladder(), StdFace_Orthorhombic(), StdFace_Pyrochlore(), StdFace_Tetragonal(), StdFace_Triangular(), and StdFace_Wannier90().
 {
   StdFace_trans(StdI, mu0 + 0.5 * h0, isite, 0, isite, 0);
   StdFace_trans(StdI, mu0 - 0.5 * h0, isite, 1, isite, 1);
   StdFace_trans(StdI, -0.5 * Gamma0, isite, 1, isite, 0);
   StdFace_trans(StdI, -0.5 * Gamma0, isite, 0, isite, 1);
   StdI->Cintra[StdI->NCintra] = U0;
   StdI->CintraIndx[StdI->NCintra][0] = isite;
   StdI->NCintra += 1;
 }/*void StdFace_HubbardLocal*/
StdFace_InitSite()
void StdFace_InitSite (struct StdIntList * StdI, FILE * fp, int dim)
Initialize the super-cell where simulation is performed.
Author
Mitsuaki Kawamura (The University of Tokyo)
(1) Check Input parameters about the shape of super-cell
(2) Define the phase factor at each boundary. Set anti-period flag (StdIntList::AntiPeriod).
(3) Malloc StdIntList::tau, intrinsic structure of unit-cell
(4) Calculate reciprocal lattice vectors (times StdIntList::NCell, the number of unit-cells) for folding sites. store in StdIntList::rbox.
(5) Find Cells in the super-cell (5-1) Find the lower- and the upper bound for surrowndinf the super-cell
(5-2) Find cells in the super-cell (StdIntList::Cell, the fractional coordinate)
(6) For 2D system, print header of lattice.gp
Parameters
[in,out] StdI
[in] fp File pointer to lattice.gp
[in] dim dimension of system, if = 2, print lattice.gp
Definition at line 632 of file StdFace_ModelUtil.c.
References StdIntList::AntiPeriod, StdIntList::box, StdIntList::Cell, StdIntList::direct, StdIntList::ExpPhase, StdIntList::Height, StdIntList::L, StdIntList::NaN_i, StdIntList::NCell, StdIntList::NsiteUC, StdIntList::phase, StdIntList::pi180, StdIntList::rbox, StdFace_exit(), StdFace_FoldSite(), StdFace_PrintVal_i(), StdIntList::tau, and StdIntList::W.
Referenced by StdFace_Chain(), StdFace_FCOrtho(), StdFace_Honeycomb(), StdFace_Kagome(), StdFace_Ladder(), StdFace_Orthorhombic(), StdFace_Pyrochlore(), StdFace_Tetragonal(), StdFace_Triangular(), and StdFace_Wannier90().
 {
   int bound[3][2], edge, ii, jj;
   int ipos;
   int nBox[3], iCellV_fold[3], iCellV[3];
   double pos[4][2], xmin, xmax/*, offset[2], scale*/;
   fprintf(stdout, "\n  @ Super-Lattice setting\n\n");
   if (
     (StdI->L != StdI->NaN_i || StdI->W != StdI->NaN_i || StdI->Height != StdI->NaN_i)
     &&
     (StdI->box[0][0] != StdI->NaN_i || StdI->box[0][1] != StdI->NaN_i || StdI->box[0][2] != StdI->NaN_i ||
      StdI->box[1][0] != StdI->NaN_i || StdI->box[1][1] != StdI->NaN_i || StdI->box[1][2] != StdI->NaN_i ||
      StdI->box[2][0] != StdI->NaN_i || StdI->box[2][1] != StdI->NaN_i || StdI->box[2][2] != StdI->NaN_i)
     )
   {
     fprintf(stdout, "\nERROR ! (L, W, Height) and (a0W, ..., a2H) conflict !\n\n");
     StdFace_exit(-1);
   }
   else if (StdI->L != StdI->NaN_i || StdI->W != StdI->NaN_i || StdI->Height != StdI->NaN_i)
   {
     StdFace_PrintVal_i("L", &StdI->L, 1);
     StdFace_PrintVal_i("W", &StdI->W, 1);
     StdFace_PrintVal_i("Height", &StdI->Height, 1);
     for (ii = 0; ii < 3; ii++) for (jj = 0; jj < 3; jj++)
       StdI->box[ii][jj] = 0;
     StdI->box[0][0] = StdI->W;
     StdI->box[1][1] = StdI->L;
     StdI->box[2][2] = StdI->Height;
   }
   else
   {
     StdFace_PrintVal_i("a0W", &StdI->box[0][0], 1);
     StdFace_PrintVal_i("a0L", &StdI->box[0][1], 0);
     StdFace_PrintVal_i("a0H", &StdI->box[0][2], 0);
     StdFace_PrintVal_i("a1W", &StdI->box[1][0], 0);
     StdFace_PrintVal_i("a1L", &StdI->box[1][1], 1);
     StdFace_PrintVal_i("a1H", &StdI->box[1][2], 0);
     StdFace_PrintVal_i("a2W", &StdI->box[2][0], 0);
     StdFace_PrintVal_i("a2L", &StdI->box[2][1], 0);
     StdFace_PrintVal_i("a2H", &StdI->box[2][2], 1);
   }
   /*
    Parameters for the 3D system will not used.
   */
   if (dim == 2) {
     StdI->direct[0][2] = 0.0;
     StdI->direct[1][2] = 0.0;
     StdI->direct[2][0] = 0.0;
     StdI->direct[2][1] = 0.0;
     StdI->direct[2][2] = 1.0;
   }
   if (dim == 2) StdI->phase[2] = 0.0;
   for (ii = 0; ii < 3; ii++) {
     StdI->ExpPhase[ii] = cos(StdI->pi180 * StdI->phase[ii]) + I*sin(StdI->pi180 * StdI->phase[ii]);
     if (cabs(StdI->ExpPhase[ii] + 1.0) < 0.000001) StdI->AntiPeriod[ii] = 1;
     else StdI->AntiPeriod[ii] = 0;
   }
   StdI->tau = (double **)malloc(sizeof(double*) * StdI->NsiteUC);
   for (ii = 0; ii < StdI->NsiteUC; ii++) {
     StdI->tau[ii] = (double *)malloc(sizeof(double) * 3);
   }
   StdI->NCell = 0;
   for (ii = 0; ii < 3; ii++) {
     StdI->NCell += StdI->box[0][ii]
       * StdI->box[1][(ii + 1) % 3]
       * StdI->box[2][(ii + 2) % 3]
       - StdI->box[0][ii]
       * StdI->box[1][(ii + 2) % 3]
       * StdI->box[2][(ii + 1) % 3];
   }
   printf("   Number of Cell = %d\n", abs(StdI->NCell));
   if (StdI->NCell == 0) {
     StdFace_exit(-1);
   }
   for (ii = 0; ii < 3; ii++) {
     for (jj = 0; jj < 3; jj++) {
       StdI->rbox[ii][jj] = StdI->box[(ii + 1) % 3][(jj + 1) % 3] * StdI->box[(ii + 2) % 3][(jj + 2) % 3]
                          - StdI->box[(ii + 1) % 3][(jj + 2) % 3] * StdI->box[(ii + 2) % 3][(jj + 1) % 3];
     }
   }
   if (StdI->NCell < 0) {
     for (ii = 0; ii < 3; ii++)
       for (jj = 0; jj < 3; jj++)
         StdI->rbox[ii][jj] *= -1;
     StdI->NCell *= -1;
   }/*if (StdI->NCell < 0)*/
   for (ii = 0; ii < 3; ii++) {
     bound[ii][0] = 0;
     bound[ii][1] = 0;
     for (nBox[2] = 0; nBox[2] < 2; nBox[2]++) {
       for (nBox[1] = 0; nBox[1] < 2; nBox[1]++) {
         for (nBox[0] = 0; nBox[0] < 2; nBox[0]++) {
           edge = 0;
           for (jj = 0; jj < 3; jj++) edge += nBox[jj] * StdI->box[jj][ii];
           if (edge < bound[ii][0]) bound[ii][0] = edge;
           if (edge > bound[ii][1]) bound[ii][1] = edge;
         }
       }
     }
   }
   StdI->Cell = (int **)malloc(sizeof(int*) * StdI->NCell);
   for (ii = 0; ii < StdI->NCell; ii++) {
     StdI->Cell[ii] = (int *)malloc(sizeof(int) * 3);
   }/*for (ii = 0; ii < StdI->NCell; ii++)*/
   jj = 0;
   for (iCellV[2] = bound[2][0]; iCellV[2] <= bound[2][1]; iCellV[2]++) {
     for (iCellV[1] = bound[1][0]; iCellV[1] <= bound[1][1]; iCellV[1]++) {
       for (iCellV[0] = bound[0][0]; iCellV[0] <= bound[0][1]; iCellV[0]++) {
         StdFace_FoldSite(StdI, iCellV, nBox, iCellV_fold);
         if (nBox[0] == 0 && nBox[1] == 0 && nBox[2] == 0) {
           for (ii = 0; ii < 3; ii++)
             StdI->Cell[jj][ii] = iCellV[ii];
           jj += 1;
         }/*if (lUC == 1)*/
       }/*for (iCellV[0] = bound[0][0]; iCellV[0] <= bound[0][1]; iCellV[0]++*/
     }/*for (iCellV[1] = bound[1][0]; iCellV[1] <= bound[1][1]; iCellV[1]++)*/
   }/*for (iCellV[2] = bound[2][0]; iCellV[2] <= bound[2][1]; iCellV[2]++)*/
   if (dim == 2) {
     pos[0][0] = 0.0;
     pos[0][1] = 0.0;
     pos[1][0] = StdI->direct[0][0] * (double)StdI->box[0][0] + StdI->direct[1][0] * (double)StdI->box[0][1];
     pos[1][1] = StdI->direct[0][1] * (double)StdI->box[0][0] + StdI->direct[1][1] * (double)StdI->box[0][1];
     pos[2][0] = StdI->direct[0][0] * (double)StdI->box[1][0] + StdI->direct[1][0] * (double)StdI->box[1][1];
     pos[2][1] = StdI->direct[0][1] * (double)StdI->box[1][0] + StdI->direct[1][1] * (double)StdI->box[1][1];
     pos[3][0] = pos[1][0] + pos[2][0];
     pos[3][1] = pos[1][1] + pos[2][1];
     xmin = 0.0;
     xmax = 0.0;
     for (ipos = 0; ipos < 4; ipos++) {
       if (pos[ipos][0] < xmin) xmin = pos[ipos][0];
       if (pos[ipos][0] > xmax) xmax = pos[ipos][0];
       if (pos[ipos][1] < xmin) xmin = pos[ipos][1];
       if (pos[ipos][1] > xmax) xmax = pos[ipos][1];
     }
     xmin -= 2.0;
     xmax += 2.0;
     fprintf(fp, "#set terminal pdf color enhanced \\\n");
     fprintf(fp, "#dashed dl 1.0 size 20.0cm, 20.0cm \n");
     fprintf(fp, "#set output \"lattice.pdf\"\n");
     fprintf(fp, "set xrange [%f: %f]\n", xmin, xmax);
     fprintf(fp, "set yrange [%f: %f]\n", xmin, xmax);
     fprintf(fp, "set size square\n");
     fprintf(fp, "unset key\n");
     fprintf(fp, "unset tics\n");
     fprintf(fp, "unset border\n");
     fprintf(fp, "set style line 1 lc 1 lt 1\n");
     fprintf(fp, "set style line 2 lc 5 lt 1\n");
     fprintf(fp, "set style line 3 lc 0 lt 1\n");
     fprintf(fp, "set arrow from %f, %f to %f, %f nohead front ls 3\n", pos[0][0], pos[0][1], pos[1][0], pos[1][1]);
     fprintf(fp, "set arrow from %f, %f to %f, %f nohead front ls 3\n", pos[1][0], pos[1][1], pos[3][0], pos[3][1]);
     fprintf(fp, "set arrow from %f, %f to %f, %f nohead front ls 3\n", pos[3][0], pos[3][1], pos[2][0], pos[2][1]);
     fprintf(fp, "set arrow from %f, %f to %f, %f nohead front ls 3\n", pos[2][0], pos[2][1], pos[0][0], pos[0][1]);
   }/*if (dim == 2)*/
 }/*void StdFace_InitSite2D*/
StdFace_InputCoulombV()
void StdFace_InputCoulombV (struct StdIntList * StdI, double * V0, char * V0name)
Input off-site Coulomb interaction from the input file, if it is not specified, use the default value (0 or the isotropic Coulomb interaction StdIntList::V).
Parameters
[in,out] StdI
[in] V0
[in] V0name E.g. V1
Definition at line 1109 of file StdFace_ModelUtil.c.
References StdFace_exit(), StdIntList::V, and StdIntList::V0.
Referenced by StdFace_Chain(), StdFace_FCOrtho(), StdFace_Honeycomb(), StdFace_Kagome(), StdFace_Ladder(), StdFace_Orthorhombic(), StdFace_Pyrochlore(), StdFace_Tetragonal(), and StdFace_Triangular().
 {
   if (isnan(StdI->V) == 0 && isnan(*V0) == 0) {
     fprintf(stdout, "\n ERROR! V and %s conflict !\n\n", V0name);
     StdFace_exit(-1);
   }
   else if (isnan(*V0) == 0)
     fprintf(stdout, "  %15s = %-10.5f\n", V0name, *V0);
   else if (isnan(StdI->V) == 0) {
     *V0 = StdI->V;
     fprintf(stdout, "  %15s = %-10.5f\n", V0name, *V0);
   }
   else {
     *V0 = 0.0;
   }
 }/*void StdFace_InputCoulombV*/
StdFace_InputHopp()
void StdFace_InputHopp (struct StdIntList * StdI, double complex * t0, char * t0name)
Input hopping integral from the input file, if it is not specified, use the default value(0 or the isotropic hopping StdIntList::V).
Parameters
[in,out] StdI
[in] t0
[in] t0name E.g. t1
Definition at line 1134 of file StdFace_ModelUtil.c.
References StdFace_exit(), StdIntList::t, and StdIntList::t0.
Referenced by StdFace_Chain(), StdFace_FCOrtho(), StdFace_Honeycomb(), StdFace_Kagome(), StdFace_Ladder(), StdFace_Orthorhombic(), StdFace_Pyrochlore(), StdFace_Tetragonal(), and StdFace_Triangular().
 {
   if (isnan(creal(StdI->t)) == 0 && isnan(creal(*t0)) == 0) {
     fprintf(stdout, "\n ERROR! t and %s conflict !\n\n", t0name);
     StdFace_exit(-1);
   }
   else if (isnan(creal(*t0)) == 0)
     fprintf(stdout, "  %15s = %-10.5f %-10.5f\n", t0name, creal(*t0), cimag(*t0));
   else if (isnan(creal(StdI->t)) == 0) {
     *t0 = StdI->t;
     fprintf(stdout, "  %15s = %-10.5f %-10.5f\n", t0name, creal(*t0), cimag(*t0));
   }
   else {
     *t0 = 0.0;
   }
 }/*void StdFace_InputHopp*/
StdFace_InputSpin()
void StdFace_InputSpin (struct StdIntList * StdI, double Jp[3][3], double JpAll, char * Jpname)
Input spin-spin interaction other than nearest-neighbor.
Parameters
[in,out] StdI
[in] Jp Fully anisotropic spin interaction
[in] JpAll The isotropic interaction
Jpname The name of this spin interaction(e.g.J')
Definition at line 1060 of file StdFace_ModelUtil.c.
References StdIntList::Jp, StdIntList::JpAll, and StdFace_exit().
Referenced by StdFace_Chain(), StdFace_FCOrtho(), StdFace_Honeycomb(), StdFace_Kagome(), StdFace_Ladder(), StdFace_Orthorhombic(), StdFace_Pyrochlore(), StdFace_Tetragonal(), and StdFace_Triangular().
 {
   int i1, i2;
   char Jname[3][3][10];
   strcpy(Jname[0][0], "x\0");
   strcpy(Jname[0][1], "xy\0");
   strcpy(Jname[0][2], "xz\0");
   strcpy(Jname[1][0], "yx\0");
   strcpy(Jname[1][1], "y\0");
   strcpy(Jname[1][2], "yz\0");
   strcpy(Jname[2][0], "zx\0");
   strcpy(Jname[2][1], "zy\0");
   strcpy(Jname[2][2], "z\0");
   for (i1 = 0; i1 < 3; i1++) {
     for (i2 = 0; i2 < 3; i2++) {
       if (isnan(JpAll) == 0 && isnan(Jp[i1][i2]) == 0) {
         fprintf(stdout, "\n ERROR! %s and %s%s conflict !\n\n", Jpname,
           Jpname, Jname[i1][i2]);
         StdFace_exit(-1);
       }
     }/*for (j = 0; j < 3; j++)*/
   }/*for (i = 0; i < 3; i++)*/
   for (i1 = 0; i1 < 3; i1++) {
     for (i2 = 0; i2 < 3; i2++) {
       if (isnan(Jp[i1][i2]) == 0)
         fprintf(stdout, "  %14s%s = %-10.5f\n", Jpname, Jname[i1][i2], Jp[i1][i2]);
       else if (i1 == i2 && isnan(JpAll) == 0) {
         Jp[i1][i2] = JpAll;
         fprintf(stdout, "  %14s%s = %-10.5f\n", Jpname, Jname[i1][i2], Jp[i1][i2]);
       }
       else {
         Jp[i1][i2] = 0.0;
       }
     }/*for (i2 = 0; i2 < 3; i2++)*/
   }/*for (i = 0; i < 3; i++)*/
 }/*void StdFace_InputSpin*/
StdFace_InputSpinNN()
void StdFace_InputSpinNN (struct StdIntList * StdI, double J0[3][3], double J0All, char * J0name)
Input nearest-neighbor spin-spin interaction.
Parameters
[in,out] StdI
[in] J0 The anisotropic spin interaction
[in] J0All The isotropic interaction
[in] J0name The name of this spin interaction (e.g. J1)
Definition at line 973 of file StdFace_ModelUtil.c.
References StdIntList::J, StdIntList::J0, StdIntList::J0All, StdIntList::JAll, and StdFace_exit().
Referenced by StdFace_Chain(), StdFace_FCOrtho(), StdFace_Honeycomb(), StdFace_Kagome(), StdFace_Orthorhombic(), StdFace_Pyrochlore(), StdFace_Tetragonal(), and StdFace_Triangular().
 {
   int i1, i2, i3, i4;
   char Jname[3][3][10];
   strcpy(Jname[0][0], "x\0");
   strcpy(Jname[0][1], "xy\0");
   strcpy(Jname[0][2], "xz\0");
   strcpy(Jname[1][0], "yx\0");
   strcpy(Jname[1][1], "y\0");
   strcpy(Jname[1][2], "yz\0");
   strcpy(Jname[2][0], "zx\0");
   strcpy(Jname[2][1], "zy\0");
   strcpy(Jname[2][2], "z\0");
   if (isnan(StdI->JAll) == 0 && isnan(J0All)  == 0) {
     fprintf(stdout, "\n ERROR! J and %s conflict !\n\n", J0name);
     StdFace_exit(-1);
   }
   for (i1 = 0; i1 < 3; i1++) {
     for (i2 = 0; i2 < 3; i2++) {
       if (isnan(StdI->JAll) == 0 && isnan(StdI->J[i1][i2]) == 0) {
         fprintf(stdout, "\n ERROR! J and J%s conflict !\n\n", Jname[i1][i2]);
         StdFace_exit(-1);
       }
       else if (isnan(J0All) == 0 && isnan(StdI->J[i1][i2]) == 0) {
         fprintf(stdout, "\n ERROR! %s and J%s conflict !\n\n",
           J0name, Jname[i1][i2]);
         StdFace_exit(-1);
       }
       else if (isnan(J0All) == 0 && isnan(J0[i1][i2]) == 0) {
         fprintf(stdout, "\n ERROR! %s and %s%s conflict !\n\n", J0name,
           J0name, Jname[i1][i2]);
         StdFace_exit(-1);
       }
       else if (isnan(J0[i1][i2]) == 0 && isnan(StdI->JAll) == 0) {
         fprintf(stdout, "\n ERROR! %s%s and J conflict !\n\n",
           J0name, Jname[i1][i2]);
         StdFace_exit(-1);
       }
     }/*for (j = 0; j < 3; j++)*/
   }/*for (i = 0; i < 3; i++)*/
   for (i1 = 0; i1 < 3; i1++) {
     for (i2 = 0; i2 < 3; i2++) {
       for (i3 = 0; i3 < 3; i3++) {
         for (i4 = 0; i4 < 3; i4++) {
           if (isnan(J0[i1][i2]) == 0 && isnan(StdI->J[i3][i4]) == 0) {
             fprintf(stdout, "\n ERROR! %s%s and J%s conflict !\n\n",
               J0name, Jname[i1][i2], Jname[i3][i4]);
             StdFace_exit(-1);
           }
         }/*for (i4 = 0; i4 < 3; i4++)*/
       }/*for (i3 = 0; i3 < 3; i3++)*/
     }/*for (j = 0; j < 3; j++)*/
   }/*for (i = 0; i < 3; i++)*/
   for (i1 = 0; i1 < 3; i1++) {
     for (i2 = 0; i2 < 3; i2++) {
       if (isnan(J0[i1][i2]) == 0)
         fprintf(stdout, "  %14s%s = %-10.5f\n", J0name, Jname[i1][i2], J0[i1][i2]);
       else if (isnan(StdI->J[i1][i2]) == 0) {
         J0[i1][i2] = StdI->J[i1][i2];
         fprintf(stdout, "  %14s%s = %-10.5f\n", J0name, Jname[i1][i2], J0[i1][i2]);
       }
       else if (i1 == i2 && isnan(J0All) == 0) {
         J0[i1][i2] = J0All;
         fprintf(stdout, "  %14s%s = %-10.5f\n", J0name, Jname[i1][i2], J0[i1][i2]);
       }
       else if (i1 == i2 && isnan(StdI->JAll) == 0) {
         J0[i1][i2] = StdI->JAll;
         fprintf(stdout, "  %14s%s = %-10.5f\n", J0name, Jname[i1][i2], J0[i1][i2]);
       }
       else {
         J0[i1][i2] = 0.0;
       }
     }/*for (i2 = 0; i2 < 3; i2++)*/
   }/*for (i = 0; i < 3; i++)*/
 }/*void StdFace_InputSpinNN*/
StdFace_intr()
void StdFace_intr (struct StdIntList * StdI, double complex intr0, int site1, int spin1, int site2, int spin2, int site3, int spin3, int site4, int spin4)
Add interaction (InterAll) to the list Set StdIntList::intr and StdIntList::intrindx and increase the number of that (StdIntList::nintr).
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in,out] StdI
[in] intr0 Interaction \(U, V, J\), etc.
[in] site1 \(i_1\) for \(c_{i_1 \sigma_1}^\dagger\)
[in] spin1 \(sigma1_1\) for \(c_{i_1 \sigma_1}^\dagger\)
[in] site2 \(i_2\) for \(c_{i_2 \sigma_2}\)
[in] spin2 \(sigma1_2\) for \(c_{i_2 \sigma_2}\)
[in] site3 \(i_3\) for \(c_{i_3 \sigma_3}^\dagger\)
[in] spin3 \(sigma1_3\) for \(c_{i_3 \sigma_3}^\dagger\)
[in] site4 \(i_2\) for \(c_{i_2 \sigma_2}\)
[in] spin4 \(sigma1_2\) for \(c_{i_2 \sigma_2}\)
Definition at line 199 of file StdFace_ModelUtil.c.
References StdIntList::intr, StdIntList::intrindx, and StdIntList::nintr.
Referenced by StdFace_GeneralJ().
 {
   StdI->intr[StdI->nintr] = intr0;
   StdI->intrindx[StdI->nintr][0] = site1; StdI->intrindx[StdI->nintr][1] = spin1;
   StdI->intrindx[StdI->nintr][2] = site2; StdI->intrindx[StdI->nintr][3] = spin2;
   StdI->intrindx[StdI->nintr][4] = site3; StdI->intrindx[StdI->nintr][5] = spin3;
   StdI->intrindx[StdI->nintr][6] = site4; StdI->intrindx[StdI->nintr][7] = spin4;
   StdI->nintr = StdI->nintr + 1;
 }/*void StdFace_intr*/
StdFace_MagField()
void StdFace_MagField (struct StdIntList * StdI, int S2, double h, double Gamma, int isite)
Add longitudinal and transvars magnetic field to the list.
Author
Mitsuaki Kawamura (The University of Tokyo)
Use Bogoliubov representation.
Londitudinal part
\[ \sum_{\sigma = -S}^{S} -h\sigma c_{i \sigma}^\dagger c_{i \sigma} \]
Transvars part
\[ -\Gamma \frac{S_i^+ + S_i^-}{2} = \sum_{\sigma = -S}^{S-1} -\frac{\Gamma}{2} \sqrt{S(S+1) - \sigma(\sigma+1)} (\sigma c_{i \sigma+ 1}^\dagger c_{i \sigma} + \sigma c_{i \sigma}^\dagger c_{i \sigma+1}) \]
Parameters
[in,out] StdI
[in] S2 Spin moment in \(i\) site
[in] h Longitudinal magnetic field \(h\)
[in] Gamma Transvars magnetic field \(h\)
[in] isite \(i\) for \(c_{i \sigma}^\dagger\)
Definition at line 151 of file StdFace_ModelUtil.c.
References StdIntList::Gamma, StdIntList::h, StdIntList::S2, and StdFace_trans().
Referenced by StdFace_Chain(), StdFace_FCOrtho(), StdFace_Honeycomb(), StdFace_Kagome(), StdFace_Ladder(), StdFace_Orthorhombic(), StdFace_Pyrochlore(), StdFace_Tetragonal(), StdFace_Triangular(), and StdFace_Wannier90().
 {
   int ispin;
   double S, Sz;
   S = (double)S2 * 0.5;
   for (ispin = 0; ispin <= S2; ispin++){
     Sz = (double)ispin - S;
     StdFace_trans(StdI, -h * Sz, isite, ispin, isite, ispin);
     if (ispin < S2) {
       StdFace_trans(StdI, -0.5 * Gamma * sqrt(S*(S + 1.0) - Sz*(Sz + 1.0)),
         isite, ispin + 1, isite, ispin);
       StdFace_trans(StdI, -0.5 * Gamma * sqrt(S*(S + 1.0) - Sz*(Sz + 1.0)),
         isite, ispin, isite, ispin + 1);
     }/*if (ispin < S2)*/
   }/*for (ispin = 0; ispin <= S2; ispin++)*/
 }/*void StdFace_MagField*/
StdFace_MallocInteractions()
void StdFace_MallocInteractions (struct StdIntList * StdI, int ntransMax, int nintrMax)
Malloc Arrays for interactions.
(1) Transfer StdIntList::trans, StdIntList::transindx
(2) InterAll StdIntList::intr, StdIntList::intrindx
(3) Coulomb intra StdIntList::Cintra, StdIntList::CintraIndx
(4) Coulomb inter StdIntList::Cinter, StdIntList::CinterIndx
(5) Hund StdIntList::Hund, StdIntList::HundIndx
(6) Excahnge StdIntList::Ex, StdIntList::ExIndx
(7) PairLift StdIntList::PairLift, StdIntList::PLIndx
(7) PairHopp StdIntList::PairHopp, StdIntList::PHIndx
Parameters
[in,out] StdI
[in] ntransMax upper limit of the number of transfer
[in] nintrMax upper limit of the number of interaction
Definition at line 1198 of file StdFace_ModelUtil.c.
References StdIntList::Cinter, StdIntList::CinterIndx, StdIntList::Cintra, StdIntList::CintraIndx, StdIntList::Ex, StdIntList::ExIndx, StdIntList::Hund, StdIntList::HundIndx, StdIntList::intr, StdIntList::intrindx, StdIntList::Lanczos_max, StdIntList::method, StdIntList::NCinter, StdIntList::NCintra, StdIntList::NEx, StdIntList::NHund, StdIntList::nintr, StdIntList::NPairHopp, StdIntList::NPairLift, StdIntList::npump, StdIntList::ntrans, StdIntList::PairHopp, StdIntList::PairLift, StdIntList::PHIndx, StdIntList::PLIndx, StdIntList::pump, StdIntList::PumpBody, StdIntList::pumpindx, StdIntList::trans, and StdIntList::transindx.
Referenced by StdFace_Chain(), StdFace_FCOrtho(), StdFace_Honeycomb(), StdFace_Kagome(), StdFace_Ladder(), StdFace_Orthorhombic(), StdFace_Pyrochlore(), StdFace_Tetragonal(), StdFace_Triangular(), and StdFace_Wannier90().
   {
   int ii;
 #if defined(_HPhi)
   int it;
 #endif
   StdI->transindx = (int **)malloc(sizeof(int*) * ntransMax);
   StdI->trans = (double complex *)malloc(sizeof(double complex) * ntransMax);
   for (ii = 0; ii < ntransMax; ii++) {
     StdI->transindx[ii] = (int *)malloc(sizeof(int) * 4);
   }
   StdI->ntrans = 0;
 #if defined(_HPhi)
   if (strcmp(StdI->method, "timeevolution") == 0 && StdI->PumpBody == 1) {
     StdI->npump = (int *)malloc(sizeof(int) * StdI->Lanczos_max);
     StdI->pumpindx = (int ***)malloc(sizeof(int**) * StdI->Lanczos_max);
     StdI->pump = (double complex **)malloc(sizeof(double complex*) * StdI->Lanczos_max);
     for (it = 0; it < StdI->Lanczos_max; it++) {
       StdI->npump[it] = 0;
       StdI->pumpindx[it] = (int **)malloc(sizeof(int*) * ntransMax);
       StdI->pump[it] = (double complex *)malloc(sizeof(double complex) * ntransMax);
       for (ii = 0; ii < ntransMax; ii++) {
         StdI->pumpindx[it][ii] = (int *)malloc(sizeof(int) * 4);
       }
     }/*for (it = 0; it < StdI->Lanczos_max;)*/
   }/*if (strcmp(StdI->method, "timeevolution") == 0*/
 #endif
   StdI->intrindx = (int **)malloc(sizeof(int*) * nintrMax);
   StdI->intr = (double complex *)malloc(sizeof(double complex) * nintrMax);
   for (ii = 0; ii < nintrMax; ii++) {
     StdI->intrindx[ii] = (int *)malloc(sizeof(int) * 8);
   }
   StdI->nintr = 0;
   StdI->CintraIndx = (int **)malloc(sizeof(int*) * nintrMax);
   StdI->Cintra = (double *)malloc(sizeof(double) * nintrMax);
   for (ii = 0; ii < nintrMax; ii++) {
     StdI->CintraIndx[ii] = (int *)malloc(sizeof(int) * 1);
   }
   StdI->NCintra = 0;
   StdI->CinterIndx = (int **)malloc(sizeof(int*) * nintrMax);
   StdI->Cinter = (double *)malloc(sizeof(double) * nintrMax);
   for (ii = 0; ii < nintrMax; ii++) {
     StdI->CinterIndx[ii] = (int *)malloc(sizeof(int) * 2);
   }
   StdI->NCinter = 0;
   StdI->HundIndx = (int **)malloc(sizeof(int*) * nintrMax);
   StdI->Hund = (double *)malloc(sizeof(double) * nintrMax);
   for (ii = 0; ii < nintrMax; ii++) {
     StdI->HundIndx[ii] = (int *)malloc(sizeof(int) * 2);
   }
   StdI->NHund = 0;
   StdI->ExIndx = (int **)malloc(sizeof(int*) * nintrMax);
   StdI->Ex = (double *)malloc(sizeof(double) * nintrMax);
   for (ii = 0; ii < nintrMax; ii++) {
     StdI->ExIndx[ii] = (int *)malloc(sizeof(int) * 2);
   }
   StdI->NEx = 0;
   StdI->PLIndx = (int **)malloc(sizeof(int*) * nintrMax);
   StdI->PairLift = (double *)malloc(sizeof(double) * nintrMax);
   for (ii = 0; ii < nintrMax; ii++) {
     StdI->PLIndx[ii] = (int *)malloc(sizeof(int) * 2);
   }
   StdI->NPairLift = 0;
   StdI->PHIndx = (int **)malloc(sizeof(int*) * nintrMax);
   StdI->PairHopp = (double *)malloc(sizeof(double) * nintrMax);
   for (ii = 0; ii < nintrMax; ii++) {
     StdI->PHIndx[ii] = (int *)malloc(sizeof(int) * 2);
   }
   StdI->NPairHopp = 0;
 }/*void StdFace_MallocInteractions*/
StdFace_NotUsed_c()
void StdFace_NotUsed_c (char * valname, double complex val)
Stop HPhi if a variable (complex) not used is specified in the input file (!=NaN).
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] valname Name of the valiable
[in] val
Definition at line 509 of file StdFace_ModelUtil.c.
References StdFace_exit().
Referenced by StdFace_Chain(), StdFace_FCOrtho(), StdFace_Honeycomb(), StdFace_Kagome(), StdFace_Ladder(), StdFace_Orthorhombic(), StdFace_Pyrochlore(), StdFace_Tetragonal(), and StdFace_Triangular().
 {
   if (isnan(creal(val)) == 0) {
     fprintf(stdout, "\n Check !  %s is SPECIFIED but will NOT be USED. \n", valname);
     fprintf(stdout, "            Please COMMENT-OUT this line \n");
     fprintf(stdout, "            or check this input is REALLY APPROPRIATE for your purpose ! \n\n");
     StdFace_exit(-1);
   }
 }/*void StdFace_NotUsed_c*/
StdFace_NotUsed_d()
void StdFace_NotUsed_d (char * valname, double val)
Stop HPhi if a variable (real) not used is specified in the input file (!=NaN).
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] valname Name of the valiable
[in] val
Definition at line 492 of file StdFace_ModelUtil.c.
References StdFace_exit().
Referenced by StdFace_Chain(), StdFace_FCOrtho(), StdFace_Honeycomb(), StdFace_Kagome(), StdFace_Ladder(), StdFace_NotUsed_J(), StdFace_Orthorhombic(), StdFace_Pyrochlore(), StdFace_Tetragonal(), StdFace_Triangular(), and StdFace_Wannier90().
 {
   if (isnan(val) == 0) {
     fprintf(stdout, "\n Check !  %s is SPECIFIED but will NOT be USED. \n", valname);
     fprintf(stdout, "            Please COMMENT-OUT this line \n");
     fprintf(stdout, "            or check this input is REALLY APPROPRIATE for your purpose ! \n\n");
     StdFace_exit(-1);
   }
 }/*void StdFace_NotUsed_d*/
StdFace_NotUsed_i()
void StdFace_NotUsed_i (char * valname, int val)
Stop HPhi if a variable (integer) not used is specified in the input file (!=2147483647, the upper limt of Int).
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] valname Name of the valiable
[in] val
Definition at line 558 of file StdFace_ModelUtil.c.
References StdIntList::NaN_i, and StdFace_exit().
Referenced by CheckModPara(), StdFace_Chain(), StdFace_FCOrtho(), StdFace_Honeycomb(), StdFace_Kagome(), StdFace_Ladder(), StdFace_Orthorhombic(), StdFace_Pyrochlore(), StdFace_Tetragonal(), and StdFace_Triangular().
 {
   int NaN_i = 2147483647;
   if (val != NaN_i) {
     fprintf(stdout, "\n Check !  %s is SPECIFIED but will NOT be USED. \n", valname);
     fprintf(stdout, "            Please COMMENT-OUT this line \n");
     fprintf(stdout, "            or check this input is REALLY APPROPRIATE for your purpose ! \n\n");
     StdFace_exit(-1);
   }
 }/*void StdFace_NotUsed_i*/
StdFace_NotUsed_J()
void StdFace_NotUsed_J (char * valname, double JAll, double J[3][3])
Stop HPhi if variables (real) not used is specified in the input file (!=NaN).
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] valname Name of the valiable*/,
[in] JAll */,
[in] J
Definition at line 526 of file StdFace_ModelUtil.c.
References StdIntList::J, StdIntList::JAll, and StdFace_NotUsed_d().
Referenced by StdFace_Chain(), StdFace_FCOrtho(), StdFace_Honeycomb(), StdFace_Kagome(), StdFace_Ladder(), StdFace_Orthorhombic(), StdFace_Pyrochlore(), StdFace_Tetragonal(), and StdFace_Triangular().
 {
   int i1, i2;
   char Jname[3][3][10];
   sprintf(Jname[0][0], "%sx", valname);
   sprintf(Jname[0][1], "%sxy", valname);
   sprintf(Jname[0][2], "%sxz", valname);
   sprintf(Jname[1][0], "%syx", valname);
   sprintf(Jname[1][1], "%sy", valname);
   sprintf(Jname[1][2], "%syz", valname);
   sprintf(Jname[2][0], "%szx", valname);
   sprintf(Jname[2][1], "%szy", valname);
   sprintf(Jname[2][2], "%sz", valname);
   StdFace_NotUsed_d(valname, JAll);
   for (i1 = 0; i1 < 3; i1++) {
     for (i2 = 0; i2 < 3; i2++) {
       StdFace_NotUsed_d(Jname[i1][i2], J[i1][i2]);
     }/*for (j = 0; j < 3; j++)*/
   }/*for (i = 0; i < 3; i++)*/
 }/*void StdFace_NotUsed_J*/
StdFace_PrintGeometry()
void StdFace_PrintGeometry (struct StdIntList * StdI)
Print geometry of sites for the pos-process of correlation function.
Definition at line 1157 of file StdFace_ModelUtil.c.
References StdIntList::box, StdIntList::Cell, StdIntList::direct, StdIntList::model, StdIntList::NCell, StdIntList::NsiteUC, and StdIntList::phase.
Referenced by StdFace_Chain(), StdFace_FCOrtho(), StdFace_Honeycomb(), StdFace_Kagome(), StdFace_Ladder(), StdFace_Orthorhombic(), StdFace_Pyrochlore(), StdFace_Tetragonal(), StdFace_Triangular(), and StdFace_Wannier90().
{
   FILE *fp;
   int isite, iCell, ii;
   fp = fopen("geometry.dat", "w");
   for (ii = 0; ii < 3; ii++)
     fprintf(fp, "%25.15e %25.15e %25.15e\n",
       StdI->direct[ii][0], StdI->direct[ii][1], StdI->direct[ii][2]);
   fprintf(fp, "%25.15e %25.15e %25.15e\n",
     StdI->phase[0], StdI->phase[1], StdI->phase[2]);
   for (ii = 0; ii < 3; ii++)
     fprintf(fp, "%d %d %d\n",
       StdI->box[ii][0], StdI->box[ii][1], StdI->box[ii][2]);
   for (iCell = 0; iCell < StdI->NCell; iCell++) {
     for (isite = 0; isite < StdI->NsiteUC; isite++) {
       fprintf(fp, "%d %d %d %d\n",
         StdI->Cell[iCell][0] - StdI->Cell[0][0],
         StdI->Cell[iCell][1] - StdI->Cell[0][1],
         StdI->Cell[iCell][2] - StdI->Cell[0][2],
         isite);
     }/*for (isite = 0; isite < StdI->NsiteUC; isite++)*/
   }/* for (iCell = 0; iCell < StdI->NCell; iCell++)*/
   if (strcmp(StdI->model, "kondo") == 0) {
     for (iCell = 0; iCell < StdI->NCell; iCell++) {
       for (isite = 0; isite < StdI->NsiteUC; isite++) {
         fprintf(fp, "%d %d %d %d\n",
           StdI->Cell[iCell][0] - StdI->Cell[0][0],
           StdI->Cell[iCell][1] - StdI->Cell[0][1],
           StdI->Cell[iCell][2] - StdI->Cell[0][2],
           isite + StdI->NsiteUC);
       }/*for (isite = 0; isite < StdI->NsiteUC; isite++)*/
     }/* for (iCell = 0; iCell < StdI->NCell; iCell++)*/
   }
   fflush(fp);
   fclose(fp);
 }/*void StdFace_PrintGeometry()*/
StdFace_PrintVal_c()
void StdFace_PrintVal_c (char * valname, double complex * val, double complex val0)
Print a valiable (complex) read from the input file if it is not specified in the input file (=NaN), set the default value.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] valname Name of the valiable
[in,out] val Valiable to be set
[in] val0 The default value
Definition at line 455 of file StdFace_ModelUtil.c.
Referenced by StdFace_Chain(), StdFace_FCOrtho(), StdFace_Honeycomb(), StdFace_Kagome(), StdFace_Orthorhombic(), StdFace_Tetragonal(), and StdFace_Triangular().
 {
   if (isnan(creal(*val)) == 1) {
     *val = val0;
     fprintf(stdout, "  %15s = %-10.5f %-10.5f  ######  DEFAULT VALUE IS USED  ######\n", valname, creal(*val), cimag(*val));
   }
   else fprintf(stdout, "  %15s = %-10.5f %-10.5f\n", valname, creal(*val), cimag(*val));
 }/*void StdFace_PrintVal_c*/
StdFace_PrintVal_d()
void StdFace_PrintVal_d (char * valname, double * val, double val0)
Print a valiable (real) read from the input file if it is not specified in the input file (=NaN), set the default value.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] valname Name of the valiable
[in,out] val Valiable to be set
[in] val0 The default value
Definition at line 414 of file StdFace_ModelUtil.c.
Referenced by CheckModPara(), PrintExcitation(), StdFace_Chain(), StdFace_FCOrtho(), StdFace_Honeycomb(), StdFace_Kagome(), StdFace_Ladder(), StdFace_LargeValue(), StdFace_Orthorhombic(), StdFace_Pyrochlore(), StdFace_Tetragonal(), StdFace_Triangular(), StdFace_Wannier90(), and VectorPotential().
 {
   if (isnan(*val) == 1) {
     *val = val0;
     fprintf(stdout, "  %15s = %-10.5f  ######  DEFAULT VALUE IS USED  ######\n", valname, *val);
   }
   else fprintf(stdout, "  %15s = %-10.5f\n", valname, *val);
 }/*void StdFace_PrintVal_d*/
StdFace_PrintVal_dd()
void StdFace_PrintVal_dd (char * valname, double * val, double val0, double val1)
Print a valiable (real) read from the input file if it is not specified in the input file (=NaN), set the default value.
Author
Mitsuaki Kawamura (The University of Tokyo)
If the primary default value (val0) is not specified, use secondary default value
Parameters
[in] valname Name of the valiable
[in,out] val Valiable to be set
[in] val0 The primary default value, possible not to be specified
[in] val1 The secondary default value
Definition at line 432 of file StdFace_ModelUtil.c.
 {
   if (isnan(*val) == 1) {
     if (isnan(val0) == 1) *val = val1;
     else *val = val0;
     fprintf(stdout, "  %15s = %-10.5f  ######  DEFAULT VALUE IS USED  ######\n", valname, *val);
   }
   else fprintf(stdout, "  %15s = %-10.5f\n", valname, *val);
 }/*void StdFace_PrintVal_dd*/
StdFace_PrintVal_i()
void StdFace_PrintVal_i (char * valname, int * val, int val0)
Print a valiable (integer) read from the input file if it is not specified in the input file (=2147483647, the upper limt of Int) set the default value.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] valname Name of the valiable
[in,out] val Valiable to be set
[in] val0 The default value
Definition at line 473 of file StdFace_ModelUtil.c.
References StdIntList::NaN_i.
Referenced by CheckModPara(), StdFace_Chain(), StdFace_FCOrtho(), StdFace_Honeycomb(), StdFace_InitSite(), StdFace_Kagome(), StdFace_Ladder(), StdFace_main(), StdFace_Orthorhombic(), StdFace_Pyrochlore(), StdFace_Tetragonal(), StdFace_Triangular(), StdFace_Wannier90(), and VectorPotential().
 {
   int NaN_i = 2147483647;/*The upper limt of Int*/
   if (*val == NaN_i) {
     *val = val0;
     fprintf(stdout, "  %15s = %-10d  ######  DEFAULT VALUE IS USED  ######\n", valname, *val);
   }
   else fprintf(stdout, "  %15s = %-10d\n", valname, *val);
 }/*void StdFace_PrintVal_i*/
StdFace_PrintXSF()
void StdFace_PrintXSF (struct StdIntList * StdI)
Print lattice.xsf (XCrysDen format)
Definition at line 938 of file StdFace_ModelUtil.c.
References StdIntList::box, StdIntList::Cell, StdIntList::direct, StdIntList::NCell, StdIntList::NsiteUC, StdIntList::tau, and vec.
Referenced by StdFace_FCOrtho(), StdFace_Orthorhombic(), StdFace_Pyrochlore(), and StdFace_Wannier90().
{
   FILE *fp;
   int ii, jj, kk, isite, iCell;
   double vec[3];
   fp = fopen("lattice.xsf", "w");
   fprintf(fp, "CRYSTAL\n");
   fprintf(fp, "PRIMVEC\n");
   for (ii = 0; ii < 3; ii++) {
     for (jj = 0; jj < 3; jj++) {
       vec[jj] = 0.0;
       for (kk = 0; kk < 3; kk++)
         vec[jj] += (double)StdI->box[ii][kk] * StdI->direct[kk][jj];
     }
     fprintf(fp, "%15.5f %15.5f %15.5f\n", vec[0], vec[1], vec[2]);
   }
   fprintf(fp, "PRIMCOORD\n");
   fprintf(fp, "%d 1\n", StdI->NCell * StdI->NsiteUC);
   for (iCell = 0; iCell < StdI->NCell; iCell++) {
     for (isite = 0; isite < StdI->NsiteUC; isite++) {
       for (jj = 0; jj < 3; jj++) {
         vec[jj] = 0.0;
         for (kk = 0; kk < 3; kk++)
           vec[jj] += ((double)StdI->Cell[iCell][kk] + StdI->tau[isite][kk])
           * StdI->direct[kk][jj];
       }
       fprintf(fp, "H %15.5f %15.5f %15.5f\n", vec[0], vec[1], vec[2]);
     }
   }
   fflush(fp);
   fclose(fp);
 }/*void StdFace_PrintXSF*/
StdFace_RequiredVal_i()
void StdFace_RequiredVal_i (char * valname, int val)
Stop HPhi if a variable (integer) which must be specified is absent in the input file (=2147483647, the upper limt of Int).
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] valname Name of the valiable
[in] val
Definition at line 577 of file StdFace_ModelUtil.c.
References StdIntList::NaN_i, and StdFace_exit().
Referenced by CheckModPara(), StdFace_Chain(), and StdFace_Ladder().
 {
   int NaN_i = 2147483647;
   if (val == NaN_i){
     fprintf(stdout, "ERROR ! %s is NOT specified !\n", valname);
     StdFace_exit(-1);
   }
   else fprintf(stdout, "  %15s = %-3d\n", valname, val);
 }/*void StdFace_RequiredVal_i*/
StdFace_SetLabel()
void StdFace_SetLabel (struct StdIntList * StdI, FILE * fp, int iW, int iL, int diW, int diL, int isiteUC, int jsiteUC, int * isite, int * jsite, int connect, double complex * Cphase, double * dR)
Set Label in the gnuplot display (Only used in 2D system)
First print the reversed one
Then print the normal one, these are different when they cross boundary.
Parameters
[in,out] StdI
[in] fp File pointer to lattice.gp
[in] iW position of initial site
[in] iL position of initial site
[in] diW Translation from the initial site
[in] diL Translation from the initial site
[in] isiteUC Intrinsic site index of initial site
[in] jsiteUC Intrinsic site index of final site
[out] isite initial site
[out] jsite final site
[in] connect 1 for nearest neighbor, 2 for 2nd nearest
[out] Cphase Boundary phase, if it across boundary
[out] dR R_i - R_j
Definition at line 877 of file StdFace_ModelUtil.c.
References StdIntList::direct, StdFace_FindSite(), and StdIntList::tau.
Referenced by StdFace_Chain(), StdFace_Honeycomb(), StdFace_Kagome(), StdFace_Ladder(), StdFace_Tetragonal(), and StdFace_Triangular().
 {
   double xi, yi, xj, yj;
   StdFace_FindSite(StdI, iW, iL, 0, -diW, -diL, 0, jsiteUC, isiteUC, isite, jsite, Cphase, dR);
   xi = StdI->direct[0][0] * ((double)iW + StdI->tau[jsiteUC][0])
      + StdI->direct[1][0] * ((double)iL + StdI->tau[jsiteUC][1]);
   yi = StdI->direct[0][1] * ((double)iW + StdI->tau[jsiteUC][0])
      + StdI->direct[1][1] * ((double)iL + StdI->tau[jsiteUC][1]);
   xj = StdI->direct[0][0] * ((double)(iW - diW) + StdI->tau[isiteUC][0])
      + StdI->direct[1][0] * ((double)(iL - diL) + StdI->tau[isiteUC][1]);
   yj = StdI->direct[0][1] * ((double)(iW - diW) + StdI->tau[isiteUC][0])
      + StdI->direct[1][1] * ((double)(iL - diL) + StdI->tau[isiteUC][1]);
   if (*isite < 10)fprintf(fp, "set label \"%1d\" at %f, %f center front\n", *isite, xi, yi);
   else            fprintf(fp, "set label \"%2d\" at %f, %f center front\n", *isite, xi, yi);
   if (*jsite < 10)fprintf(fp, "set label \"%1d\" at %f, %f center front\n", *jsite, xj, yj);
   else            fprintf(fp, "set label \"%2d\" at %f, %f center front\n", *jsite, xj, yj);
   fprintf(fp, "set arrow from %f, %f to %f, %f nohead ls %d\n", xi, yi, xj, yj, connect);
   StdFace_FindSite(StdI, iW, iL, 0, diW, diL, 0, isiteUC, jsiteUC, isite, jsite, Cphase, dR);
   xi = StdI->direct[1][0] * ((double)iL + StdI->tau[isiteUC][1])
      + StdI->direct[0][0] * ((double)iW + StdI->tau[isiteUC][0]);
   yi = StdI->direct[1][1] * ((double)iL + StdI->tau[isiteUC][1])
      + StdI->direct[0][1] * ((double)iW + StdI->tau[isiteUC][0]);
   xj = StdI->direct[0][0] * ((double)(iW + diW) + StdI->tau[jsiteUC][0])
      + StdI->direct[1][0] * ((double)(iL + diL) + StdI->tau[jsiteUC][1]);
   yj = StdI->direct[0][1] * ((double)(iW + diW) + StdI->tau[jsiteUC][0])
      + StdI->direct[1][1] * ((double)(iL + diL) + StdI->tau[jsiteUC][1]);
   if (*isite < 10)fprintf(fp, "set label \"%1d\" at %f, %f center front\n", *isite, xi, yi);
   else            fprintf(fp, "set label \"%2d\" at %f, %f center front\n", *isite, xi, yi);
   if (*jsite < 10)fprintf(fp, "set label \"%1d\" at %f, %f center front\n", *jsite, xj, yj);
   else            fprintf(fp, "set label \"%2d\" at %f, %f center front\n", *jsite, xj, yj);
   fprintf(fp, "set arrow from %f, %f to %f, %f nohead ls %d\n", xi, yi, xj, yj, connect);
 }/*void StdFace_SetLabel*/
StdFace_trans()
void StdFace_trans (struct StdIntList * StdI, double complex trans0, int isite, int ispin, int jsite, int jspin)
Add transfer to the list set StdIntList::trans and StdIntList::transindx and increment StdIntList::ntrans.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in,out] StdI
[in] trans0 Hopping integral \(t, mu\), etc.
[in] isite \(i\) for \(c_{i \sigma}^\dagger\)
[in] ispin \(\sigma\) for \(c_{i \sigma}^\dagger\)
[in] jsite \(j\) for \(c_{j \sigma'}\)
[in] jspin \(\sigma'\) for \(c_{j \sigma'}\)
Definition at line 55 of file StdFace_ModelUtil.c.
References StdIntList::ntrans, StdIntList::trans, and StdIntList::transindx.
Referenced by StdFace_Hopping(), StdFace_HubbardLocal(), and StdFace_MagField().
 {
   StdI->trans[StdI->ntrans] = trans0;
   StdI->transindx[StdI->ntrans][0] = isite;
   StdI->transindx[StdI->ntrans][1] = ispin;
   StdI->transindx[StdI->ntrans][2] = jsite;
   StdI->transindx[StdI->ntrans][3] = jspin;
   StdI->ntrans = StdI->ntrans + 1;
 }/*void StdFace_trans*/