HΦ: bitcalc.c File Reference
bitcalc.c File Reference
File for giving functions of treating bits on the target of Hilbert space.
#include "bitcalc.h"
#include "wrapperMPI.h"
Functions
int GetSplitBit (const int Nsite, long unsigned int *irght, long unsigned int *ilft, long unsigned int *ihfbit)
function of getting right, left and half bits corresponding to a original Hilbert space. }
int GetSplitBitByModel (const int Nsite, const int iCalcModel, long unsigned int *irght, long unsigned int *ilft, long unsigned int *ihfbit)
function of splitting original bit into right and left spaces.
int GetSplitBitForGeneralSpin (const int Nsite, long unsigned int *ihfbit, const long int *SiteToBit)
function of getting right, left and half bits corresponding to a original space.
void SplitBit (const long unsigned int ibit, const long unsigned int irght, const long unsigned int ilft, const long unsigned int ihfbit, long unsigned int *isplited_Bit_right, long unsigned int *isplited_Bit_left)
function of splitting a original bit to right and left spaces
int GetOffComp (long unsigned int *_list_2_1, long unsigned int *_list_2_2, long unsigned int _ibit, const long unsigned int _irght, const long unsigned int _ilft, const long unsigned int _ihfbit, long unsigned int *_ioffComp)
function of getting off-diagonal component
int GetOffCompGeneralSpin (const long unsigned int org_ibit, const int org_isite, const int org_ispin, const int off_ispin, long unsigned int *_ioffComp, const long int *SiteToBit, const long unsigned int *Tpow)
function of getting off-diagonal component for general spin
int ConvertToList1GeneralSpin (const long unsigned int org_ibit, const long unsigned int ihlfbit, long unsigned int *_ilist1Comp)
function of converting component to list_1
void SgnBit_old (const long unsigned int org_bit, int *sgn)
function of getting fermion signs (for 32bit)
void SgnBit (const long unsigned int org_bit, int *sgn)
function of getting fermion sign (64 bit)
int BitCheck (const long unsigned int org_bit, const long unsigned int target_bit)
bit check function
int BitCheckGeneral (const long unsigned int org_bit, const unsigned int org_isite, const unsigned int target_ispin, const long int *SiteToBit, const long unsigned int *Tpow)
bit check function for general spin
int GetBitGeneral (const unsigned int isite, const long unsigned int org_bit, const long int *SiteToBit, const long unsigned int *Tpow)
get bit at a site for general spin
int GetLocal2Sz (const unsigned int isite, const long unsigned int org_bit, const long int *SiteToBit, const long unsigned int *Tpow)
get 2sz at a site for general spin
unsigned long int snoob (unsigned long int x)
"finding the next higher number after a given number that has the same number of 1-bits" This method is introduced in S.H. Warren, Hacker$B!G(Bs Delight, second ed., Addison-Wesley, ISBN: 0321842685, 2012.
int pop (unsigned int x)
calculating number of 1-bits in x (32 bit) This method is introduced in S.H. Warren, Hacker$B!G(Bs Delight, second ed., Addison-Wesley, ISBN: 0321842685, 2012.
Detailed Description
File for giving functions of treating bits on the target of Hilbert space.
Version
0.1, 0.2
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Definition in file bitcalc.c.
Function Documentation
BitCheck()
int BitCheck (const long unsigned int org_bit, const long unsigned int target_bit)
bit check function
Parameters
org_bit original bit to check
target_bit target bit to check
Return values
1
0
Version
0.1
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] org_bit
[in] target_bit
Definition at line 367 of file bitcalc.c.
 {
    return  (org_bit >> target_bit) &1;
    // (org_bit & (2^target_bit))/2^target_bit
 }
BitCheckGeneral()
int BitCheckGeneral (const long unsigned int org_bit, const unsigned int org_isite, const unsigned int target_ispin, const long int * SiteToBit, const long unsigned int * Tpow)
bit check function for general spin
Parameters
org_bit original bit to check
org_isite site index (org_isite >= 1)
target_ispin target spin to check
SiteToBit List for getting bit at a site
Tpow List for getting total bit at a site before
Return values
0 bit does not exists
1 bit exists
Version
0.2
Author
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] org_bit
[in] org_isite
[in] target_ispin
[in] SiteToBit
[in] Tpow
Definition at line 393 of file bitcalc.c.
References FALSE, GetBitGeneral(), and TRUE.
Referenced by expec_cisajs_SpinGCGeneral(), expec_cisajs_SpinGeneral(), expec_cisajscktalt_SpinGCGeneral(), expec_cisajscktalt_SpinGeneral(), GetOffCompGeneralSpin(), GetPairExcitedStateGeneralSpin(), GetPairExcitedStateGeneralSpinGC(), mltplyGeneralSpinGC(), SetDiagonalChemi(), SetDiagonalInterAll(), SetDiagonalTEChemi(), SetDiagonalTEInterAll(), SetDiagonalTETransfer(), X_child_CisAisCjuAju_GeneralSpin_MPIdouble(), X_child_CisAisCjuAju_GeneralSpin_MPIsingle(), X_GC_child_AisCis_GeneralSpin_MPIdouble(), X_GC_child_CisAis_GeneralSpin_MPIdouble(), X_GC_child_CisAisCjuAju_GeneralSpin_MPIdouble(), X_GC_child_CisAisCjuAju_GeneralSpin_MPIsingle(), X_GC_child_CisAisCjuAjv_GeneralSpin_MPIdouble(), X_GC_child_CisAisCjuAjv_GeneralSpin_MPIsingle(), X_GC_child_CisAitCjuAju_GeneralSpin_MPIdouble(), and X_GC_child_CisAitCjuAju_GeneralSpin_MPIsingle().
 {
   if(GetBitGeneral(org_isite, org_bit, SiteToBit, Tpow) !=target_ispin){
     return FALSE;
   }
   return TRUE;
 }
ConvertToList1GeneralSpin()
int ConvertToList1GeneralSpin (const long unsigned int org_ibit, const long unsigned int ihlfbit, long unsigned int * _ilist1Comp)
function of converting component to list_1
Parameters
org_ibit a original bit
ihlfbit a split bit for general spin
_ilist1Comp a component converted to list_1
Version
0.2
Author
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] org_ibit
[in] ihlfbit
[out] _ilist1Comp
Definition at line 285 of file bitcalc.c.
References FALSE, list_2_1, list_2_2, and TRUE.
Referenced by expec_cisajscktalt_SpinGeneral(), GetPairExcitedStateGeneralSpin(), makeHam(), mltplyGeneralSpin(), totalspin_Spin(), X_child_CisAit_GeneralSpin_MPIdouble(), X_child_CisAitCjuAjv_GeneralSpin_MPIdouble(), and X_child_CisAitCjuAjv_GeneralSpin_MPIsingle().
 {
   long unsigned int ia, ib;
   long unsigned int tmp_list;
   ia=org_ibit%ihlfbit;
   ib=org_ibit/ihlfbit;
   if(list_2_1[ia]*list_2_2[ib]==0){
     *_ilist1Comp=0;
     return FALSE;
   }
   *_ilist1Comp = list_2_1[ia] + list_2_2[ib] - 2;
   return TRUE;
 }
GetBitGeneral()
int GetBitGeneral (const unsigned int isite, const long unsigned int org_bit, const long int * SiteToBit, const long unsigned int * Tpow)
get bit at a site for general spin
Parameters
isite site index (isite >= 1)
org_bit original bit to check
SiteToBit List for getting bit at a site
Tpow List for getting total bit at a site before
Returns
bit at a site
Version
0.2
Author
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] isite
[in] org_bit
[in] SiteToBit
[in] Tpow
Definition at line 422 of file bitcalc.c.
Referenced by BitCheckGeneral(), GetLocal2Sz(), totalspin_Spin(), and totalspin_SpinGC().
 {
   long unsigned int tmp_bit=(org_bit/Tpow[isite-1])%SiteToBit[isite-1] ;
   return (tmp_bit);
 }
GetLocal2Sz()
int GetLocal2Sz (const unsigned int isite, const long unsigned int org_bit, const long int * SiteToBit, const long unsigned int * Tpow)
get 2sz at a site for general spin
Parameters
isite site index (isite >= 1)
org_bit original bit to check
SiteToBit List for getting bit at a site
Tpow List for getting total bit at a site before
Returns
2sz at isite
Version
0.2
Author
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] isite
[in] org_bit
[in] SiteToBit
[in] Tpow
Definition at line 449 of file bitcalc.c.
References GetBitGeneral().
Referenced by check(), expec_cisajscktalt_SpinGeneral(), expec_energy_flct_GeneralSpin(), expec_energy_flct_GeneralSpinGC(), sz(), totalspin_Spin(), totalspin_SpinGC(), and totalSz_SpinGC().
 {
   int TwiceSz=0;
   int bitAtSite=0;
   //get bit
   bitAtSite=GetBitGeneral(isite, org_bit, SiteToBit, Tpow);
   TwiceSz=-(SiteToBit[isite-1]-1)+2*bitAtSite; //-2S^{total}_i+2Sz_i
   return TwiceSz;
 }
GetOffComp()
int GetOffComp (long unsigned int * _list_2_1, long unsigned int * _list_2_2, long unsigned int _ibit, const long unsigned int _irght, const long unsigned int _ilft, const long unsigned int _ihfbit, long unsigned int * _ioffComp)
function of getting off-diagonal component
Parameters
_list_2_1 list to right space
_list_2_2 list to left space
_ibit a original bit
_irght a bit to split original space into right space
_ilft a bit to split original space into left space
_ihfbit a half bit to split original space
_ioffComp an off diagonal component
Version
0.1
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] _list_2_1
[in] _list_2_2
[in] _ibit
[in] _irght
[in] _ilft
[in] _ihfbit
[out] _ioffComp
Definition at line 195 of file bitcalc.c.
References FALSE, SplitBit(), and TRUE.
Referenced by child_exchange_element(), child_exchange_spin_element(), child_pairhopp_element(), CisAjt(), totalspin_Hubbard(), totalspin_Spin(), X_Ajt(), X_Ajt_MPI(), X_child_CisAit_spin_MPIdouble(), X_child_CisAjt_MPIdouble(), X_child_CisAjt_MPIsingle(), X_child_CisAjtCkuAku_Hubbard_MPI(), X_child_CisAjtCkuAlv_Hubbard_MPI(), X_child_exchange_spin_element(), X_child_general_hopp_MPIdouble(), X_child_general_hopp_MPIsingle(), X_child_general_int_spin_MPIdouble(), X_child_general_int_spin_MPIsingle(), X_child_general_int_spin_TotalS_MPIdouble(), X_Cis(), X_Cis_MPI(), X_CisAjt(), and X_Spin_CisAit().
 {
   long unsigned int ia, ib;
   SplitBit(_ibit, _irght, _ilft, _ihfbit, &ia, &ib);
 /*
   *_ioffComp =_list_2_1[ia];
   *_ioffComp+=_list_2_2[ib];
 */
   //if(myrank==1)
   //printf( "DEGBUG:_ibit=%ld, _list_2_1=%ld, _list_2_2=%ld\n", _ibit, _list_2_1[ia], _list_2_2[ib]);
   if(_list_2_1[ia]*_list_2_2[ib]==0){
     *_ioffComp=0;
     return FALSE;
   }
   *_ioffComp =_list_2_1[ia]-1;
   *_ioffComp+=_list_2_2[ib]-1;
   return TRUE;
 }
GetOffCompGeneralSpin()
int GetOffCompGeneralSpin (const long unsigned int org_ibit, const int org_isite, const int org_ispin, const int off_ispin, long unsigned int * _ioffComp, const long int * SiteToBit, const long unsigned int * Tpow)
function of getting off-diagonal component for general spin
Parameters
org_ibit a original bit
org_isite a target site
org_ispin a target spin to delete.
off_ispin a target spin to create.
_ioffComp a generated bit
SiteToBit List for getting bit at a site
Tpow List for getting total bit at a site before
Return values
FALSE off-diagonal component does not exist
TRUE off-diagonal component exists
Version
0.2
Author
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] org_ibit
[in] org_isite
[in] org_ispin
[in] off_ispin
[out] _ioffComp
[in] SiteToBit
[in] Tpow
Definition at line 243 of file bitcalc.c.
References BitCheckGeneral(), FALSE, and TRUE.
Referenced by expec_cisajs_SpinGCGeneral(), expec_cisajscktalt_SpinGCGeneral(), expec_cisajscktalt_SpinGeneral(), GetPairExcitedStateGeneralSpin(), GetPairExcitedStateGeneralSpinGC(), makeHam(), mltplyGeneralSpin(), mltplyGeneralSpinGC(), totalspin_Spin(), totalspin_SpinGC(), X_child_CisAit_GeneralSpin_MPIdouble(), X_child_CisAitCjuAjv_GeneralSpin_MPIdouble(), X_child_CisAitCjuAjv_GeneralSpin_MPIsingle(), X_GC_child_CisAisCjuAjv_GeneralSpin_MPIdouble(), X_GC_child_CisAisCjuAjv_GeneralSpin_MPIsingle(), X_GC_child_CisAit_GeneralSpin_MPIdouble(), X_GC_child_CisAitCjuAju_GeneralSpin_MPIdouble(), X_GC_child_CisAitCjuAju_GeneralSpin_MPIsingle(), X_GC_child_CisAitCjuAjv_GeneralSpin_MPIdouble(), and X_GC_child_CisAitCjuAjv_GeneralSpin_MPIsingle().
 {
   if(off_ispin>SiteToBit[org_isite-1]-1 ||
      off_ispin<0                      ||
      org_ispin>SiteToBit[org_isite-1]-1 ||
      org_ispin <0){
     *_ioffComp=0;
     return FALSE;
   }
   if(BitCheckGeneral(org_ibit, org_isite, org_ispin, SiteToBit, Tpow) == FALSE){
     *_ioffComp=0;
     return FALSE;
   }
   //delete org_ispin and create off_ispin
   long int tmp_off=0;
   tmp_off=(long int)(off_ispin-org_ispin);
   tmp_off *=Tpow[org_isite-1];
   tmp_off +=org_ibit;
   *_ioffComp =tmp_off;
   return TRUE;
 }
GetSplitBit()
int GetSplitBit (const int Nsite, long unsigned int * irght, long unsigned int * ilft, long unsigned int * ihfbit)
function of getting right, left and half bits corresponding to a original Hilbert space. }
Parameters
Nsite a total number of sites
irght a bit to split original Hilbert space into right space \(2^{(Ns+2)/2}-1\)
ilft a bit to split original Hilbert space into left space
ihfbit a half bit to split original Hilbert space \(2^{(Ns+2)/2}\)
Version
0.1
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Returns
Parameters
[in] Nsite
[out] irght
[out] ilft
[out] ihfbit
Definition at line 45 of file bitcalc.c.
References cErrSiteNumber.
Referenced by GetSplitBitByModel().
  {
   if(Nsite<1){
     fprintf(stderr, "%s", cErrSiteNumber);
     return -1;
   }
   *ihfbit=1;
   *ihfbit=(*ihfbit<<(unsigned long int)((Nsite+1)/2));
   *irght = *ihfbit-1;
   *ilft=1;
   *ilft = (*ilft<<(unsigned long int)Nsite)-1;
   *ilft= *ilft ^ *irght;
   return 0;
 }
GetSplitBitByModel()
int GetSplitBitByModel (const int Nsite, const int iCalcModel, long unsigned int * irght, long unsigned int * ilft, long unsigned int * ihfbit)
function of splitting original bit into right and left spaces.
Parameters
Nsite a total number of sites
iCalcModel Calc model defined in CalcMode file
irght a bit to split original space into right space
ilft a bit to split original space into left space
ihfbit a half bit to split original space
Version
0.1
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Returns
Parameters
[in] Nsite
[in] iCalcModel
[out] irght
[out] ilft
[out] ihfbit
Definition at line 78 of file bitcalc.c.
References cErrNoModel, and GetSplitBit().
Referenced by expec_cisajs(), expec_cisajscktaltdc(), expec_energy_flct(), GetPairExcitedState(), GetPairExcitedStateHubbard(), makeHam(), mltply(), sz(), totalspin_Hubbard(), and totalspin_Spin().
 {
   int tmpNsite=Nsite;
   switch(iCalcModel){
   case HubbardGC:
   case KondoGC:
   case HubbardNConserved:
   case Hubbard:
   case Kondo:
     tmpNsite *= 2;
     break;
   case Spin:
   case SpinGC:
     break;
   default:
     fprintf(stderr, cErrNoModel, iCalcModel);
     return -1;
   }
   if(GetSplitBit(tmpNsite, irght, ilft, ihfbit)!=0){
     return -1;
   }
   return 0;
 }
GetSplitBitForGeneralSpin()
int GetSplitBitForGeneralSpin (const int Nsite, long unsigned int * ihfbit, const long int * SiteToBit)
function of getting right, left and half bits corresponding to a original space.
Parameters
Nsite a total number of sites
ihfbit a bit to split original space
Return values
0 normally finished
-1 unnormally finished
Version
0.2
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] Nsite
[out] ihfbit
[in] SiteToBit
Definition at line 124 of file bitcalc.c.
References cErrSiteNumber.
Referenced by check(), GetPairExcitedState(), and mltply().
  {
   int isite=0;
   long int isqrtMaxDim=1;
   long int tmpbit=1;
   if(Nsite<1){
     fprintf(stderr, "%s", cErrSiteNumber);
     return -1;
   }
   for(isite=1; isite<=Nsite ; isite++){
     isqrtMaxDim *= SiteToBit[isite-1];
   }
   isqrtMaxDim =(long int)sqrt(isqrtMaxDim);
   for(isite=1; isite<=Nsite ; isite++){
     tmpbit *= SiteToBit[isite-1];
     if(tmpbit >= isqrtMaxDim) break;
   }
   *ihfbit=tmpbit;
   return 0;
 }
pop()
int pop (unsigned int x)
calculating number of 1-bits in x (32 bit) This method is introduced in S.H. Warren, Hacker$B!G(Bs Delight, second ed., Addison-Wesley, ISBN: 0321842685, 2012.
Parameters
x
Version
2.0
Author
Takahiro Misawa (The University of Tokyo)
Definition at line 492 of file bitcalc.c.
Referenced by expec_energy_flct_HalfSpin(), expec_energy_flct_HalfSpinGC(), expec_energy_flct_Hubbard(), and expec_energy_flct_HubbardGC().
{
   x = x - ((x>>1) & 0x55555555);
   x = (x & 0x33333333)+ ((x>>2)& 0x33333333);
   x = (x+(x>>4)) & 0x0F0F0F0F;
   x = x+ (x>>8);
   x = x+ (x>>16);
   return  x & 0x0000003F;
 }
SgnBit()
void SgnBit (const long unsigned int org_bit, int * sgn)
function of getting fermion sign (64 bit)
Parameters
org_bit an original bit
sgn fermion sign
Version
0.1
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] org_bit
[out] sgn
Definition at line 339 of file bitcalc.c.
Referenced by CisAjt(), GC_Ajt(), GC_Cis(), GC_CisAjt(), X_Ajt(), X_Ajt_MPI(), X_child_CisAjt_MPIdouble(), X_child_CisAjt_MPIsingle(), X_child_CisAjtCkuAku_Hubbard_MPI(), X_child_general_hopp_MPIdouble(), X_child_general_hopp_MPIsingle(), X_Cis(), X_Cis_MPI(), X_GC_Ajt_MPI(), X_GC_child_CisAjtCkuAku_Hubbard_MPI(), X_GC_child_general_hopp_MPIdouble(), X_GC_child_general_hopp_MPIsingle(), X_GC_Cis_MPI(), and X_GC_CisAjt().
 {
    long unsigned int bit;
    bit =  org_bit^(org_bit>>1);
    bit =  bit^(bit>>2);
    bit =  bit^(bit>>4);
    bit =  bit^(bit>>8);
    bit =  bit^(bit>>16);
    bit =  bit^(bit>>32);
    *sgn    = 1-2*(bit & 1); // sgn = pm 1
 }
SgnBit_old()
void SgnBit_old (const long unsigned int org_bit, int * sgn)
function of getting fermion signs (for 32bit)
Parameters
org_bit an original bit
sgn fermion sign
Version
0.1
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] org_bit
[out] sgn
Definition at line 313 of file bitcalc.c.
 {
    long unsigned int bit;
    bit     = org_bit^(org_bit>>1);
    bit     = (bit^(bit>>2) ) & 0x11111111;
    bit     = bit*0x11111111;
    *sgn    = 1-2*((bit>>28) & 1); // sgn = pm 1
 }
snoob()
unsigned long int snoob (unsigned long int x)
"finding the next higher number after a given number that has the same number of 1-bits" This method is introduced in S.H. Warren, Hacker$B!G(Bs Delight, second ed., Addison-Wesley, ISBN: 0321842685, 2012.
Parameters
x
Version
2.0
Author
Takahiro Misawa (The University of Tokyo)
Definition at line 474 of file bitcalc.c.
Referenced by child_omp_sz_hacker(), child_omp_sz_Kondo_hacker(), child_omp_sz_spin_hacker(), and sz().
{
   unsigned long int smallest, ripple, ones;
   smallest = x &(-x);
   ripple   = x+ smallest;
   ones     = x ^ ripple;
   ones     = (ones>>2)/smallest;
   return   ripple|ones;
 }
SplitBit()
void SplitBit (const long unsigned int ibit, const long unsigned int irght, const long unsigned int ilft, const long unsigned int ihfbit, long unsigned int * isplited_Bit_right, long unsigned int * isplited_Bit_left)
function of splitting a original bit to right and left spaces
Parameters
ibit a original bit
irght a bit to split original space into right space
ilft a bit to split original space into left space
ihfbit a half bit to split original space
isplited_Bit_right a splitted bit reflected on right space
isplited_Bit_left a splitted bit reflected on left space
Version
0.1
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] ibit
[in] irght
[in] ilft
[in] ihfbit
[out] isplited_Bit_right
[out] isplited_Bit_left
Definition at line 166 of file bitcalc.c.
Referenced by GetOffComp().
 {
   *isplited_Bit_right=ibit & irght;
   *isplited_Bit_left=ibit & ilft;
   *isplited_Bit_left=*isplited_Bit_left/ihfbit;
 }