HΦ: log.c File Reference
log.c File Reference
File for defining functions to write log messages.
#include <time.h>
#include "Common.h"
#include "log.h"
#include "FileIO.h"
Functions
int TimeKeeper (struct BindStruct *X, const char *cFileName, const char *cTimeKeeper_Message, const char *cWriteType)
Functions for writing a time log.
int TimeKeeperWithStep (struct BindStruct *X, const char *cFileName, const char *cTimeKeeper_Message, const char *cWriteType, const int istep)
Functions for writing a time log.
int TimeKeeperWithRandAndStep (struct BindStruct *X, const char *cFileName, const char *cTimeKeeper_Message, const char *cWriteType, const int irand, const int istep)
Functions for writing a time log.
Detailed Description
File for defining functions to write log messages.
Definition in file log.c.
Function Documentation
int TimeKeeper (struct BindStruct * X, const char * cFileName, const char * cTimeKeeper_Message, const char * cWriteType)
Functions for writing a time log.
Parameters
[in] X Define List for parameters.
[in] cFileName character for a file name of writing.
[in] cTimeKeeper_Message character for a sentence writing in a file.
[in] cWriteType character for determining writing option for fopen.
Return values
0 normally finished.
-1 unnormally finished.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Definition at line 42 of file log.c.
References DefineList::CDataFileHead, childfopenMPI(), D_FileNameMax, BindStruct::Def, and TimeKeeperWithStep().
Referenced by CalcByLanczos(), CalcByLOBPCG(), CalcByTEM(), CalcSpectrum(), CalcSpectrumByBiCG(), CalcSpectrumByTPQ(), CG_EigenVector(), diagonalcalc(), expec_cisajs(), expec_cisajscktaltdc(), expec_energy_flct(), Lanczos_EigenValue(), Lanczos_EigenVector(), LOBPCG_Main(), main(), OutputLanczosVector(), Read_sz(), ReadInitialVector(), and sz().
 {
   FILE *fp;
   char sdt[D_FileNameMax];
   struct tm *area;
   time_t tx;
   sprintf(sdt, cFileName, X->Def.CDataFileHead);
   tx   = time(NULL);
   area = localtime(&tx);
   if(childfopenMPI(sdt, cWriteType, &fp)!=0){
     return -1;
   }
   fprintf(fp, cTimeKeeper_Message, asctime(area));
   fclose(fp);
   return 0;
 }
int TimeKeeperWithRandAndStep (struct BindStruct * X, const char * cFileName, const char * cTimeKeeper_Message, const char * cWriteType, const int irand, const int istep)
Functions for writing a time log.
Parameters
[in] X Define List for parameters.
[in] cFileName character for a file name of writing.
[in] cTimeKeeper_Message character for a sentence writing in a file.
[in] cWriteType character for determining writing option for fopen.
[in] irand int for writing a number of seed of rand.
[in] istep int for writing steps of progress for a function under calculating.
Return values
0 normally finished.
-1 unnormally finished.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Definition at line 117 of file log.c.
References DefineList::CDataFileHead, childfopenMPI(), D_FileNameMax, and BindStruct::Def.
Referenced by CalcByTPQ(), expec_cisajs(), expec_cisajscktaltdc(), and TimeKeeperWithStep().
   {
   FILE *fp;
   char sdt[D_FileNameMax];
   struct tm *area;
   time_t tx;
   sprintf(sdt, cFileName, X->Def.CDataFileHead);
   tx   = time(NULL);
   area = localtime(&tx);
   if(childfopenMPI(sdt, cWriteType, &fp)!=0){
     return -1;
   }
   fprintf(fp, cTimeKeeper_Message, irand, istep, asctime(area));
   fclose(fp);
   return 0;
 }
int TimeKeeperWithStep (struct BindStruct * X, const char * cFileName, const char * cTimeKeeper_Message, const char * cWriteType, const int istep)
Functions for writing a time log.
Parameters
[in] X Define List for parameters.
[in] cFileName character for a file name of writing.
[in] cTimeKeeper_Message character for a sentence writing in a file.
[in] cWriteType character for determining writing option for fopen.
[in] istep int for writing steps of progress for a function under calculating.
Return values
0 normally finished.
-1 unnormally finished.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Definition at line 78 of file log.c.
References DefineList::CDataFileHead, childfopenMPI(), D_FileNameMax, BindStruct::Def, and TimeKeeperWithRandAndStep().
Referenced by CalcByTEM(), expec_cisajs(), expec_cisajscktaltdc(), expec_energy_flct(), Lanczos_EigenValue(), Lanczos_GetTridiagonalMatrixComponents(), LOBPCG_Main(), and TimeKeeper().
 {
   FILE *fp;
   char sdt[D_FileNameMax];
   struct tm *area;
   time_t tx;
   sprintf(sdt, cFileName, X->Def.CDataFileHead);
   tx   = time(NULL);
   area = localtime(&tx);
   if(childfopenMPI(sdt, cWriteType, &fp)!=0){
     return -1;
   }
   fprintf(fp, cTimeKeeper_Message, istep, asctime(area));
   fclose(fp);
   return 0;
 }