HΦ: mltplyHubbardCore.c File Reference
mltplyHubbardCore.c File Reference
Functions for Hubbard hamiltonian (Core)
#include <bitcalc.h>
#include "xsetmem.h"
#include "wrapperMPI.h"
#include "mltplyCommon.h"
#include "mltplyHubbardCore.h"
Functions
int child_general_hopp_GetInfo (struct BindStruct *X, unsigned long int isite1, unsigned long int isite2, unsigned long int sigma1, unsigned long int sigma2)
Compute mask for bit operation of hopping term.
int child_general_int_GetInfo (int iInterAll, struct BindStruct *X, long unsigned int isite1, long unsigned int isite2, long unsigned int isite3, long unsigned int isite4, long unsigned int sigma1, long unsigned int sigma2, long unsigned int sigma3, long unsigned int sigma4, double complex tmp_V)
Compute mask for bit operation of general interaction term.
int child_pairhopp_GetInfo (int iPairHopp, struct BindStruct *X)
Compute mask for bit operation of pairhop term.
int child_exchange_GetInfo (int iExchange, struct BindStruct *X)
Compute mask for bit operation of exchange term.
double complex GC_CisAis (long unsigned int j, double complex *tmp_v0, double complex *tmp_v1, struct BindStruct *X, long unsigned int is1_spin, double complex tmp_trans)
Operation of \(t c_{i\sigma}^\dagger c_{i\sigma}\) (Grandcanonical)
double complex GC_AisCis (long unsigned int j, double complex *tmp_v0, double complex *tmp_v1, struct BindStruct *X, long unsigned int is1_spin, double complex tmp_trans)
Operation of \(t c_{i\sigma} c_{i\sigma}^\dagger\) (Grandcanonical)
int X_CisAis (long unsigned int list_1_j, struct BindStruct *X, long unsigned int is1_spin)
\(c_{is}\\dagger c_{is}\) term in Hubbard (canonical)
double complex CisAjt (long unsigned int j, double complex *tmp_v0, double complex *tmp_v1, struct BindStruct *X, long unsigned int is1_spin, long unsigned int is2_spin, long unsigned int sum_spin, long unsigned int diff_spin, double complex tmp_V)
\(c_{is}^\dagger c_{jt}\) term for canonical Hubbard
double complex GC_CisAjt (long unsigned int j, double complex *tmp_v0, double complex *tmp_v1, struct BindStruct *X, long unsigned int is1_spin, long unsigned int is2_spin, long unsigned int sum_spin, long unsigned int diff_spin, double complex tmp_V, long unsigned int *tmp_off)
\(c_{is}^\dagger c_{jt}\) term for grandcanonical Hubbard
int X_CisAjt (long unsigned int list_1_j, struct BindStruct *X, long unsigned int is1_spin, long unsigned int is2_spin, long unsigned int sum_spin, long unsigned int diff_spin, long unsigned int *tmp_off)
Compute index of wavefunction of final state.
int X_GC_CisAjt (long unsigned int list_1_j, struct BindStruct *X, long unsigned int is1_spin, long unsigned int is2_spin, long unsigned int sum_spin, long unsigned int diff_spin, long unsigned int *tmp_off)
Compute index of wavefunction of final state.
double complex child_exchange_element (long unsigned int j, double complex *tmp_v0, double complex *tmp_v1, struct BindStruct *X, long unsigned int *tmp_off)
Compute exchange term of canonical-Hubbard.
double complex child_pairhopp_element (long unsigned int j, double complex *tmp_v0, double complex *tmp_v1, struct BindStruct *X, long unsigned int *tmp_off)
Compute pairhopp term of canonical Hubbard system.
double complex GC_child_exchange_element (long unsigned int j, double complex *tmp_v0, double complex *tmp_v1, struct BindStruct *X, long unsigned int *tmp_off)
Compute exchange term of grandcanonical Hubbard system.
double complex GC_child_pairhopp_element (long unsigned int j, double complex *tmp_v0, double complex *tmp_v1, struct BindStruct *X, long unsigned int *tmp_off)
Compute pairhopp term of grandcanonical Hubbard system.
double complex child_CisAisCisAis_element (long unsigned int j, long unsigned int isite1, long unsigned int isite3, double complex tmp_V, double complex *tmp_v0, double complex *tmp_v1, struct BindStruct *X, long unsigned int *tmp_off)
Compute \(c_{is}^\dagger c_{is} c_{is}^\dagger c_{is}\) term of canonical Hubbard system.
double complex child_CisAisCjtAku_element (long unsigned int j, long unsigned int isite1, long unsigned int isite3, long unsigned int isite4, long unsigned int Bsum, long unsigned int Bdiff, double complex tmp_V, double complex *tmp_v0, double complex *tmp_v1, struct BindStruct *X, long unsigned int *tmp_off)
Compute \(c_{is}^\dagger c_{is} c_{jt}^\dagger c_{ku}\) term of canonical Hubbard system.
double complex child_CisAjtCkuAku_element (long unsigned int j, long unsigned int isite1, long unsigned int isite2, long unsigned int isite3, long unsigned int Asum, long unsigned int Adiff, double complex tmp_V, double complex *tmp_v0, double complex *tmp_v1, struct BindStruct *X, long unsigned int *tmp_off)
Compute \(c_{is}^\dagger c_{jt} c_{ku}^\dagger c_{ku}\) term of canonical Hubbard system.
double complex child_CisAjtCkuAlv_element (long unsigned int j, long unsigned int isite1, long unsigned int isite2, long unsigned int isite3, long unsigned int isite4, long unsigned int Asum, long unsigned int Adiff, long unsigned int Bsum, long unsigned int Bdiff, double complex tmp_V, double complex *tmp_v0, double complex *tmp_v1, struct BindStruct *X, long unsigned int *tmp_off_2)
Compute \(c_{is}^\dagger c_{jt} c_{ku}^\dagger c_{lv}\) term of canonical Hubbard system.
double complex GC_child_CisAisCisAis_element (long unsigned int j, long unsigned int isite1, long unsigned int isite3, double complex tmp_V, double complex *tmp_v0, double complex *tmp_v1, struct BindStruct *X, long unsigned int *tmp_off)
Compute \(c_{is}^\dagger c_{is} c_{is}^\dagger c_{is}\) term of grandcanonical Hubbard system.
double complex GC_child_CisAisCjtAku_element (long unsigned int j, long unsigned int isite1, long unsigned int isite3, long unsigned int isite4, long unsigned int Bsum, long unsigned int Bdiff, double complex tmp_V, double complex *tmp_v0, double complex *tmp_v1, struct BindStruct *X, long unsigned int *tmp_off)
Compute \(c_{is}^\dagger c_{is} c_{jt}^\dagger c_{ku}\) term of grandcanonical Hubbard system.
double complex GC_child_CisAjtCkuAku_element (long unsigned int j, long unsigned int isite1, long unsigned int isite2, long unsigned int isite3, long unsigned int Asum, long unsigned int Adiff, double complex tmp_V, double complex *tmp_v0, double complex *tmp_v1, struct BindStruct *X, long unsigned int *tmp_off)
Compute \(c_{is}^\dagger c_{jt} c_{ku}^\dagger c_{ku}\) term of grandcanonical Hubbard system.
double complex GC_child_CisAjtCkuAlv_element (long unsigned int j, long unsigned int isite1, long unsigned int isite2, long unsigned int isite3, long unsigned int isite4, long unsigned int Asum, long unsigned int Adiff, long unsigned int Bsum, long unsigned int Bdiff, double complex tmp_V, double complex *tmp_v0, double complex *tmp_v1, struct BindStruct *X, long unsigned int *tmp_off_2)
Compute \(c_{is}^\dagger c_{jt} c_{ku}^\dagger c_{lv}\) term of grandcanonical Hubbard system.
double complex GC_Cis (long unsigned int j, double complex *tmp_v0, double complex *tmp_v1, long unsigned int is1_spin, double complex tmp_V, long unsigned int *tmp_off)
Compute \(c_{is}^\dagger\) term of grandcanonical Hubbard system.
double complex GC_Ajt (long unsigned int j, double complex *tmp_v0, double complex *tmp_v1, long unsigned int is1_spin, double complex tmp_V, long unsigned int *tmp_off)
Compute \(c_{jt}\) term of grandcanonical Hubbard system.
int X_Cis (long unsigned int j, long unsigned int is1_spin, long unsigned int *tmp_off, long unsigned int *list_1_org, long unsigned int *list_2_1_target, long unsigned int *list_2_2_target, long unsigned int _irght, long unsigned int _ilft, long unsigned int _ihfbit)
Compute index of final wavefunction associatesd to \(c_{is}^\dagger\) term of canonical Hubbard system.
double complex X_Ajt (long unsigned int j, long unsigned int is1_spin, long unsigned int *tmp_off, long unsigned int *list_1_org, long unsigned int *list_2_1_target, long unsigned int *list_2_2_target, long unsigned int _irght, long unsigned int _ilft, long unsigned int _ihfbit)
Compute index of final wavefunction associatesd to \(c_{jt}\) term of canonical Hubbard system.
Detailed Description
Functions for Hubbard hamiltonian (Core)
Definition in file mltplyHubbardCore.c.
Function Documentation
child_CisAisCisAis_element()
double complex child_CisAisCisAis_element (long unsigned int j, long unsigned int isite1, long unsigned int isite3, double complex tmp_V, double complex * tmp_v0, double complex * tmp_v1, struct BindStruct * X, long unsigned int * tmp_off)
Compute \(c_{is}^\dagger c_{is} c_{is}^\dagger c_{is}\) term of canonical Hubbard system.
Returns
Fragment of \(\langle v_1 | H_{\rm this} | v_1 \rangle\)
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] isite1 Site 1
[in] isite3 Site 3
[in] tmp_V Coupling constant
[in,out] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[in,out] X
[out] tmp_off Index of final wavefunction
Definition at line 689 of file mltplyHubbardCore.c.
References BindStruct::Large, list_1, LargeList::mode, and X_CisAis().
Referenced by child_general_int(), expec_cisajscktalt_Hubbard(), and makeHam().
   {
   int tmp_sgn;
   double complex dmv;
   double complex dam_pr = 0 + 0 * I;
   tmp_sgn = X_CisAis(list_1[j], X, isite3);
   tmp_sgn *= X_CisAis(list_1[j], X, isite1);
   dmv = tmp_V * tmp_v1[j] * tmp_sgn;
   if (X->Large.mode == M_MLTPLY || X->Large.mode == M_CALCSPEC) { // for multply
     tmp_v0[j] += dmv;
   }
   dam_pr = conj(tmp_v1[j]) * dmv;
   return dam_pr;
 }/*double complex child_CisAisCisAis_element*/
child_CisAisCjtAku_element()
double complex child_CisAisCjtAku_element (long unsigned int j, long unsigned int isite1, long unsigned int isite3, long unsigned int isite4, long unsigned int Bsum, long unsigned int Bdiff, double complex tmp_V, double complex * tmp_v0, double complex * tmp_v1, struct BindStruct * X, long unsigned int * tmp_off)
Compute \(c_{is}^\dagger c_{is} c_{jt}^\dagger c_{ku}\) term of canonical Hubbard system.
Returns
Fragment of \(\langle v_1 | H_{\rm this} | v_1 \rangle\)
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] isite1 Site 1
[in] isite3 Site 3
[in] isite4 Site 4
[in] Bsum Bit mask for hopping
[in] Bdiff Bit mask for Fermion sign
[in] tmp_V Coupling constant
[in,out] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[in,out] X
[out] tmp_off Index of final wavefunction
Definition at line 718 of file mltplyHubbardCore.c.
References BindStruct::Large, list_1, LargeList::mode, X_CisAis(), and X_CisAjt().
Referenced by child_general_int(), expec_cisajscktalt_Hubbard(), and makeHam().
   {
   int tmp_sgn;
   double complex dmv;
   double complex dam_pr = 0 + 0 * I;
   tmp_sgn = X_CisAjt(list_1[j], X, isite3, isite4, Bsum, Bdiff, tmp_off);
   if (tmp_sgn != 0) {
     tmp_sgn *= X_CisAis(list_1[*tmp_off], X, isite1);
     if (tmp_sgn != 0) {
       dmv = tmp_V * tmp_v1[j] * tmp_sgn;
       if (X->Large.mode == M_MLTPLY || X->Large.mode == M_CALCSPEC) { // for multply
         tmp_v0[*tmp_off] += dmv;
       }
       dam_pr = conj(tmp_v1[*tmp_off]) * dmv;
     }
   }
   return dam_pr;
 }/*double complex child_CisAisCjtAku_element*/
child_CisAjtCkuAku_element()
double complex child_CisAjtCkuAku_element (long unsigned int j, long unsigned int isite1, long unsigned int isite2, long unsigned int isite3, long unsigned int Asum, long unsigned int Adiff, double complex tmp_V, double complex * tmp_v0, double complex * tmp_v1, struct BindStruct * X, long unsigned int * tmp_off)
Compute \(c_{is}^\dagger c_{jt} c_{ku}^\dagger c_{ku}\) term of canonical Hubbard system.
Returns
Fragment of \(\langle v_1 | H_{\rm this} | v_1 \rangle\)
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] isite1 Site 1
[in] isite2 Site 2
[in] isite3 Site 3
[in] Asum Bit mask for hopping
[in] Adiff Bit mask for Fermion sign
[in] tmp_V Coupling constant
[in,out] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[in,out] X
[out] tmp_off Index of final wavefunction
Definition at line 754 of file mltplyHubbardCore.c.
References BindStruct::Large, list_1, LargeList::mode, X_CisAis(), and X_CisAjt().
Referenced by child_general_int(), expec_cisajscktalt_Hubbard(), and makeHam().
   {
   int tmp_sgn;
   double complex dmv;
   double complex dam_pr;
   dam_pr = 0;
   tmp_sgn = X_CisAis(list_1[j], X, isite3);
   if (tmp_sgn != 0) {
     tmp_sgn *= X_CisAjt(list_1[j], X, isite1, isite2, Asum, Adiff, tmp_off);
     if (tmp_sgn != 0) {
       dmv = tmp_V * tmp_v1[j] * tmp_sgn;
       if (X->Large.mode == M_MLTPLY || X->Large.mode == M_CALCSPEC) { // for multply
         tmp_v0[*tmp_off] += dmv;
       }
       dam_pr = conj(tmp_v1[*tmp_off]) * dmv;
     }
   }
   return dam_pr;
 }/*double complex child_CisAjtCkuAku_element*/
child_CisAjtCkuAlv_element()
double complex child_CisAjtCkuAlv_element (long unsigned int j, long unsigned int isite1, long unsigned int isite2, long unsigned int isite3, long unsigned int isite4, long unsigned int Asum, long unsigned int Adiff, long unsigned int Bsum, long unsigned int Bdiff, double complex tmp_V, double complex * tmp_v0, double complex * tmp_v1, struct BindStruct * X, long unsigned int * tmp_off_2)
Compute \(c_{is}^\dagger c_{jt} c_{ku}^\dagger c_{lv}\) term of canonical Hubbard system.
Returns
Fragment of \(\langle v_1 | H_{\rm this} | v_1 \rangle\)
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] isite1 Site 1
[in] isite2 Site 2
[in] isite3 Site 3
[in] isite4 Site 4
[in] Asum Bit mask for hopping
[in] Adiff Bit mask for Fermion sign
[in] Bsum Bit mask for hopping
[in] Bdiff Bit mask for Fermion sign
[in] tmp_V Coupling constant
[in,out] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[in,out] X
[out] tmp_off_2 Index of final wavefunction
Definition at line 791 of file mltplyHubbardCore.c.
References BindStruct::Large, list_1, LargeList::mode, X_CisAjt(), and X_GC_CisAjt().
Referenced by child_general_int(), expec_cisajscktalt_Hubbard(), and makeHam().
   {
   int tmp_sgn;
   long unsigned int tmp_off_1;
   double complex dmv;
   double complex dam_pr = 0;
   tmp_sgn = X_GC_CisAjt(list_1[j], X, isite3, isite4, Bsum, Bdiff, &tmp_off_1);
   if (tmp_sgn != 0) {
     tmp_sgn *= X_CisAjt(tmp_off_1, X, isite1, isite2, Asum, Adiff, tmp_off_2);
     if (tmp_sgn != 0) {
       dmv = tmp_V * tmp_v1[j] * tmp_sgn;
       if (X->Large.mode == M_MLTPLY || X->Large.mode == M_CALCSPEC) { // for multply
         tmp_v0[*tmp_off_2] += dmv;
       }
       dam_pr = conj(tmp_v1[*tmp_off_2]) * dmv;
     }
   }
   return dam_pr;
 }/*double complex child_CisAjtCkuAlv_element*/
child_exchange_element()
double complex child_exchange_element (long unsigned int j, double complex * tmp_v0, double complex * tmp_v1, struct BindStruct * X, long unsigned int * tmp_off)
Compute exchange term of canonical-Hubbard.
Returns
\(\langle v_1|{\hat H}_{\rm this}|v_1\rangle\)
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in,out] tmp_v0 \(v_0 = H v_1\)
[in] tmp_v1 Vector to be producted
[in,out] X
tmp_off [off] Index of wavefunction of final state
Definition at line 472 of file mltplyHubbardCore.c.
References GetOffComp(), LargeList::ihfbit, LargeList::ilft, LargeList::irght, LargeList::is1_down, LargeList::is1_up, LargeList::is2_down, LargeList::is2_up, BindStruct::Large, list_1, list_2_1, list_2_2, LargeList::mode, LargeList::tmp_J, and TRUE.
Referenced by child_exchange(), and makeHam().
   {
   long unsigned int off;
   long unsigned int ibit1_up, ibit2_up, ibit1_down, ibit2_down;
   double complex dmv;
   long unsigned int iexchg;
   long unsigned int is1_up = X->Large.is1_up;
   long unsigned int is2_up = X->Large.is2_up;
   long unsigned int is1_down = X->Large.is1_down;
   long unsigned int is2_down = X->Large.is2_down;
   long unsigned int irght = X->Large.irght;
   long unsigned int ilft = X->Large.ilft;
   long unsigned int ihfbit = X->Large.ihfbit;
   double complex tmp_J = X->Large.tmp_J;
   int mode = X->Large.mode;
   double complex dam_pr = 0;
   ibit1_up = list_1[j] & is1_up;
   ibit2_up = list_1[j] & is2_up;
   ibit1_down = list_1[j] & is1_down;
   ibit2_down = list_1[j] & is2_down;
   if (ibit1_up == 0 && ibit1_down != 0 && ibit2_up != 0 && ibit2_down == 0) {
     iexchg = list_1[j] - (is1_down + is2_up);
     iexchg += (is1_up + is2_down);
     if(GetOffComp(list_2_1, list_2_2, iexchg, irght, ilft, ihfbit, &off)!=TRUE){
       return 0;
     }
     *tmp_off = off;
     dmv = tmp_J * tmp_v1[j];
     if (mode == M_MLTPLY) {
       tmp_v0[off] += dmv;
     }
     dam_pr += dmv * conj(tmp_v1[off]);
   }
   else if (ibit1_up != 0 && ibit1_down == 0 && ibit2_up == 0 && ibit2_down != 0) {
     iexchg = list_1[j] - (is1_up + is2_down);
     iexchg += (is1_down + is2_up);
     if(GetOffComp(list_2_1, list_2_2, iexchg, irght, ilft, ihfbit, &off)!=TRUE){
       return 0;
     }
     *tmp_off = off;
     dmv = tmp_J * tmp_v1[j];
     if (mode == M_MLTPLY) {
       tmp_v0[off] += dmv;
     }
     dam_pr += dmv * conj(tmp_v1[off]);
   }
   return dam_pr;
 }/*double complex child_exchange_element*/
child_exchange_GetInfo()
int child_exchange_GetInfo (int iExchange, struct BindStruct * X)
Compute mask for bit operation of exchange term.
Returns
Error-code, always return 0
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Copy coupling constant (LargeList::tmp_J)
Compute mask for checking occupations of \((i_1,\uparrow)\) (LargeList::is1_up), \((i_1,\downarrow)\) (LargeList::is1_down) \((i_2,\uparrow)\) (LargeList::is2_up), \((i_2,\downarrow)\) (LargeList::is2_down)
Parameters
[in] iExchange Index of exchange interaction
[in,out] X
Definition at line 197 of file mltplyHubbardCore.c.
References BindStruct::Def, DefineList::ExchangeCoupling, LargeList::is1_down, LargeList::is1_up, LargeList::is2_down, LargeList::is2_up, BindStruct::Large, DefineList::ParaExchangeCoupling, LargeList::tmp_J, and DefineList::Tpow.
Referenced by makeHam(), mltplyHubbard(), and mltplyHubbardGC().
   {
   int isite1 = X->Def.ExchangeCoupling[iExchange][0] + 1;
   int isite2 = X->Def.ExchangeCoupling[iExchange][1] + 1;
   X->Large.tmp_J = -X->Def.ParaExchangeCoupling[iExchange];
   X->Large.is1_up = X->Def.Tpow[2 * isite1 - 2];
   X->Large.is1_down = X->Def.Tpow[2 * isite1 - 1];
   X->Large.is2_up = X->Def.Tpow[2 * isite2 - 2];
   X->Large.is2_down = X->Def.Tpow[2 * isite2 - 1];
   return 0;
 }/*int child_exchange_GetInfo*/
child_general_hopp_GetInfo()
int child_general_hopp_GetInfo (struct BindStruct * X, unsigned long int isite1, unsigned long int isite2, unsigned long int sigma1, unsigned long int sigma2)
Compute mask for bit operation of hopping term.
Returns
Error-code, always return 0
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Compute mask for checking occupations of \((i_1,\sigma_1)\) (LargeList::is1_spin) and \((i_2,\sigma_2)\) (LargeList::is2_spin)
Compute mask for Fermion sign (LargeList::A_spin)
Compute mask for hopping (LargeList::isA_spin)
Parameters
[in,out] X
[in] isite1 Site index
[in] isite2 Site index
[in] sigma1 Spin index
[in] sigma2 Spin index
Definition at line 34 of file mltplyHubbardCore.c.
References LargeList::A_spin, BindStruct::Def, LargeList::is1_spin, LargeList::is2_spin, LargeList::isA_spin, BindStruct::Large, and DefineList::Tpow.
Referenced by expec_cisajs_Hubbard(), expec_cisajs_HubbardGC(), GetPairExcitedStateHubbard(), GetPairExcitedStateHubbardGC(), makeHam(), mltplyHalfSpinGC(), mltplyHubbard(), and mltplyHubbardGC().
   {
   X->Large.is1_spin = X->Def.Tpow[2 * isite1 - 2 + sigma1];
   X->Large.is2_spin = X->Def.Tpow[2 * isite2 - 2 + sigma2];
   if (isite1 > isite2) {
     X->Large.A_spin = (X->Def.Tpow[2 * isite1 - 2 + sigma1] - X->Def.Tpow[2 * isite2 - 1 + sigma2]);
   }
   else if (isite1 < isite2) {
     X->Large.A_spin = (X->Def.Tpow[2 * isite2 - 2 + sigma2] - X->Def.Tpow[2 * isite1 - 1 + sigma1]);
   }
   else {
     if (sigma1 > sigma2) {
       X->Large.A_spin = (X->Def.Tpow[2 * isite1 - 2 + sigma1] - X->Def.Tpow[2 * isite2 - 1 + sigma2]);
     }
     else {
       X->Large.A_spin = (X->Def.Tpow[2 * isite2 - 2 + sigma2] - X->Def.Tpow[2 * isite1 - 1 + sigma1]);
     }
   }
   X->Large.isA_spin = X->Large.is1_spin + X->Large.is2_spin;
   return 0;
 }/*int child_general_hopp_GetInfo*/
child_general_int_GetInfo()
int child_general_int_GetInfo (int iInterAll, struct BindStruct * X, long unsigned int isite1, long unsigned int isite2, long unsigned int isite3, long unsigned int isite4, long unsigned int sigma1, long unsigned int sigma2, long unsigned int sigma3, long unsigned int sigma4, double complex tmp_V)
Compute mask for bit operation of general interaction term.
Returns
Error-code, always return 0
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Compute mask for checking occupations of \((i_1,\sigma_1)\) (LargeList::is1_spin) and \((i_2,\sigma_2)\) (LargeList::is2_spin)
Compute mask for Fermion sign (LargeList::A_spin)
Compute mask for checking occupations of \((i_3,\sigma_3)\) (LargeList::is3_spin) and \((i_4,\sigma_4)\) (LargeList::is4_spin)
Compute mask for Fermion sign (LargeList::B_spin)
Compute mask for hopping (LargeList::isA_spin, LargeList::isB_spin)
Copy coupling constant (LargeList::tmp_V)
Parameters
[in] iInterAll It is not used
[in,out] X
[in] isite1 Site index
[in] isite2 Site index
[in] isite3 Site index
[in] isite4 Site index
[in] sigma1 Spin index
[in] sigma2 Spin index
[in] sigma3 Spin index
[in] sigma4 Spin index
[in] tmp_V Coupling constant
Definition at line 76 of file mltplyHubbardCore.c.
References LargeList::A_spin, LargeList::B_spin, BindStruct::Def, LargeList::is1_spin, LargeList::is2_spin, LargeList::is3_spin, LargeList::is4_spin, LargeList::isA_spin, LargeList::isB_spin, LargeList::isite1, LargeList::isite2, LargeList::isite3, LargeList::isite4, BindStruct::Large, LargeList::tmp_V, and DefineList::Tpow.
Referenced by expec_cisajscktalt_Hubbard(), expec_cisajscktalt_HubbardGC(), makeHam(), mltplyHubbard(), and mltplyHubbardGC().
   {
   long unsigned int is1_spin, is2_spin, is3_spin, is4_spin;
   long unsigned int A_spin, B_spin;
   long unsigned int isA_spin, isB_spin;
   is1_spin = X->Def.Tpow[2 * isite1 - 2 + sigma1];
   is2_spin = X->Def.Tpow[2 * isite2 - 2 + sigma2];
   if (isite1 > isite2) {
     A_spin = (X->Def.Tpow[2 * isite1 - 2 + sigma1] - X->Def.Tpow[2 * isite2 - 1 + sigma2]);
   }
   else if (isite2 > isite1) {
     A_spin = (X->Def.Tpow[2 * isite2 - 2 + sigma2] - X->Def.Tpow[2 * isite1 - 1 + sigma1]);
   }
   else {//isite1=isite2
     if (sigma1 > sigma2) {
       A_spin = (X->Def.Tpow[2 * isite1 - 2 + sigma1] - X->Def.Tpow[2 * isite2 - 1 + sigma2]);
     }
     else {
       A_spin = (X->Def.Tpow[2 * isite2 - 2 + sigma2] - X->Def.Tpow[2 * isite1 - 1 + sigma1]);
     }
   }
   is3_spin = X->Def.Tpow[2 * isite3 - 2 + sigma3];
   is4_spin = X->Def.Tpow[2 * isite4 - 2 + sigma4];
   if (isite3 > isite4) {
     B_spin = (X->Def.Tpow[2 * isite3 - 2 + sigma3] - X->Def.Tpow[2 * isite4 - 1 + sigma4]);
   }
   else if (isite3 < isite4) {
     B_spin = (X->Def.Tpow[2 * isite4 - 2 + sigma4] - X->Def.Tpow[2 * isite3 - 1 + sigma3]);
   }
   else {//isite3=isite4
     if (sigma3 > sigma4) {
       B_spin = (X->Def.Tpow[2 * isite3 - 2 + sigma3] - X->Def.Tpow[2 * isite4 - 1 + sigma4]);
     }
     else {
       B_spin = (X->Def.Tpow[2 * isite4 - 2 + sigma4] - X->Def.Tpow[2 * isite3 - 1 + sigma3]);
     }
   }
   isA_spin = is1_spin + is2_spin;
   isB_spin = is3_spin + is4_spin;
   X->Large.is1_spin = is1_spin;
   X->Large.is2_spin = is2_spin;
   X->Large.is3_spin = is3_spin;
   X->Large.is4_spin = is4_spin;
   X->Large.isA_spin = isA_spin;
   X->Large.isB_spin = isB_spin;
   X->Large.A_spin = A_spin;
   X->Large.B_spin = B_spin;
   X->Large.tmp_V = tmp_V;
   X->Large.isite1 = isite1;
   X->Large.isite2 = isite2;
   X->Large.isite3 = isite3;
   X->Large.isite4 = isite4;
   return 0;
 }/*int child_general_int_GetInfo*/
child_pairhopp_element()
double complex child_pairhopp_element (long unsigned int j, double complex * tmp_v0, double complex * tmp_v1, struct BindStruct * X, long unsigned int * tmp_off)
Compute pairhopp term of canonical Hubbard system.
Returns
Fragment of \(\langle v_1 | H_{\rm this} | v_1 \rangle\)
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in,out] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[in,out] X
[out] tmp_off Index of final wavefunction
Definition at line 533 of file mltplyHubbardCore.c.
References GetOffComp(), LargeList::ihfbit, LargeList::ilft, LargeList::irght, LargeList::is1_down, LargeList::is1_up, LargeList::is2_down, LargeList::is2_up, BindStruct::Large, list_1, list_2_1, list_2_2, LargeList::mode, LargeList::tmp_J, and TRUE.
Referenced by child_pairhopp(), and makeHam().
   {
   long unsigned int off;
   long unsigned int ibit1_up, ibit2_up, ibit1_down, ibit2_down;
   double complex dmv;
   long unsigned int iexchg;
   long unsigned int is1_up = X->Large.is1_up;
   long unsigned int is2_up = X->Large.is2_up;
   long unsigned int is1_down = X->Large.is1_down;
   long unsigned int is2_down = X->Large.is2_down;
   long unsigned int irght = X->Large.irght;
   long unsigned int ilft = X->Large.ilft;
   long unsigned int ihfbit = X->Large.ihfbit;
   double complex tmp_J = X->Large.tmp_J;
   int mode = X->Large.mode;
   double complex dam_pr = 0;
   ibit1_up = list_1[j] & is1_up;
   ibit2_up = list_1[j] & is2_up;
   ibit1_down = list_1[j] & is1_down;
   ibit2_down = list_1[j] & is2_down;
   if (ibit1_up == 0 && ibit1_down == 0 && ibit2_up != 0 && ibit2_down != 0) {
     iexchg = list_1[j] - (is2_up + is2_down);
     iexchg += (is1_up + is1_down);
     if(GetOffComp(list_2_1, list_2_2, iexchg, irght, ilft, ihfbit, &off)!=TRUE){
       return 0;
     }
     *tmp_off = off;
     dmv = tmp_J * tmp_v1[j];
     if (mode == M_MLTPLY || X->Large.mode == M_CALCSPEC) {
       tmp_v0[off] += dmv;
     }
     dam_pr += dmv * conj(tmp_v1[off]);
   }
   return dam_pr;
 }/*double complex child_pairhopp_element*/
child_pairhopp_GetInfo()
int child_pairhopp_GetInfo (int iPairHopp, struct BindStruct * X)
Compute mask for bit operation of pairhop term.
Returns
Error-code, always return 0
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Copy coupling constant (LargeList::tmp_J)
Compute mask for checking occupations of \((i_1,\uparrow)\) (LargeList::is1_up), \((i_1,\downarrow)\) (LargeList::is1_down) \((i_2,\uparrow)\) (LargeList::is2_up), \((i_2,\downarrow)\) (LargeList::is2_down)
Parameters
[in] iPairHopp Index of pairhopp interaction
[in,out] X
Definition at line 169 of file mltplyHubbardCore.c.
References BindStruct::Def, LargeList::is1_down, LargeList::is1_up, LargeList::is2_down, LargeList::is2_up, BindStruct::Large, DefineList::PairHopping, DefineList::ParaPairHopping, LargeList::tmp_J, and DefineList::Tpow.
Referenced by makeHam(), mltplyHubbard(), and mltplyHubbardGC().
   {
   int isite1 = X->Def.PairHopping[iPairHopp][0] + 1;
   int isite2 = X->Def.PairHopping[iPairHopp][1] + 1;
   X->Large.tmp_J = X->Def.ParaPairHopping[iPairHopp];
   X->Large.is1_up = X->Def.Tpow[2 * isite1 - 2];
   X->Large.is1_down = X->Def.Tpow[2 * isite1 - 1];
   X->Large.is2_up = X->Def.Tpow[2 * isite2 - 2];
   X->Large.is2_down = X->Def.Tpow[2 * isite2 - 1];
   return 0;
 }/*int child_pairhopp_GetInfo*/
CisAjt()
double complex CisAjt (long unsigned int j, double complex * tmp_v0, double complex * tmp_v1, struct BindStruct * X, long unsigned int is1_spin, long unsigned int is2_spin, long unsigned int sum_spin, long unsigned int diff_spin, double complex tmp_V)
\(c_{is}^\dagger c_{jt}\) term for canonical Hubbard
Returns
\(\langle v_1|{\hat H}_{\rm this}|v_1\rangle\)
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of wavefunction
[in,out] tmp_v0 \(v_0 = H v_1\)
[in] tmp_v1 Vector to be producted
[in,out] X
[in] is1_spin Mask for occupation of (is)
[in] is2_spin Mask for occupation of (jt)
[in] sum_spin Mask for hopping
[in] diff_spin Mask for Fermion sign
[in] tmp_V Hopping integral
Definition at line 305 of file mltplyHubbardCore.c.
References FALSE, GetOffComp(), LargeList::ihfbit, LargeList::ilft, LargeList::irght, BindStruct::Large, list_1, list_2_1, list_2_2, LargeList::mode, and SgnBit().
Referenced by child_general_hopp(), X_child_CisAjtCkuAku_Hubbard_MPI(), and X_child_CisAjtCkuAlv_Hubbard_MPI().
   {
   long unsigned int ibit_tmp_1, ibit_tmp_2;
   long unsigned int bit, iexchg, off;
   int sgn;
   double complex dmv, dam_pr;
   ibit_tmp_1 = (list_1[j] & is1_spin);
   ibit_tmp_2 = (list_1[j] & is2_spin);
   if (ibit_tmp_1 == 0 && ibit_tmp_2 != 0) {
     bit = list_1[j] & diff_spin;
     SgnBit(bit, &sgn); // Fermion sign
     iexchg = list_1[j] ^ sum_spin;
     if(GetOffComp(list_2_1, list_2_2, iexchg, X->Large.irght, X->Large.ilft, X->Large.ihfbit, &off)==FALSE){
       return 0;
     }
 /*
     if(X->Large.mode==M_CORR){
       fprintf(stdout, "DEBUG-1: myrank=%d, org=%d, bit=%d, iexchg=%d, list_1[%d]=%d\n",
               myrank, list_1[j], bit, iexchg, off, list_1[off]);
     }
 */
     dmv = sgn * tmp_v1[j];
     if (X->Large.mode == M_MLTPLY || X->Large.mode == M_CALCSPEC) { // for multply
       tmp_v0[off] += tmp_V * dmv;
     }
     dam_pr = dmv * conj(tmp_v1[off]);
     return dam_pr;
   }
   else {
     return 0;
   }
 }
GC_AisCis()
double complex GC_AisCis (long unsigned int j, double complex * tmp_v0, double complex * tmp_v1, struct BindStruct * X, long unsigned int is1_spin, double complex tmp_trans)
Operation of \(t c_{i\sigma} c_{i\sigma}^\dagger\) (Grandcanonical)
Returns
Fragment of \(\langle v_1|{\hat H}|v_1\rangle\)
Author
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of element of wavefunction
[in,out] tmp_v0 Result vector
[in] tmp_v1 Input producted vector
[in,out] X
[in] is1_spin Mask for occupation of \((i \sigma)\)
[in] tmp_trans Transfer integral
Definition at line 260 of file mltplyHubbardCore.c.
References BindStruct::Large, and LargeList::mode.
Referenced by GetPairExcitedStateHubbardGC().
   {
   long unsigned int A_ibit_tmp;
   long unsigned int list_1_j;
   double complex dmv;
   double complex dam_pr;
   list_1_j = j - 1;
   A_ibit_tmp = (list_1_j & is1_spin) / is1_spin;
   dmv = tmp_v1[j] * (1 - A_ibit_tmp);
   if (X->Large.mode == M_MLTPLY || X->Large.mode == M_CALCSPEC) {
     tmp_v0[j] += dmv * tmp_trans;
   }/*if (X->Large.mode == M_MLTPLY || X->Large.mode == M_CALCSPEC)*/
   dam_pr = dmv * conj(tmp_v1[j]);
   return dam_pr;
 }/*double complex GC_AisCis*/
GC_Ajt()
double complex GC_Ajt (long unsigned int j, double complex * tmp_v0, double complex * tmp_v1, long unsigned int is1_spin, double complex tmp_V, long unsigned int * tmp_off)
Compute \(c_{jt}\) term of grandcanonical Hubbard system.
Returns
Fragment of \(\langle v_1 | H_{\rm this} | v_1 \rangle\)
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Youhei Yamaji (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[in] is1_spin Bit mask
[in] tmp_V Coupling constant
[in] tmp_off Index of final wavefunction
Definition at line 1031 of file mltplyHubbardCore.c.
References myrank, and SgnBit().
Referenced by GetSingleExcitedStateHubbardGC().
   {
   long unsigned int list_1_j, list_1_off;
   long unsigned int ibit_tmp_1;
   long unsigned int bit;
   int sgn, ipsgn;
   double complex dmv, dam_pr;
   list_1_j = j - 1;
   ibit_tmp_1 = (list_1_j & is1_spin);
   // is1_spin >= 1
   *tmp_off = 0;
   if (ibit_tmp_1 == is1_spin) {
     // able to create an electron at the is1_spin state
     bit = list_1_j - (list_1_j & (2 * is1_spin - 1));
     SgnBit(bit, &sgn); // Fermion sign
     ipsgn = 1;
 #ifdef MPI
     SgnBit(myrank, &ipsgn); // Fermion sign
 #endif
     list_1_off = list_1_j ^ is1_spin;
     *tmp_off = list_1_off;
     dmv = ipsgn * sgn * tmp_v1[j];
     //if (X->Large.mode == M_MLTPLY) { // for multply
     tmp_v0[list_1_off + 1] += dmv * tmp_V;
     //}
     dam_pr = dmv * conj(tmp_v1[list_1_off + 1]);
     return dam_pr;
   }
   else {
     return 0;
   }
 }/*double complex GC_Ajt*/
GC_child_CisAisCisAis_element()
double complex GC_child_CisAisCisAis_element (long unsigned int j, long unsigned int isite1, long unsigned int isite3, double complex tmp_V, double complex * tmp_v0, double complex * tmp_v1, struct BindStruct * X, long unsigned int * tmp_off)
Compute \(c_{is}^\dagger c_{is} c_{is}^\dagger c_{is}\) term of grandcanonical Hubbard system.
Returns
Fragment of \(\langle v_1 | H_{\rm this} | v_1 \rangle\)
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] isite1 Site 1
[in] isite3 Site 3
[in] tmp_V Coupling constant
[in,out] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[in,out] X
[out] tmp_off Index of final wavefunction
Definition at line 834 of file mltplyHubbardCore.c.
References BindStruct::Large, LargeList::mode, and X_CisAis().
Referenced by expec_cisajscktalt_HubbardGC(), GC_child_general_int(), and makeHam().
   {
   int tmp_sgn;
   double complex dmv;
   double complex dam_pr = 0;
   tmp_sgn = X_CisAis(j - 1, X, isite3);
   tmp_sgn *= X_CisAis(j - 1, X, isite1);
   if (tmp_sgn != 0) {
     dmv = tmp_V * tmp_v1[j] * tmp_sgn;
     if (X->Large.mode == M_MLTPLY || X->Large.mode == M_CALCSPEC) { // for multply
       tmp_v0[j] += dmv;
     }
     dam_pr = conj(tmp_v1[j]) * dmv;
   }
   return dam_pr;
 }/*double complex GC_child_CisAisCisAis_element*/
GC_child_CisAisCjtAku_element()
double complex GC_child_CisAisCjtAku_element (long unsigned int j, long unsigned int isite1, long unsigned int isite3, long unsigned int isite4, long unsigned int Bsum, long unsigned int Bdiff, double complex tmp_V, double complex * tmp_v0, double complex * tmp_v1, struct BindStruct * X, long unsigned int * tmp_off)
Compute \(c_{is}^\dagger c_{is} c_{jt}^\dagger c_{ku}\) term of grandcanonical Hubbard system.
Returns
Fragment of \(\langle v_1 | H_{\rm this} | v_1 \rangle\)
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] isite1 Site 1
[in] isite3 Site 3
[in] isite4 Site 4
[in] Bsum Bit mask for hopping
[in] Bdiff Bit mask for Fermion sign
[in] tmp_V Coupling constant
[in,out] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[in,out] X
[out] tmp_off Index of final wavefunction
Definition at line 865 of file mltplyHubbardCore.c.
References BindStruct::Large, LargeList::mode, X_CisAis(), and X_GC_CisAjt().
Referenced by expec_cisajscktalt_HubbardGC(), GC_child_general_int(), and makeHam().
   {
   int tmp_sgn;
   double complex dmv;
   double complex dam_pr = 0 + 0 * I;
   tmp_sgn = X_GC_CisAjt((j - 1), X, isite3, isite4, Bsum, Bdiff, tmp_off);
   if (tmp_sgn != 0) {
     tmp_sgn *= X_CisAis(*tmp_off, X, isite1);
     if (tmp_sgn != 0) {
       dmv = tmp_V * tmp_v1[j] * tmp_sgn;
       if (X->Large.mode == M_MLTPLY || X->Large.mode == M_CALCSPEC) { // for multply
         tmp_v0[*tmp_off + 1] += dmv;
       }
       dam_pr = conj(tmp_v1[*tmp_off + 1]) * dmv;
     }
   }
   return dam_pr;
 }/*double complex GC_child_CisAisCjtAku_element*/
GC_child_CisAjtCkuAku_element()
double complex GC_child_CisAjtCkuAku_element (long unsigned int j, long unsigned int isite1, long unsigned int isite2, long unsigned int isite3, long unsigned int Asum, long unsigned int Adiff, double complex tmp_V, double complex * tmp_v0, double complex * tmp_v1, struct BindStruct * X, long unsigned int * tmp_off)
Compute \(c_{is}^\dagger c_{jt} c_{ku}^\dagger c_{ku}\) term of grandcanonical Hubbard system.
Returns
Fragment of \(\langle v_1 | H_{\rm this} | v_1 \rangle\)
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] isite1 Site 1
[in] isite2 Site 2
[in] isite3 Site 3
[in] Asum Bit mask for hopping
[in] Adiff Bit mask for Fermion sign
[in] tmp_V Coupling constant
[in,out] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[in,out] X
[out] tmp_off Index of final wavefunction
Definition at line 901 of file mltplyHubbardCore.c.
References BindStruct::Large, LargeList::mode, X_CisAis(), and X_GC_CisAjt().
Referenced by expec_cisajscktalt_HubbardGC(), GC_child_general_int(), and makeHam().
   {
   int tmp_sgn;
   double complex dmv;
   double complex dam_pr = 0 + 0 * I;
   tmp_sgn = X_CisAis((j - 1), X, isite3);
   if (tmp_sgn != 0) {
     tmp_sgn *= X_GC_CisAjt((j - 1), X, isite1, isite2, Asum, Adiff, tmp_off);
     if (tmp_sgn != 0) {
       dmv = tmp_V * tmp_v1[j] * tmp_sgn;
       if (X->Large.mode == M_MLTPLY || X->Large.mode == M_CALCSPEC) { // for multply
         tmp_v0[*tmp_off + 1] += dmv;
       }
       dam_pr = conj(tmp_v1[*tmp_off + 1]) * dmv;
     }/*if (tmp_sgn != 0)*/
   }/*if (tmp_sgn != 0)*/
   return dam_pr;
 }/*double complex GC_child_CisAjtCkuAku_element*/
GC_child_CisAjtCkuAlv_element()
double complex GC_child_CisAjtCkuAlv_element (long unsigned int j, long unsigned int isite1, long unsigned int isite2, long unsigned int isite3, long unsigned int isite4, long unsigned int Asum, long unsigned int Adiff, long unsigned int Bsum, long unsigned int Bdiff, double complex tmp_V, double complex * tmp_v0, double complex * tmp_v1, struct BindStruct * X, long unsigned int * tmp_off_2)
Compute \(c_{is}^\dagger c_{jt} c_{ku}^\dagger c_{lv}\) term of grandcanonical Hubbard system.
Returns
Fragment of \(\langle v_1 | H_{\rm this} | v_1 \rangle\)
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] isite1 Site 1
[in] isite2 Site 2
[in] isite3 Site 3
[in] isite4 Site 4
[in] Asum Bit mask for hopping
[in] Adiff Bit mask for Fermion sign
[in] Bsum Bit mask for hopping
[in] Bdiff Bit mask for Fermion sign
[in] tmp_V Coupling constant
[in,out] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[in,out] X
[out] tmp_off_2 Index of final wavefunction
Definition at line 937 of file mltplyHubbardCore.c.
References BindStruct::Large, LargeList::mode, and X_GC_CisAjt().
Referenced by expec_cisajscktalt_HubbardGC(), GC_child_general_int(), and makeHam().
   {
   int tmp_sgn;
   long unsigned int tmp_off_1;
   double complex dmv;
   double complex dam_pr = 0 + 0 * I;
   tmp_sgn = X_GC_CisAjt((j - 1), X, isite3, isite4, Bsum, Bdiff, &tmp_off_1);
   if (tmp_sgn != 0) {
     tmp_sgn *= X_GC_CisAjt(tmp_off_1, X, isite1, isite2, Asum, Adiff, tmp_off_2);
     if (tmp_sgn != 0) {
       dmv = tmp_V * tmp_v1[j] * tmp_sgn;
       if (X->Large.mode == M_MLTPLY || X->Large.mode == M_CALCSPEC) { // for multply
         tmp_v0[*tmp_off_2 + 1] += dmv;
       }
       dam_pr = conj(tmp_v1[*tmp_off_2 + 1]) * dmv;
     }
   }
   return dam_pr;
 }/*double complex GC_child_CisAjtCkuAlv_element*/
GC_child_exchange_element()
double complex GC_child_exchange_element (long unsigned int j, double complex * tmp_v0, double complex * tmp_v1, struct BindStruct * X, long unsigned int * tmp_off)
Compute exchange term of grandcanonical Hubbard system.
Returns
Fragment of \(\langle v_1 | H_{\rm this} | v_1 \rangle\)
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in,out] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[in,out] X
[out] tmp_off Index of final wavefunction
Definition at line 582 of file mltplyHubbardCore.c.
References LargeList::is1_down, LargeList::is1_up, LargeList::is2_down, LargeList::is2_up, BindStruct::Large, LargeList::mode, and LargeList::tmp_J.
Referenced by GC_child_exchange(), and makeHam().
   {
   long unsigned int ibit1_up, ibit2_up, ibit1_down, ibit2_down;
   double complex dmv;
   long unsigned int iexchg;
   long unsigned int is1_up = X->Large.is1_up;
   long unsigned int is2_up = X->Large.is2_up;
   long unsigned int is1_down = X->Large.is1_down;
   long unsigned int is2_down = X->Large.is2_down;
   long unsigned int list_1_j, list_1_off;
   double complex tmp_J = X->Large.tmp_J;
   int mode = X->Large.mode;
   double complex dam_pr = 0;
   list_1_j = j - 1;
   ibit1_up = list_1_j & is1_up;
   ibit2_up = list_1_j & is2_up;
   ibit1_down = list_1_j & is1_down;
   ibit2_down = list_1_j & is2_down;
   if (ibit1_up == 0 && ibit1_down != 0 && ibit2_up != 0 && ibit2_down == 0) {
     iexchg = list_1_j - (is1_down + is2_up);
     iexchg += (is1_up + is2_down);
     list_1_off = iexchg;
     *tmp_off = list_1_off;
     dmv = tmp_J * tmp_v1[j];
     if (mode == M_MLTPLY) {
       tmp_v0[list_1_off + 1] += dmv;
     }
     dam_pr += dmv * conj(tmp_v1[list_1_off + 1]);
   }
   else if (ibit1_up != 0 && ibit1_down == 0 && ibit2_up == 0 && ibit2_down != 0) {
     iexchg = list_1_j - (is1_up + is2_down);
     iexchg += (is1_down + is2_up);
     list_1_off = iexchg;
     *tmp_off = list_1_off;
     dmv = tmp_J * tmp_v1[j];
     if (mode == M_MLTPLY) {
       tmp_v0[list_1_off + 1] += dmv;
     }
     dam_pr += dmv * conj(tmp_v1[list_1_off + 1]);
   }
   return dam_pr;
 }/*double complex GC_child_exchange_element*/
GC_child_pairhopp_element()
double complex GC_child_pairhopp_element (long unsigned int j, double complex * tmp_v0, double complex * tmp_v1, struct BindStruct * X, long unsigned int * tmp_off)
Compute pairhopp term of grandcanonical Hubbard system.
Returns
Fragment of \(\langle v_1 | H_{\rm this} | v_1 \rangle\)
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in,out] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[in,out] X
[out] tmp_off Index of final wavefunction
Definition at line 640 of file mltplyHubbardCore.c.
References LargeList::is1_down, LargeList::is1_up, LargeList::is2_down, LargeList::is2_up, BindStruct::Large, LargeList::mode, and LargeList::tmp_J.
Referenced by GC_child_pairhopp(), and makeHam().
   {
   long unsigned int ibit1_up, ibit2_up, ibit1_down, ibit2_down;
   double complex dmv;
   long unsigned int iexchg;
   long unsigned int is1_up = X->Large.is1_up;
   long unsigned int is2_up = X->Large.is2_up;
   long unsigned int is1_down = X->Large.is1_down;
   long unsigned int is2_down = X->Large.is2_down;
   long unsigned int list_1_j, list_1_off;
   double complex tmp_J = X->Large.tmp_J;
   int mode = X->Large.mode;
   double complex dam_pr = 0 + 0 * I;
   list_1_j = j - 1;
   ibit1_up = list_1_j & is1_up;
   ibit2_up = list_1_j & is2_up;
   ibit1_down = list_1_j & is1_down;
   ibit2_down = list_1_j & is2_down;
   if (ibit1_up == 0 && ibit1_down == 0 && ibit2_up != 0 && ibit2_down != 0) {
     iexchg = list_1_j - (is2_up + is2_down);
     iexchg += (is1_up + is1_down);
     list_1_off = iexchg;
     *tmp_off = list_1_off;
     dmv = tmp_J * tmp_v1[j];
     if (mode == M_MLTPLY || X->Large.mode == M_CALCSPEC) {
       tmp_v0[list_1_off + 1] += dmv;
     }
     dam_pr += dmv * conj(tmp_v1[list_1_off + 1]);
   }
   return dam_pr;
 }
GC_Cis()
double complex GC_Cis (long unsigned int j, double complex * tmp_v0, double complex * tmp_v1, long unsigned int is1_spin, double complex tmp_V, long unsigned int * tmp_off)
Compute \(c_{is}^\dagger\) term of grandcanonical Hubbard system.
Returns
Fragment of \(\langle v_1 | H_{\rm this} | v_1 \rangle\)
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Youhei Yamaji (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[in] is1_spin Bit mask
[in] tmp_V Coupling constant
[in] tmp_off Index of final wavefunction
Definition at line 980 of file mltplyHubbardCore.c.
References myrank, and SgnBit().
Referenced by GetSingleExcitedStateHubbardGC().
   {
   long unsigned int list_1_j, list_1_off;
   long unsigned int ibit_tmp_1;
   long unsigned int bit;
   int sgn, ipsgn;
   double complex dmv, dam_pr;
   list_1_j = j - 1;
   ibit_tmp_1 = (list_1_j & is1_spin);
   // is1_spin >= 1
   // is1_spin = Tpow[2*isite + ispin]
   *tmp_off = 0;
   if (ibit_tmp_1 == 0) {
     // able to create an electron at the is1_spin state
     bit = list_1_j - (list_1_j & (2 * is1_spin - 1));
     SgnBit(bit, &sgn); // Fermion sign
     ipsgn = 1;
 #ifdef MPI
     SgnBit(myrank, &ipsgn); // Fermion sign
 #endif
     list_1_off = list_1_j | is1_spin; // OR
     *tmp_off = list_1_off;
     dmv = ipsgn * sgn * tmp_v1[j];
     //if (X->Large.mode == M_MLTPLY) { // for multply
     tmp_v0[list_1_off + 1] += dmv * tmp_V;
     //}
     dam_pr = dmv * conj(tmp_v1[list_1_off + 1]);
     return dam_pr;
   }
   else {
     return 0;
   }
 }/*double complex GC_Cis*/
GC_CisAis()
double complex GC_CisAis (long unsigned int j, double complex * tmp_v0, double complex * tmp_v1, struct BindStruct * X, long unsigned int is1_spin, double complex tmp_trans)
Operation of \(t c_{i\sigma}^\dagger c_{i\sigma}\) (Grandcanonical)
Returns
Fragment of \(\langle v_1|{\hat H}|v_1\rangle\)
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of element of wavefunction
[in,out] tmp_v0 Result vector
[in] tmp_v1 Input producted vector
[in,out] X
[in] is1_spin Mask for occupation of \((i \sigma)\)
[in] tmp_trans Transfer integral
Definition at line 233 of file mltplyHubbardCore.c.
References BindStruct::Large, and LargeList::mode.
Referenced by GC_child_general_hopp().
   {
   long unsigned int A_ibit_tmp;
   long unsigned int list_1_j;
   double complex dmv;
   double complex dam_pr;
   list_1_j = j - 1;
   A_ibit_tmp = (list_1_j & is1_spin) / is1_spin;
   dmv = tmp_v1[j] * A_ibit_tmp;
   if (X->Large.mode == M_MLTPLY || X->Large.mode == M_CALCSPEC) {
     tmp_v0[j] += dmv * tmp_trans;
   }/*if (X->Large.mode == M_MLTPLY || X->Large.mode == M_CALCSPEC)*/
   dam_pr = dmv * conj(tmp_v1[j]);
   return dam_pr;
 }/*double complex GC_CisAis*/
GC_CisAjt()
double complex GC_CisAjt (long unsigned int j, double complex * tmp_v0, double complex * tmp_v1, struct BindStruct * X, long unsigned int is1_spin, long unsigned int is2_spin, long unsigned int sum_spin, long unsigned int diff_spin, double complex tmp_V, long unsigned int * tmp_off)
\(c_{is}^\dagger c_{jt}\) term for grandcanonical Hubbard
Returns
\(\langle v_1|{\hat H}_{\rm this}|v_1\rangle\)
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of wavefunction
[in] tmp_v0 \(v_0 = H v_1\)
[in] tmp_v1 Vector to be producted
[in,out] X
[in] is1_spin Mask for occupation of (is)
[in] is2_spin Mask for occupation of (jt)
[in] sum_spin Mask for hopping
[in] diff_spin Mask for Fermion sign
[in] tmp_V Hopping
[in] tmp_off Index of wavefunction of final state
Definition at line 354 of file mltplyHubbardCore.c.
References BindStruct::Large, LargeList::mode, and SgnBit().
Referenced by GC_child_general_hopp(), makeHam(), X_GC_child_CisAjtCkuAku_Hubbard_MPI(), and X_GC_child_CisAjtCkuAlv_Hubbard_MPI().
   {
   long unsigned int list_1_j, list_1_off;
   long unsigned int ibit_tmp_1, ibit_tmp_2;
   long unsigned int bit;
   int sgn;
   double complex dmv, dam_pr;
   list_1_j = j - 1;
   ibit_tmp_1 = (list_1_j & is1_spin);
   ibit_tmp_2 = (list_1_j & is2_spin);
   *tmp_off = 0;
   if (ibit_tmp_1 == 0 && ibit_tmp_2 != 0) {
     bit = list_1_j & diff_spin;
     SgnBit(bit, &sgn); // Fermion sign
     list_1_off = list_1_j ^ sum_spin;
     *tmp_off = list_1_off;
     dmv = sgn * tmp_v1[j];
     if (X->Large.mode == M_MLTPLY || X->Large.mode == M_CALCSPEC) { // for multply
       tmp_v0[list_1_off + 1] += dmv * tmp_V;
     }
     dam_pr = dmv * conj(tmp_v1[list_1_off + 1]);
     return dam_pr;
   }
   else {
     return 0;
   }
 }/*double complex GC_CisAjt*/
X_Ajt()
double complex X_Ajt (long unsigned int j, long unsigned int is1_spin, long unsigned int * tmp_off, long unsigned int * list_1_org, long unsigned int * list_2_1_target, long unsigned int * list_2_2_target, long unsigned int _irght, long unsigned int _ilft, long unsigned int _ihfbit)
Compute index of final wavefunction associatesd to \(c_{jt}\) term of canonical Hubbard system.
Returns
1 if electron (jt) exist, 0 if not.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Youhei Yamaji (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] is1_spin Bit mask
[out] tmp_off Index of final wavefunction
[in] list_1_org Similar to list_1
[in] list_2_1_target Similar to list_2_1
[in] list_2_2_target Similar to list_2_2
[in] _irght Similar to LargeList::irght
[in] _ilft Similar to LargeList::ilft
[in] _ihfbit Similar to LargeList::ihfbit
Definition at line 1135 of file mltplyHubbardCore.c.
References GetOffComp(), myrank, SgnBit(), and TRUE.
Referenced by GetSingleExcitedStateHubbard().
   {
   long unsigned int list_1_j, list_1_off;
   long unsigned int ibit_tmp_1;
   long unsigned int bit;
   int sgn, ipsgn;
   list_1_j = list_1_org[j];
   ibit_tmp_1 = (list_1_j & is1_spin);
 // is1_spin >= 1
 // is1_spin = Tpow[2*isite + ispin]
   *tmp_off = 0;
   if (ibit_tmp_1 != 0) {
     // able to delete an electron at the is1_spin state
     bit = list_1_j - (list_1_j & (2 * is1_spin - 1));
     SgnBit(bit, &sgn); // Fermion sign
     ipsgn = 1;
 #ifdef MPI
     SgnBit(myrank, &ipsgn); // Fermion sign
 #endif
     list_1_off = list_1_j ^ is1_spin;
     if(GetOffComp(list_2_1_target, list_2_2_target, list_1_off, _irght, _ilft, _ihfbit, tmp_off)!=TRUE){
       *tmp_off=0;
       return 0;
     }
     sgn *= ipsgn;
     return(sgn);
   }
   else {
     *tmp_off = 0;
     return 0;
   }
 }/*double complex X_Ajt*/
X_Cis()
int X_Cis (long unsigned int j, long unsigned int is1_spin, long unsigned int * tmp_off, long unsigned int * list_1_org, long unsigned int * list_2_1_target, long unsigned int * list_2_2_target, long unsigned int _irght, long unsigned int _ilft, long unsigned int _ihfbit)
Compute index of final wavefunction associatesd to \(c_{is}^\dagger\) term of canonical Hubbard system.
Returns
1 if electron (is) absent, 0 if not.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Youhei Yamaji (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] is1_spin Bit mask
[out] tmp_off Index of final wavefunction
[in] list_1_org Similar to list_1
[in] list_2_1_target Similar to list_2_1
[in] list_2_2_target Similar to list_2_2
[in] _irght Similar to LargeList::irght
[in] _ilft Similar to LargeList::ilft
[in] _ihfbit Similar to LargeList::ihfbit
Definition at line 1081 of file mltplyHubbardCore.c.
References GetOffComp(), myrank, SgnBit(), and TRUE.
Referenced by GetSingleExcitedStateHubbard().
   {
   long unsigned int list_1_j, list_1_off;
   long unsigned int ibit_tmp_1;
   long unsigned int bit;
   int sgn, ipsgn;
   list_1_j = list_1_org[j];
   ibit_tmp_1 = (list_1_j & is1_spin);
   // is1_spin >= 1
   // is1_spin = Tpow[2*isite + ispin]
   *tmp_off = 0;
   if (ibit_tmp_1 == 0) {
     // able to create an electron at the is1_spin state
     bit = list_1_j - (list_1_j & (2 * is1_spin - 1));
     SgnBit(bit, &sgn); // Fermion sign
     ipsgn = 1;
 #ifdef MPI
     SgnBit(myrank, &ipsgn); // Fermion sign
 #endif
     list_1_off = list_1_j | is1_spin; // OR
     if(GetOffComp(list_2_1_target, list_2_2_target, list_1_off, _irght, _ilft, _ihfbit, tmp_off)!=TRUE){
       *tmp_off=0;
       return 0;
     }
     sgn *= ipsgn;
     return (sgn);
   }
   else {
     *tmp_off = 0;
     return 0;
   }
 }/*int X_Cis*/
X_CisAis()
int X_CisAis (long unsigned int list_1_j, struct BindStruct * X, long unsigned int is1_spin)
\(c_{is}\\dagger c_{is}\) term in Hubbard (canonical)
Returns
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Definition at line 288 of file mltplyHubbardCore.c.
Referenced by child_CisAisCisAis_element(), child_CisAisCjtAku_element(), child_CisAjtCkuAku_element(), GC_child_CisAisCisAis_element(), GC_child_CisAisCjtAku_element(), GC_child_CisAjtCkuAku_element(), and X_child_CisAis_Hubbard_MPI().
   {
   int A_ibit_tmp;
   // off = j
   A_ibit_tmp = (list_1_j & is1_spin) / is1_spin;
   return A_ibit_tmp;
 }
X_CisAjt()
int X_CisAjt (long unsigned int list_1_j, struct BindStruct * X, long unsigned int is1_spin, long unsigned int is2_spin, long unsigned int sum_spin, long unsigned int diff_spin, long unsigned int * tmp_off)
Compute index of wavefunction of final state.
Returns
Fermion sign
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] list_1_j Similer to list_1 ?
[in] X
[in] is1_spin Mask for occupation of (is)
[in] is2_spin Mask for occupation of (jt)
[in] sum_spin Mask for hopping
[in] diff_spin Mask for Fermion sign
[in] tmp_off Index of wavefunction of final state
Definition at line 399 of file mltplyHubbardCore.c.
References GetOffComp(), LargeList::ihfbit, LargeList::ilft, LargeList::irght, BindStruct::Large, list_2_1, list_2_2, TRUE, and X_GC_CisAjt().
Referenced by child_CisAisCjtAku_element(), child_CisAjtCkuAku_element(), child_CisAjtCkuAlv_element(), GetPairExcitedStateHubbard(), and makeHam().
   {
   long unsigned int off;
   int sgn = 1;
   sgn = X_GC_CisAjt(list_1_j, X, is1_spin, is2_spin, sum_spin, diff_spin, tmp_off);
   if (sgn != 0) {
     if(GetOffComp(list_2_1, list_2_2, *tmp_off, X->Large.irght, X->Large.ilft, X->Large.ihfbit, &off)!=TRUE){
       *tmp_off = 0;
       return 0;
     }
     *tmp_off = off;
     return sgn;
   }
   else {
     *tmp_off = 0;
     return 0;
   }
 }/*int X_CisAjt*/
X_GC_CisAjt()
int X_GC_CisAjt (long unsigned int list_1_j, struct BindStruct * X, long unsigned int is1_spin, long unsigned int is2_spin, long unsigned int sum_spin, long unsigned int diff_spin, long unsigned int * tmp_off)
Compute index of wavefunction of final state.
Returns
Fermion sign
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] list_1_j list_1 ?
[in] X
[in] is1_spin Mask for occupation of (is)
[in] is2_spin Mask for occupation of (jt)
[in] sum_spin Mask for hopping
[in] diff_spin Mask for Fermion sign
[out] tmp_off Index of wavefunction of final state
Definition at line 431 of file mltplyHubbardCore.c.
References SgnBit().
Referenced by child_CisAjtCkuAlv_element(), GC_child_CisAisCjtAku_element(), GC_child_CisAjtCkuAku_element(), GC_child_CisAjtCkuAlv_element(), GetSgnInterAll(), X_child_CisAjtCkuAlv_Hubbard_MPI(), X_CisAjt(), and X_GC_child_CisAjtCkuAlv_Hubbard_MPI().
   {
   long unsigned int ibit_tmp_1, ibit_tmp_2;
   long unsigned int bit, off;
   int sgn = 1;
   ibit_tmp_1 = (list_1_j & is1_spin);
   ibit_tmp_2 = (list_1_j & is2_spin);
   if (ibit_tmp_1 == 0 && ibit_tmp_2 != 0) {
     bit = list_1_j & diff_spin;
     SgnBit(bit, &sgn); // Fermion sign
     off = list_1_j ^ sum_spin;
     *tmp_off = off;
     return sgn; // pm 1
   }
   else {
     *tmp_off = 0;
     return 0;
   }
 }