HΦ: mltplySpinCore.c File Reference
mltplySpinCore.c File Reference
Functions for spin Hamiltonian (Core)
#include <bitcalc.h>
#include "mfmemory.h"
#include "xsetmem.h"
#include "wrapperMPI.h"
#include "mltplyCommon.h"
#include "mltplySpinCore.h"
Functions
int child_exchange_spin_GetInfo (int iExchange, struct BindStruct *X)
Set parameters for the bit operation of spin-exchange term.
int child_pairlift_spin_GetInfo (int iPairLift, struct BindStruct *X)
Set parameters for the bit operation of spin-pairlift term.
int child_general_int_spin_GetInfo (struct BindStruct *X, long unsigned int isite1, long unsigned int isite2, long unsigned int sigma1, long unsigned int sigma2, long unsigned int sigma3, long unsigned int sigma4, double complex tmp_V)
Set parameters for the bit operation of spin-general interaction term.
int X_Spin_CisAit (long unsigned int j, struct BindStruct *X, long unsigned int is1_spin, long unsigned int sigma2, long unsigned int *list_1_Org_, long unsigned int *list_2_1_, long unsigned int *list_2_2_, long unsigned int *tmp_off)
Compute index of final wavefunction by \(c_{is}^\dagger c_{it}\) term.
int X_Spin_CisAis (long unsigned int j, struct BindStruct *X, long unsigned int is1_spin, long unsigned int sigma1)
Compute the spin state with bit mask is1_spin.
int X_SpinGC_CisAis (long unsigned int j, struct BindStruct *X, long unsigned int is1_spin, long unsigned int sigma1)
Compute the grandcanonical spin state with bit mask is1_spin.
int X_SpinGC_CisAit (long unsigned int j, struct BindStruct *X, long unsigned int is1_spin, long unsigned int sigma2, long unsigned int *tmp_off)
Compute index of final wavefunction by \(c_{is}^\dagger c_{it}\) term (grandcanonical).
int X_child_exchange_spin_element (long unsigned int j, struct BindStruct *X, long unsigned int isA_up, long unsigned int isB_up, long unsigned int sigmaA, long unsigned int sigmaB, long unsigned int *tmp_off)
Compute index of final wavefunction associated to spin-exchange term.
double complex child_exchange_spin_element (long unsigned int j, double complex *tmp_v0, double complex *tmp_v1, struct BindStruct *X, long unsigned int *tmp_off)
Multiply Hamiltonian of exchange term of canonical spin system.
double complex GC_child_exchange_spin_element (long unsigned int j, double complex *tmp_v0, double complex *tmp_v1, struct BindStruct *X, long unsigned int *tmp_off)
Multiply Hamiltonian of exchange term of grandcanonical spin system.
double complex GC_child_pairlift_spin_element (long unsigned int j, double complex *tmp_v0, double complex *tmp_v1, struct BindStruct *X, long unsigned int *tmp_off)
Multiply Hamiltonian of pairlift term of grandcanonical spin system.
double complex child_CisAisCisAis_spin_element (long unsigned int j, long unsigned int isA_up, long unsigned int isB_up, long unsigned int org_sigma2, long unsigned int org_sigma4, double complex tmp_V, double complex *tmp_v0, double complex *tmp_v1, struct BindStruct *X)
Compute \(c_{is}^\dagger c_{is} c_{is}^\dagger c_{is}\) term of canonical spsin system.
double complex GC_child_CisAisCisAis_spin_element (long unsigned int j, long unsigned int isA_up, long unsigned int isB_up, long unsigned int org_sigma2, long unsigned int org_sigma4, double complex tmp_V, double complex *tmp_v0, double complex *tmp_v1, struct BindStruct *X)
Compute \(c_{is}^\dagger c_{is} c_{is}^\dagger c_{is}\) term of grandcanonical spsin system.
double complex GC_child_CisAisCitAiu_spin_element (long unsigned int j, long unsigned int org_sigma2, long unsigned int org_sigma4, long unsigned int isA_up, long unsigned int isB_up, double complex tmp_V, double complex *tmp_v0, double complex *tmp_v1, struct BindStruct *X, long unsigned int *tmp_off)
Compute \(c_{is}^\dagger c_{is} c_{it}^\dagger c_{iu}\) term of grandcanonical spsin system.
double complex GC_child_CisAitCiuAiu_spin_element (long unsigned int j, long unsigned int org_sigma2, long unsigned int org_sigma4, long unsigned int isA_up, long unsigned int isB_up, double complex tmp_V, double complex *tmp_v0, double complex *tmp_v1, struct BindStruct *X, long unsigned int *tmp_off)
Compute \(c_{is}^\dagger c_{it} c_{iu}^\dagger c_{iu}\) term of grandcanonical spsin system.
double complex GC_child_CisAitCiuAiv_spin_element (long unsigned int j, long unsigned int org_sigma2, long unsigned int org_sigma4, long unsigned int isA_up, long unsigned int isB_up, double complex tmp_V, double complex *tmp_v0, double complex *tmp_v1, struct BindStruct *X, long unsigned int *tmp_off_2)
Compute \(c_{is}^\dagger c_{it} c_{iu}^\dagger c_{iv}\) term of grandcanonical spsin system.
Detailed Description
Functions for spin Hamiltonian (Core)
Definition in file mltplySpinCore.c.
Function Documentation
double complex child_CisAisCisAis_spin_element (long unsigned int j, long unsigned int isA_up, long unsigned int isB_up, long unsigned int org_sigma2, long unsigned int org_sigma4, double complex tmp_V, double complex * tmp_v0, double complex * tmp_v1, struct BindStruct * X)
Compute \(c_{is}^\dagger c_{is} c_{is}^\dagger c_{is}\) term of canonical spsin system.
Returns
Fragment of \(\langle v_1 | H_{\rm this}|v_1 \rangle\)
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] isA_up Bit mask for spin 1
[in] isB_up Bit mask for spin 2
[in] org_sigma2 Target for spin 1
[in] org_sigma4 Target for spin 2
[in] tmp_V Coupling constatnt
[in] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[in,out] X
Definition at line 392 of file mltplySpinCore.c.
References BindStruct::Large, LargeList::mode, and X_Spin_CisAis().
Referenced by expec_cisajscktalt_SpinHalf().
   {
   int tmp_sgn;
   double complex dmv;
   double complex dam_pr = 0;
   tmp_sgn = X_Spin_CisAis(j, X, isB_up, org_sigma4);
   tmp_sgn *= X_Spin_CisAis(j, X, isA_up, org_sigma2);
   dmv = tmp_v1[j] * tmp_sgn * tmp_V;
   if (X->Large.mode == M_MLTPLY || X->Large.mode == M_CALCSPEC) { // for multply
     tmp_v0[j] += dmv;
   }
   dam_pr = conj(tmp_v1[j]) * dmv;
   return dam_pr;
 }/*double complex child_CisAisCisAis_spin_element*/
double complex child_exchange_spin_element (long unsigned int j, double complex * tmp_v0, double complex * tmp_v1, struct BindStruct * X, long unsigned int * tmp_off)
Multiply Hamiltonian of exchange term of canonical spin system.
Returns
\(\langle v_1 | H_{\rm this}| v_1 \rangle\)
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[out] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[in,out] X
[out] tmp_off Index of final wavefunction
Definition at line 274 of file mltplySpinCore.c.
References GetOffComp(), LargeList::ihfbit, LargeList::ilft, LargeList::irght, LargeList::isA_spin, BindStruct::Large, list_1, list_2_1, list_2_2, LargeList::mode, and LargeList::tmp_J.
Referenced by child_exchange_spin(), and makeHam().
   {
   long unsigned int off;
   double complex dmv;
   long unsigned int iexchg;
   long unsigned int is_up = X->Large.isA_spin;
   long unsigned int irght = X->Large.irght;
   long unsigned int ilft = X->Large.ilft;
   long unsigned int ihfbit = X->Large.ihfbit;
   double complex tmp_J = X->Large.tmp_J;
   int mode = X->Large.mode;
   double complex dam_pr = 0;
   long unsigned int ibit_tmp;
   ibit_tmp = (list_1[j] & is_up);
   if (ibit_tmp == 0 || ibit_tmp == is_up) {
     return dam_pr;
   }
   else {
     iexchg = list_1[j] ^ is_up;
     GetOffComp(list_2_1, list_2_2, iexchg, irght, ilft, ihfbit, &off);
     *tmp_off = off;
     dmv = tmp_J * tmp_v1[j];
     if (mode == M_MLTPLY) {
       tmp_v0[off] += dmv;
     }
     dam_pr += dmv * conj(tmp_v1[off]);
     return dam_pr;
   }
 }/*double complex child_exchange_spin_element*/
int child_exchange_spin_GetInfo (int iExchange, struct BindStruct * X)
Set parameters for the bit operation of spin-exchange term.
Returns
Always return 0
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Set the exchange coupling constant (LargeList::tmp_J)
Set the bit mask for computing spin state of both site (LargeList::is1_up, LargeList::is2_up)
Set the bit mask for exchange 2 spins (LargeList::isA_spin)
Parameters
[in] iExchange Counter of exchange interaction
[in,out] X
Definition at line 36 of file mltplySpinCore.c.
References BindStruct::Def, DefineList::ExchangeCoupling, LargeList::is1_up, LargeList::is2_up, LargeList::isA_spin, BindStruct::Large, DefineList::ParaExchangeCoupling, LargeList::tmp_J, and DefineList::Tpow.
Referenced by makeHam(), mltplyHalfSpin(), and mltplyHalfSpinGC().
   {
   int isite1 = X->Def.ExchangeCoupling[iExchange][0] + 1;
   int isite2 = X->Def.ExchangeCoupling[iExchange][1] + 1;
   X->Large.tmp_J = X->Def.ParaExchangeCoupling[iExchange];
   X->Large.is1_up = X->Def.Tpow[isite1 - 1];
   X->Large.is2_up = X->Def.Tpow[isite2 - 1];
   X->Large.isA_spin = X->Large.is1_up + X->Large.is2_up;
   return 0;
 }/*int child_exchange_spin_GetInfo*/
int child_general_int_spin_GetInfo (struct BindStruct * X, long unsigned int isite1, long unsigned int isite2, long unsigned int sigma1, long unsigned int sigma2, long unsigned int sigma3, long unsigned int sigma4, double complex tmp_V)
Set parameters for the bit operation of spin-general interaction term.
Returns
Always return 0
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Set the pairlift coupling constant (LargeList::tmp_J)
Set the bit mask for computing spin state of both site (LargeList::is1_up, LargeList::is2_up)
Set the bit mask for general interaction (LargeList::is1_spin, LargeList::is2_spin, LargeList::is3_spin, LargeList::is4_spin)
Parameters
[in,out] X
[in] isite1 Site 1
[in] isite2 Site 2
[in] sigma1 Sigma 1, final state of site 1
[in] sigma2 Sigma 3, initial state of site 1
[in] sigma3 Sigma 3, final state of site 2
[in] sigma4 Sigma 4, initial state of site 2
[in] tmp_V General interaction constatnt
Definition at line 92 of file mltplySpinCore.c.
References BindStruct::Def, LargeList::is1_spin, LargeList::is1_up, LargeList::is2_spin, LargeList::is2_up, LargeList::is3_spin, LargeList::is4_spin, LargeList::isite1, LargeList::isite2, BindStruct::Large, LargeList::tmp_V, and DefineList::Tpow.
Referenced by makeHam(), mltplyHalfSpin(), and mltplyHalfSpinGC().
   {
   X->Large.tmp_V = tmp_V;
   X->Large.isite1 = isite1;
   X->Large.isite2 = isite2;
   X->Large.is1_up = X->Def.Tpow[isite1 - 1];
   X->Large.is2_up = X->Def.Tpow[isite2 - 1];
   X->Large.is1_spin = sigma1;
   X->Large.is2_spin = sigma2;
   X->Large.is3_spin = sigma3;
   X->Large.is4_spin = sigma4;
   return 0;
 }/*int child_general_int_spin_GetInfo*/
int child_pairlift_spin_GetInfo (int iPairLift, struct BindStruct * X)
Set parameters for the bit operation of spin-pairlift term.
Returns
Always return 0
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Set the pairlift coupling constant (LargeList::tmp_J)
Set the bit mask for computing spin state of both site (LargeList::is1_up, LargeList::is2_up)
Set the bit mask for exchange 2 spins (LargeList::isA_spin)
Definition at line 64 of file mltplySpinCore.c.
References BindStruct::Def, LargeList::is1_up, LargeList::is2_up, LargeList::isA_spin, BindStruct::Large, DefineList::PairLiftCoupling, DefineList::ParaPairLiftCoupling, LargeList::tmp_J, and DefineList::Tpow.
Referenced by makeHam(), and mltplyHalfSpinGC().
   {
   int isite1 = X->Def.PairLiftCoupling[iPairLift][0] + 1;
   int isite2 = X->Def.PairLiftCoupling[iPairLift][1] + 1;
   X->Large.tmp_J = X->Def.ParaPairLiftCoupling[iPairLift];
   X->Large.is1_up = X->Def.Tpow[isite1 - 1];
   X->Large.is2_up = X->Def.Tpow[isite2 - 1];
   X->Large.isA_spin = X->Large.is1_up + X->Large.is2_up;
   return 0;
 }/*int child_pairlift_spin_GetInfo*/
double complex GC_child_CisAisCisAis_spin_element (long unsigned int j, long unsigned int isA_up, long unsigned int isB_up, long unsigned int org_sigma2, long unsigned int org_sigma4, double complex tmp_V, double complex * tmp_v0, double complex * tmp_v1, struct BindStruct * X)
Compute \(c_{is}^\dagger c_{is} c_{is}^\dagger c_{is}\) term of grandcanonical spsin system.
Returns
Fragment of \(\langle v_1 | H_{\rm this}|v_1 \rangle\)
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] isA_up Bit mask for spin 1
[in] isB_up Bit mask for spin 2
[in] org_sigma2 Target for spin 1
[in] org_sigma4 Target for spin 2
[in] tmp_V Coupling constatnt
[in] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[in,out] X
Definition at line 427 of file mltplySpinCore.c.
References BindStruct::Large, LargeList::mode, and X_SpinGC_CisAis().
Referenced by expec_cisajscktalt_SpinGCHalf(), GC_child_general_int_spin(), and makeHam().
   {
   int tmp_sgn;
   double complex dmv = 0;
   double complex dam_pr = 0;
   tmp_sgn = X_SpinGC_CisAis(j, X, isB_up, org_sigma4);
   tmp_sgn *= X_SpinGC_CisAis(j, X, isA_up, org_sigma2);
   if (tmp_sgn != 0) {
     dmv = tmp_v1[j] * tmp_sgn * tmp_V;
     if (X->Large.mode == M_MLTPLY || X->Large.mode == M_CALCSPEC) { // for multply
       tmp_v0[j] += dmv;
     }
     dam_pr = conj(tmp_v1[j]) * dmv;
   }
   return dam_pr;
 }/*double complex GC_child_CisAisCisAis_spin_element*/
double complex GC_child_CisAisCitAiu_spin_element (long unsigned int j, long unsigned int org_sigma2, long unsigned int org_sigma4, long unsigned int isA_up, long unsigned int isB_up, double complex tmp_V, double complex * tmp_v0, double complex * tmp_v1, struct BindStruct * X, long unsigned int * tmp_off)
Compute \(c_{is}^\dagger c_{is} c_{it}^\dagger c_{iu}\) term of grandcanonical spsin system.
Returns
Fragment of \(\langle v_1 | H_{\rm this}|v_1 \rangle\)
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] org_sigma2 Target for spin 1
[in] org_sigma4 Target for spin 2
[in] isA_up Bit mask for spin 1
[in] isB_up Bit mask for spin 2
[in] tmp_V Coupling constatnt
[in] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[in,out] X
[out] tmp_off Index of final wavefunction
Definition at line 460 of file mltplySpinCore.c.
References BindStruct::Large, LargeList::mode, X_SpinGC_CisAis(), and X_SpinGC_CisAit().
Referenced by expec_cisajscktalt_SpinGCHalf(), GC_child_general_int_spin(), and makeHam().
   {
   int tmp_sgn;
   double complex dmv;
   double complex dam_pr = 0 + 0 * I;
   tmp_sgn = X_SpinGC_CisAit(j, X, isB_up, org_sigma4, tmp_off);
   if (tmp_sgn != 0) {
     tmp_sgn *= X_SpinGC_CisAis((*tmp_off + 1), X, isA_up, org_sigma2);
     if (tmp_sgn != 0) {
       dmv = tmp_v1[j] * tmp_sgn * tmp_V;
       if (X->Large.mode == M_MLTPLY || X->Large.mode == M_CALCSPEC) { // for multply
         tmp_v0[*tmp_off + 1] += dmv;
       }
       dam_pr = conj(tmp_v1[*tmp_off + 1]) * dmv;
     }/*if (tmp_sgn != 0)*/
   }/*if (tmp_sgn != 0)*/
   return dam_pr;
 }/*double complex GC_child_CisAisCitAiu_spin_element*/
double complex GC_child_CisAitCiuAiu_spin_element (long unsigned int j, long unsigned int org_sigma2, long unsigned int org_sigma4, long unsigned int isA_up, long unsigned int isB_up, double complex tmp_V, double complex * tmp_v0, double complex * tmp_v1, struct BindStruct * X, long unsigned int * tmp_off)
Compute \(c_{is}^\dagger c_{it} c_{iu}^\dagger c_{iu}\) term of grandcanonical spsin system.
Returns
Fragment of \(\langle v_1 | H_{\rm this}|v_1 \rangle\)
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] org_sigma2 Target for spin 1
[in] org_sigma4 Target for spin 2
[in] isA_up Bit mask for spin 1
[in] isB_up Bit mask for spin 2
[in] tmp_V Coupling constatnt
[in] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[in,out] X
[out] tmp_off Index of final wavefunction
Definition at line 495 of file mltplySpinCore.c.
References BindStruct::Large, LargeList::mode, X_SpinGC_CisAis(), and X_SpinGC_CisAit().
Referenced by expec_cisajscktalt_SpinGCHalf(), GC_child_general_int_spin(), and makeHam().
   {
   int tmp_sgn;
   double complex dmv;
   double complex dam_pr = 0 + 0 * I;
   tmp_sgn = X_SpinGC_CisAis(j, X, isB_up, org_sigma4);
   if (tmp_sgn != 0) {
     tmp_sgn *= X_SpinGC_CisAit(j, X, isA_up, org_sigma2, tmp_off);
     if (tmp_sgn != 0) {
       dmv = tmp_v1[j] * tmp_sgn * tmp_V;
       if (X->Large.mode == M_MLTPLY || X->Large.mode == M_CALCSPEC) { // for multply
         tmp_v0[*tmp_off + 1] += dmv;
       }
       dam_pr = conj(tmp_v1[*tmp_off + 1]) * dmv;
     }/*if (tmp_sgn != 0)*/
   }/*if (tmp_sgn != 0)*/
   return dam_pr;
 }/*double complex GC_child_CisAitCiuAiu_spin_element*/
double complex GC_child_CisAitCiuAiv_spin_element (long unsigned int j, long unsigned int org_sigma2, long unsigned int org_sigma4, long unsigned int isA_up, long unsigned int isB_up, double complex tmp_V, double complex * tmp_v0, double complex * tmp_v1, struct BindStruct * X, long unsigned int * tmp_off_2)
Compute \(c_{is}^\dagger c_{it} c_{iu}^\dagger c_{iv}\) term of grandcanonical spsin system.
Returns
Fragment of \(\langle v_1 | H_{\rm this}|v_1 \rangle\)
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] org_sigma2 Target for spin 1
[in] org_sigma4 Target for spin 2
[in] isA_up Bit mask for spin 1
[in] isB_up Bit mask for spin 2
[in] tmp_V Coupling constatnt
[in] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[in,out] X
[out] tmp_off_2 Index of final wavefunction
Definition at line 530 of file mltplySpinCore.c.
References BindStruct::Large, LargeList::mode, and X_SpinGC_CisAit().
Referenced by expec_cisajscktalt_SpinGCHalf(), GC_child_general_int_spin(), and makeHam().
   {
   int tmp_sgn;
   long unsigned int tmp_off_1;
   double complex dmv;
   double complex dam_pr = 0 + 0 * I;
   tmp_sgn = X_SpinGC_CisAit(j, X, isB_up, org_sigma4, &tmp_off_1);
   if (tmp_sgn != 0) {
     tmp_sgn *= X_SpinGC_CisAit((tmp_off_1 + 1), X, isA_up, org_sigma2, tmp_off_2);
     if (tmp_sgn != 0) {
       dmv = tmp_v1[j] * tmp_sgn * tmp_V;
       if (X->Large.mode == M_MLTPLY || X->Large.mode == M_CALCSPEC) { // for multply
         tmp_v0[*tmp_off_2 + 1] += dmv;
       }
       dam_pr = conj(tmp_v1[*tmp_off_2 + 1]) * dmv;
     }/*if (tmp_sgn != 0)*/
   }/*if (tmp_sgn != 0)*/
   return dam_pr;
 }/*double complex GC_child_CisAitCiuAiv_spin_element*/
double complex GC_child_exchange_spin_element (long unsigned int j, double complex * tmp_v0, double complex * tmp_v1, struct BindStruct * X, long unsigned int * tmp_off)
Multiply Hamiltonian of exchange term of grandcanonical spin system.
Returns
\(\langle v_1 | H_{\rm this}| v_1 \rangle\)
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[out] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[in,out] X
[out] tmp_off Index of final wavefunction
Definition at line 315 of file mltplySpinCore.c.
References LargeList::isA_spin, BindStruct::Large, LargeList::mode, and LargeList::tmp_J.
Referenced by GC_child_exchange_spin(), and makeHam().
   {
   double complex dmv;
   long unsigned int is_up = X->Large.isA_spin;
   double complex tmp_J = X->Large.tmp_J;
   int mode = X->Large.mode;
   long unsigned int list_1_j, list_1_off;
   double complex dam_pr = 0;
   list_1_j = j - 1;
   long unsigned int ibit_tmp;
   ibit_tmp = (list_1_j & is_up);
   if (ibit_tmp == 0 || ibit_tmp == is_up) {
     return dam_pr;
   }
   else {
     list_1_off = list_1_j ^ is_up;
     *tmp_off = list_1_off;
     dmv = tmp_J * tmp_v1[j];
     if (mode == M_MLTPLY) {
       tmp_v0[list_1_off + 1] += dmv;
     }
     dam_pr += dmv * conj(tmp_v1[list_1_off + 1]);
     return dam_pr;
   }
 }/*double complex GC_child_exchange_spin_element*/
double complex GC_child_pairlift_spin_element (long unsigned int j, double complex * tmp_v0, double complex * tmp_v1, struct BindStruct * X, long unsigned int * tmp_off)
Multiply Hamiltonian of pairlift term of grandcanonical spin system.
Returns
\(\langle v_1 | H_{\rm this}| v_1 \rangle\)
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[out] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[in,out] X
[out] tmp_off Index of final wavefunction
Definition at line 353 of file mltplySpinCore.c.
References LargeList::isA_spin, BindStruct::Large, LargeList::mode, and LargeList::tmp_J.
Referenced by GC_child_pairlift_spin(), and makeHam().
   {
   double complex dmv;
   long unsigned int is_up = X->Large.isA_spin;
   double complex tmp_J = X->Large.tmp_J;
   int mode = X->Large.mode;
   double complex dam_pr = 0;
   long unsigned int list_1_off;
   long unsigned int list_1_j = j - 1;
   long unsigned int ibit_tmp;
   //ibit_tmp = ((list_1_j & is1_up) / is1_up) ^ ((list_1_j & is2_up) / is2_up);
   ibit_tmp = (list_1_j & is_up);
   if (ibit_tmp == 0 || ibit_tmp == is_up) {
     list_1_off = list_1_j ^ is_up; //Change: ++ -> -- or -- -> ++
     *tmp_off = list_1_off;
     dmv = tmp_J * tmp_v1[j];//* ibit_tmp;
     if (mode == M_MLTPLY) {
       tmp_v0[list_1_off + 1] += dmv;
     }
     dam_pr += dmv * conj(tmp_v1[list_1_off + 1]);
     return dam_pr;
   }
   else {
     return dam_pr;
   }
 }/*double complex GC_child_pairlift_spin_element*/
int X_child_exchange_spin_element (long unsigned int j, struct BindStruct * X, long unsigned int isA_up, long unsigned int isB_up, long unsigned int sigmaA, long unsigned int sigmaB, long unsigned int * tmp_off)
Compute index of final wavefunction associated to spin-exchange term.
Returns
1 if spin of site 1 is sigmaA and spin of site 2 is sigmaB. 0 if not.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in,out] X
[in] isA_up Bit mask for spin 1
[in] isB_up Bit mask for spin 2
[in] sigmaA Target of spin 1
[in] sigmaB Target of spin 2
[out] tmp_off Index of final wavefunction
Definition at line 240 of file mltplySpinCore.c.
References GetOffComp(), LargeList::ihfbit, LargeList::ilft, LargeList::irght, BindStruct::Large, list_1, list_2_1, and list_2_2.
Referenced by child_general_int_spin(), expec_cisajscktalt_SpinHalf(), and makeHam().
   {
   long unsigned int iexchg, off;
   long unsigned int irght = X->Large.irght;
   long unsigned int ilft = X->Large.ilft;
   long unsigned int ihfbit = X->Large.ihfbit;
   long unsigned int ibit_tmp_A, ibit_tmp_B;
   ibit_tmp_A = ((list_1[j] & isA_up) / isA_up);
   ibit_tmp_B = ((list_1[j] & isB_up) / isB_up);
   if (ibit_tmp_A == sigmaA && ibit_tmp_B == sigmaB) {
     iexchg = list_1[j] ^ (isA_up + isB_up);
     GetOffComp(list_2_1, list_2_2, iexchg, irght, ilft, ihfbit, &off);
     *tmp_off = off;
     return 1;
   }
   else {
     *tmp_off = 0; // just tentative
     return 0;
   }
 }/*int X_child_exchange_spin_element*/
int X_Spin_CisAis (long unsigned int j, struct BindStruct * X, long unsigned int is1_spin, long unsigned int sigma1)
Compute the spin state with bit mask is1_spin.
Returns
1 if the spin state with bit mask is1_spin is sigma1, 0 for the other.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of wavefunction
[in,out] X
[in] is1_spin Bit mask
[in] sigma1 Target spin state
Definition at line 167 of file mltplySpinCore.c.
References list_1.
Referenced by child_CisAisCisAis_spin_element(), expec_cisajs_SpinHalf(), expec_cisajscktalt_SpinHalf(), GetPairExcitedStateHalfSpin(), makeHam(), SetDiagonalInterAll(), and SetDiagonalTEInterAll().
   {
   int A_ibit_tmp;
   // off = j
   A_ibit_tmp = ((list_1[j] & is1_spin) / is1_spin) ^ (1 - sigma1);
   return A_ibit_tmp;
 }/*int X_Spin_CisAis*/
int X_Spin_CisAit (long unsigned int j, struct BindStruct * X, long unsigned int is1_spin, long unsigned int sigma2, long unsigned int * list_1_Org_, long unsigned int * list_2_1_, long unsigned int * list_2_2_, long unsigned int * tmp_off)
Compute index of final wavefunction by \(c_{is}^\dagger c_{it}\) term.
Returns
1 if bit-mask is1_spin is sigma2, 0 for the other
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in,out] X
[in] is1_spin Bit mask for computing spin state
[in] sigma2 Spin state at site 2
[in] list_1_Org_ Similar to list_1
[in] list_2_1_ Similar to list_2_1
[in] list_2_2_ Similar to list_2_2
[out] tmp_off Index of final wavefunction
Definition at line 139 of file mltplySpinCore.c.
References GetOffComp(), LargeList::ihfbit, LargeList::ilft, LargeList::irght, BindStruct::Large, and X_SpinGC_CisAit().
Referenced by GetPairExcitedStateHalfSpin().
   {
   long unsigned int list_1_j;
   long unsigned int off;
   list_1_j = list_1_Org_[j];
   if (X_SpinGC_CisAit(list_1_j + 1, X, is1_spin, sigma2, &off) != 0) {
     GetOffComp(list_2_1_, list_2_2_, off, X->Large.irght, X->Large.ilft, X->Large.ihfbit, tmp_off);
     return 1;
   }
   else {
     *tmp_off = 0;
     return 0;
   }
 }/*int X_Spin_CisAit*/
int X_SpinGC_CisAis (long unsigned int j, struct BindStruct * X, long unsigned int is1_spin, long unsigned int sigma1)
Compute the grandcanonical spin state with bit mask is1_spin.
Returns
1 if the spin state with bit mask is1_spin is sigma1, 0 for the other.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of wavefunction
[in,out] X
[in] is1_spin Bit mask
[in] sigma1 Target spin state
Definition at line 184 of file mltplySpinCore.c.
Referenced by expec_cisajs_SpinGCHalf(), expec_cisajs_SpinHalf(), expec_cisajscktalt_SpinHalf(), GC_child_CisAisCisAis_spin_element(), GC_child_CisAisCitAiu_spin_element(), GC_child_CisAitCiuAiu_spin_element(), GetPairExcitedStateHalfSpin(), GetPairExcitedStateHalfSpinGC(), SetDiagonalInterAll(), SetDiagonalTEInterAll(), totalspin_Spin(), totalspin_SpinGC(), X_GC_child_CisAisCjuAju_spin_MPIdouble(), X_GC_child_CisAisCjuAju_spin_MPIsingle(), X_GC_child_CisAisCjuAjv_spin_MPIdouble(), and X_GC_child_CisAitCjuAju_spin_MPIdouble().
   {
   int A_ibit_tmp;
   long unsigned int list_1_j;
   // off = j
   list_1_j = j - 1;
   A_ibit_tmp = ((list_1_j & is1_spin) / is1_spin) ^ (1 - sigma1);
   return A_ibit_tmp;
 }/*int X_SpinGC_CisAis*/
int X_SpinGC_CisAit (long unsigned int j, struct BindStruct * X, long unsigned int is1_spin, long unsigned int sigma2, long unsigned int * tmp_off)
Compute index of final wavefunction by \(c_{is}^\dagger c_{it}\) term (grandcanonical).
Returns
1 if bit-mask is1_spin is sigma2, 0 for the other
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of wavefunction
[in,out] X
[in] is1_spin Bit mask for computing spin state
[in] sigma2 Spin state at site 2
[out] tmp_off Index of final wavefunction
Definition at line 204 of file mltplySpinCore.c.
Referenced by expec_cisajs_SpinGCHalf(), GC_child_CisAisCitAiu_spin_element(), GC_child_CisAitCiuAiu_spin_element(), GC_child_CisAitCiuAiv_spin_element(), GetPairExcitedStateHalfSpinGC(), makeHam(), mltplyHalfSpinGC(), X_GC_child_CisAitCiuAiv_spin_MPIsingle(), and X_Spin_CisAit().
   {
   long unsigned int list_1_j, ibit_tmp_1;
   list_1_j = j - 1;
   ibit_tmp_1 = list_1_j & is1_spin;
   if (ibit_tmp_1 == 0 && sigma2 == 0) {    // down -> up
     *tmp_off = list_1_j + is1_spin;
     return 1;
   }
   else if (ibit_tmp_1 != 0 && sigma2 == 1) { // up -> down
     *tmp_off = list_1_j - is1_spin;
     return 1;
   }
   else {
     *tmp_off = 0;
     return 0;
   }
 }/*int X_SpinGC_CisAit*/