HΦ: mltplyMPISpin.c File Reference
mltplyMPISpin.c File Reference
Functions for spin Hamiltonian + MPI.
#include "mpi.h"
#include "Common.h"
#include "mltplyCommon.h"
#include "bitcalc.h"
#include "wrapperMPI.h"
#include "mltplyMPISpin.h"
#include "mltplyMPISpinCore.h"
Functions
void child_general_int_spin_MPIdouble (unsigned long int i_int, struct BindStruct *X, double complex *tmp_v0, double complex *tmp_v1)
Exchange term in Spin model When both site1 and site2 are in the inter process region.
double complex X_child_general_int_spin_MPIdouble (int org_isite1, int org_ispin1, int org_ispin2, int org_isite3, int org_ispin3, int org_ispin4, double complex tmp_J, struct BindStruct *X, double complex *tmp_v0, double complex *tmp_v1)
Exchange term in Spin model When both site1 and site2 are in the inter process region.
double complex X_child_general_int_spin_TotalS_MPIdouble (int org_isite1, int org_isite3, struct BindStruct *X, double complex *tmp_v0, double complex *tmp_v1)
Exchange term in Spin model When both site1 and site2 are in the inter process region.
void child_general_int_spin_MPIsingle (unsigned long int i_int, struct BindStruct *X, double complex *tmp_v0, double complex *tmp_v1)
Exchange term in Spin model When only site2 is in the inter process region.
double complex X_child_general_int_spin_MPIsingle (int org_isite1, int org_ispin1, int org_ispin2, int org_isite3, int org_ispin3, int org_ispin4, double complex tmp_J, struct BindStruct *X, double complex *tmp_v0, double complex *tmp_v1)
void GC_child_general_int_spin_MPIdouble (unsigned long int i_int, struct BindStruct *X, double complex *tmp_v0, double complex *tmp_v1)
General interaction term in the Spin model + GC When both site1 and site2 are in the inter process region.
void GC_child_general_int_spin_MPIsingle (unsigned long int i_int, struct BindStruct *X, double complex *tmp_v0, double complex *tmp_v1)
General interaction term in the Spin model + GC When both site1 and site2 are in the inter process region.
void GC_child_general_int_GeneralSpin_MPIdouble (unsigned long int i_int, struct BindStruct *X, double complex *tmp_v0, double complex *tmp_v1)
General interaction term in the Spin model + GC When both site1 and site2 are in the inter process region.
void GC_child_general_int_GeneralSpin_MPIsingle (unsigned long int i_int, struct BindStruct *X, double complex *tmp_v0, double complex *tmp_v1)
General interaction term in the Spin model + GC When both site1 and site2 are in the inter process region.
void child_general_int_GeneralSpin_MPIdouble (unsigned long int i_int, struct BindStruct *X, double complex *tmp_v0, double complex *tmp_v1)
General interaction term in the Spin model + GC When both site1 and site2 are in the inter process region.
void child_general_int_GeneralSpin_MPIsingle (unsigned long int i_int, struct BindStruct *X, double complex *tmp_v0, double complex *tmp_v1)
General interaction term in the Spin model + GC When both site1 and site2 are in the inter process region.
Detailed Description
Functions for spin Hamiltonian + MPI.
Definition in file mltplyMPISpin.c.
Function Documentation
void child_general_int_GeneralSpin_MPIdouble (unsigned long int i_int, struct BindStruct * X, double complex * tmp_v0, double complex * tmp_v1)
General interaction term in the Spin model + GC When both site1 and site2 are in the inter process region.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] i_int Interaction ID
[in,out] X
[out] tmp_v0 Result v0 = H v1
[in] tmp_v1 v0 = H v1
Definition at line 460 of file mltplyMPISpin.c.
References BindStruct::Def, DefineList::InterAll_OffDiagonal, BindStruct::Large, DefineList::ParaInterAll_OffDiagonal, LargeList::prdct, and X_child_CisAitCjuAjv_GeneralSpin_MPIdouble().
Referenced by mltplyGeneralSpin().
  {
     double complex dam_pr;
     dam_pr = X_child_CisAitCjuAjv_GeneralSpin_MPIdouble(
       X->Def.InterAll_OffDiagonal[i_int][0], X->Def.InterAll_OffDiagonal[i_int][1],
       X->Def.InterAll_OffDiagonal[i_int][3], X->Def.InterAll_OffDiagonal[i_int][4],
       X->Def.InterAll_OffDiagonal[i_int][5], X->Def.InterAll_OffDiagonal[i_int][7],
       X->Def.ParaInterAll_OffDiagonal[i_int], X, tmp_v0, tmp_v1);
     X->Large.prdct += dam_pr;
 }/*void GC_child_general_int_spin_MPIdouble*/
void child_general_int_GeneralSpin_MPIsingle (unsigned long int i_int, struct BindStruct * X, double complex * tmp_v0, double complex * tmp_v1)
General interaction term in the Spin model + GC When both site1 and site2 are in the inter process region.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] i_int Interaction ID
[in,out] X
[out] tmp_v0 Result v0 = H v1
[in] tmp_v1 v0 = H v1
Definition at line 480 of file mltplyMPISpin.c.
References BindStruct::Def, DefineList::InterAll_OffDiagonal, BindStruct::Large, DefineList::ParaInterAll_OffDiagonal, LargeList::prdct, and X_child_CisAitCjuAjv_GeneralSpin_MPIsingle().
Referenced by mltplyGeneralSpin().
  {
   double complex dam_pr;
   dam_pr = X_child_CisAitCjuAjv_GeneralSpin_MPIsingle(
     X->Def.InterAll_OffDiagonal[i_int][0], X->Def.InterAll_OffDiagonal[i_int][1],
     X->Def.InterAll_OffDiagonal[i_int][3], X->Def.InterAll_OffDiagonal[i_int][4],
     X->Def.InterAll_OffDiagonal[i_int][5], X->Def.InterAll_OffDiagonal[i_int][7],
     X->Def.ParaInterAll_OffDiagonal[i_int], X, tmp_v0, tmp_v1);
   X->Large.prdct += dam_pr;
 }/*void GC_child_general_int_spin_MPIsingle*/
void child_general_int_spin_MPIdouble (unsigned long int i_int, struct BindStruct * X, double complex * tmp_v0, double complex * tmp_v1)
Exchange term in Spin model When both site1 and site2 are in the inter process region.
Author
Mitsuaki Kawamura (The University of Tokyo)
Add \(\langle v_1| H_{\rm this} | v_1 \rangle\) to LargeList::prdct
Parameters
[in] i_int Interaction ID
[in,out] X
[out] tmp_v0 Result v0 = H v1
[in] tmp_v1 v0 = H v1
Definition at line 35 of file mltplyMPISpin.c.
References BindStruct::Def, DefineList::InterAll_OffDiagonal, BindStruct::Large, DefineList::ParaInterAll_OffDiagonal, LargeList::prdct, and X_child_general_int_spin_MPIdouble().
Referenced by mltplyHalfSpin().
  {
 #ifdef MPI
   double complex dam_pr = 0;
   dam_pr = X_child_general_int_spin_MPIdouble(
     (int)X->Def.InterAll_OffDiagonal[i_int][0], (int)X->Def.InterAll_OffDiagonal[i_int][1],
     (int)X->Def.InterAll_OffDiagonal[i_int][3], (int)X->Def.InterAll_OffDiagonal[i_int][4],
     (int)X->Def.InterAll_OffDiagonal[i_int][5], (int)X->Def.InterAll_OffDiagonal[i_int][7],
     X->Def.ParaInterAll_OffDiagonal[i_int], X, tmp_v0, tmp_v1);
   X->Large.prdct += dam_pr;
 #endif
 }/*void child_general_int_spin_MPIdouble*/
void child_general_int_spin_MPIsingle (unsigned long int i_int, struct BindStruct * X, double complex * tmp_v0, double complex * tmp_v1)
Exchange term in Spin model When only site2 is in the inter process region.
Returns
\(\langle v_1| H_{\rm this} | v_1 \rangle\)
Author
Mitsuaki Kawamura (The University of Tokyo)
Add \(\langle v_1| H_{\rm this} | v_1 \rangle\) to LargeList::prdct
Parameters
[in] i_int Interaction ID
[in,out] X
[out] tmp_v0 Result v0 = H v1
[in] tmp_v1 v0 = H v1
Definition at line 192 of file mltplyMPISpin.c.
References BindStruct::Def, DefineList::InterAll_OffDiagonal, BindStruct::Large, DefineList::ParaInterAll_OffDiagonal, LargeList::prdct, and X_child_general_int_spin_MPIsingle().
Referenced by mltplyHalfSpin().
  {
 #ifdef MPI
   double complex dam_pr = 0;
   dam_pr = X_child_general_int_spin_MPIsingle(
     (int)X->Def.InterAll_OffDiagonal[i_int][0], (int)X->Def.InterAll_OffDiagonal[i_int][1],
     (int)X->Def.InterAll_OffDiagonal[i_int][3], (int)X->Def.InterAll_OffDiagonal[i_int][4],
     (int)X->Def.InterAll_OffDiagonal[i_int][5], (int)X->Def.InterAll_OffDiagonal[i_int][7],
     X->Def.ParaInterAll_OffDiagonal[i_int], X, tmp_v0, tmp_v1);
   X->Large.prdct += dam_pr;
 #endif
 }/*void child_general_int_spin_MPIsingle*/
void GC_child_general_int_GeneralSpin_MPIdouble (unsigned long int i_int, struct BindStruct * X, double complex * tmp_v0, double complex * tmp_v1)
General interaction term in the Spin model + GC When both site1 and site2 are in the inter process region.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] i_int Interaction ID
[in,out] X
[out] tmp_v0 Result v0 = H v1
[in] tmp_v1 v0 = H v1
Definition at line 382 of file mltplyMPISpin.c.
References BindStruct::Def, DefineList::InterAll_OffDiagonal, BindStruct::Large, DefineList::ParaInterAll_OffDiagonal, LargeList::prdct, X_GC_child_CisAisCjuAjv_GeneralSpin_MPIdouble(), X_GC_child_CisAitCjuAju_GeneralSpin_MPIsingle(), and X_GC_child_CisAitCjuAjv_GeneralSpin_MPIdouble().
Referenced by mltplyGeneralSpinGC().
  {
 #ifdef MPI
   double complex dam_pr;
   // MPI_Status statusMPI;
   if (X->Def.InterAll_OffDiagonal[i_int][1] == X->Def.InterAll_OffDiagonal[i_int][3] &&
       X->Def.InterAll_OffDiagonal[i_int][5] != X->Def.InterAll_OffDiagonal[i_int][7]) {
     dam_pr = X_GC_child_CisAisCjuAjv_GeneralSpin_MPIdouble(
       X->Def.InterAll_OffDiagonal[i_int][0], X->Def.InterAll_OffDiagonal[i_int][1],
       X->Def.InterAll_OffDiagonal[i_int][4], X->Def.InterAll_OffDiagonal[i_int][5],
       X->Def.InterAll_OffDiagonal[i_int][7], X->Def.ParaInterAll_OffDiagonal[i_int], X, tmp_v0, tmp_v1);
   }
   else if (X->Def.InterAll_OffDiagonal[i_int][1] != X->Def.InterAll_OffDiagonal[i_int][3] &&
            X->Def.InterAll_OffDiagonal[i_int][5] == X->Def.InterAll_OffDiagonal[i_int][7]) {
     dam_pr = X_GC_child_CisAitCjuAju_GeneralSpin_MPIsingle(
       X->Def.InterAll_OffDiagonal[i_int][0], X->Def.InterAll_OffDiagonal[i_int][1],
       X->Def.InterAll_OffDiagonal[i_int][3], X->Def.InterAll_OffDiagonal[i_int][4],
       X->Def.InterAll_OffDiagonal[i_int][5], X->Def.ParaInterAll_OffDiagonal[i_int], X, tmp_v0, tmp_v1);
   }
   else {
     dam_pr = X_GC_child_CisAitCjuAjv_GeneralSpin_MPIdouble(
       X->Def.InterAll_OffDiagonal[i_int][0], X->Def.InterAll_OffDiagonal[i_int][1],
       X->Def.InterAll_OffDiagonal[i_int][3], X->Def.InterAll_OffDiagonal[i_int][4],
       X->Def.InterAll_OffDiagonal[i_int][5], X->Def.InterAll_OffDiagonal[i_int][7],
       X->Def.ParaInterAll_OffDiagonal[i_int], X, tmp_v0, tmp_v1);
   }
   X->Large.prdct += dam_pr;
 #endif
 }/*void GC_child_general_int_spin_MPIdouble*/
void GC_child_general_int_GeneralSpin_MPIsingle (unsigned long int i_int, struct BindStruct * X, double complex * tmp_v0, double complex * tmp_v1)
General interaction term in the Spin model + GC When both site1 and site2 are in the inter process region.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] i_int Interaction ID
[in,out] X
[out] tmp_v0 Result v0 = H v1
[in] tmp_v1 v0 = H v1
Definition at line 421 of file mltplyMPISpin.c.
References BindStruct::Def, DefineList::InterAll_OffDiagonal, BindStruct::Large, DefineList::ParaInterAll_OffDiagonal, LargeList::prdct, X_GC_child_CisAisCjuAjv_GeneralSpin_MPIsingle(), X_GC_child_CisAitCjuAju_GeneralSpin_MPIsingle(), and X_GC_child_CisAitCjuAjv_GeneralSpin_MPIsingle().
Referenced by mltplyGeneralSpinGC().
  {
 #ifdef MPI
   double complex dam_pr;
   if (X->Def.InterAll_OffDiagonal[i_int][1] == X->Def.InterAll_OffDiagonal[i_int][3] &&
       X->Def.InterAll_OffDiagonal[i_int][5] != X->Def.InterAll_OffDiagonal[i_int][7]) {
     dam_pr = X_GC_child_CisAisCjuAjv_GeneralSpin_MPIsingle(
       X->Def.InterAll_OffDiagonal[i_int][0], X->Def.InterAll_OffDiagonal[i_int][1],
       X->Def.InterAll_OffDiagonal[i_int][4], X->Def.InterAll_OffDiagonal[i_int][5],
       X->Def.InterAll_OffDiagonal[i_int][7], X->Def.ParaInterAll_OffDiagonal[i_int], X, tmp_v0, tmp_v1);
   }
   else if (X->Def.InterAll_OffDiagonal[i_int][1] != X->Def.InterAll_OffDiagonal[i_int][3] &&
            X->Def.InterAll_OffDiagonal[i_int][5] == X->Def.InterAll_OffDiagonal[i_int][7]) {
     dam_pr = X_GC_child_CisAitCjuAju_GeneralSpin_MPIsingle(
       X->Def.InterAll_OffDiagonal[i_int][0], X->Def.InterAll_OffDiagonal[i_int][1],
       X->Def.InterAll_OffDiagonal[i_int][3], X->Def.InterAll_OffDiagonal[i_int][4],
       X->Def.InterAll_OffDiagonal[i_int][5], X->Def.ParaInterAll_OffDiagonal[i_int], X, tmp_v0, tmp_v1);
     }
   else {
     dam_pr = X_GC_child_CisAitCjuAjv_GeneralSpin_MPIsingle(
       X->Def.InterAll_OffDiagonal[i_int][0], X->Def.InterAll_OffDiagonal[i_int][1],
       X->Def.InterAll_OffDiagonal[i_int][3], X->Def.InterAll_OffDiagonal[i_int][4],
       X->Def.InterAll_OffDiagonal[i_int][5], X->Def.InterAll_OffDiagonal[i_int][7],
       X->Def.ParaInterAll_OffDiagonal[i_int], X, tmp_v0, tmp_v1);
   }
   X->Large.prdct += dam_pr;
 #endif
 }/*void GC_child_general_int_spin_MPIsingle*/
void GC_child_general_int_spin_MPIdouble (unsigned long int i_int, struct BindStruct * X, double complex * tmp_v0, double complex * tmp_v1)
General interaction term in the Spin model + GC When both site1 and site2 are in the inter process region.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] i_int Interaction ID
[in,out] X
[out] tmp_v0 Result v0 = H v1
[in] tmp_v1 v0 = H v1
Definition at line 336 of file mltplyMPISpin.c.
References BindStruct::Def, GC_child_CisAisCjuAjv_spin_MPIdouble(), GC_child_CisAitCiuAiv_spin_MPIdouble(), GC_child_CisAitCjuAju_spin_MPIdouble(), and DefineList::InterAll_OffDiagonal.
Referenced by mltplyHalfSpinGC().
  {
   if (X->Def.InterAll_OffDiagonal[i_int][1] == X->Def.InterAll_OffDiagonal[i_int][3] &&
       X->Def.InterAll_OffDiagonal[i_int][5] != X->Def.InterAll_OffDiagonal[i_int][7]) {
     GC_child_CisAisCjuAjv_spin_MPIdouble(i_int, X, tmp_v0, tmp_v1);
   }
   else if (X->Def.InterAll_OffDiagonal[i_int][1] != X->Def.InterAll_OffDiagonal[i_int][3] &&
            X->Def.InterAll_OffDiagonal[i_int][5] == X->Def.InterAll_OffDiagonal[i_int][7]) {
     GC_child_CisAitCjuAju_spin_MPIdouble(i_int, X, tmp_v0, tmp_v1);
   }
   else {
     GC_child_CisAitCiuAiv_spin_MPIdouble(i_int, X, tmp_v0, tmp_v1);
   }
 }/*void GC_child_general_int_spin_MPIdouble*/
void GC_child_general_int_spin_MPIsingle (unsigned long int i_int, struct BindStruct * X, double complex * tmp_v0, double complex * tmp_v1)
General interaction term in the Spin model + GC When both site1 and site2 are in the inter process region.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] i_int Interaction ID
[in,out] X
[out] tmp_v0 Result v0 = H v1
[in] tmp_v1 v0 = H v1
Definition at line 359 of file mltplyMPISpin.c.
References BindStruct::Def, GC_child_CisAisCjuAjv_spin_MPIsingle(), GC_child_CisAitCiuAiv_spin_MPIsingle(), GC_child_CisAitCjuAju_spin_MPIsingle(), and DefineList::InterAll_OffDiagonal.
Referenced by mltplyHalfSpinGC().
  {
   if (X->Def.InterAll_OffDiagonal[i_int][1] == X->Def.InterAll_OffDiagonal[i_int][3] &&
       X->Def.InterAll_OffDiagonal[i_int][5] != X->Def.InterAll_OffDiagonal[i_int][7]) {
     GC_child_CisAisCjuAjv_spin_MPIsingle(i_int, X, tmp_v0, tmp_v1);
   }
   else if (X->Def.InterAll_OffDiagonal[i_int][1] != X->Def.InterAll_OffDiagonal[i_int][3] &&
            X->Def.InterAll_OffDiagonal[i_int][5] == X->Def.InterAll_OffDiagonal[i_int][7]) {
     GC_child_CisAitCjuAju_spin_MPIsingle(i_int, X, tmp_v0, tmp_v1);
   }
   else {
     GC_child_CisAitCiuAiv_spin_MPIsingle(i_int, X, tmp_v0, tmp_v1);
   }
 }/*void GC_child_general_int_spin_MPIsingle*/
double complex X_child_general_int_spin_MPIdouble (int org_isite1, int org_ispin1, int org_ispin2, int org_isite3, int org_ispin3, int org_ispin4, double complex tmp_J, struct BindStruct * X, double complex * tmp_v0, double complex * tmp_v1)
Exchange term in Spin model When both site1 and site2 are in the inter process region.
Returns
\(\langle v_1| H_{\rm this} | v_1 \rangle\)
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] org_isite1 Site 1
[in] org_ispin1 Spin 1
[in] org_ispin2 Spin 2
[in] org_isite3 Site 3
[in] org_ispin3 Spin 3
[in] org_ispin4 Spin 4
[in] tmp_J Copupling constatnt
[in,out] X
[in,out] tmp_v0 \({\bf v}_0=H {\bf v}_1\)
[in] tmp_v1 Vector to be producted
Definition at line 61 of file mltplyMPISpin.c.
References BindStruct::Check, BindStruct::Def, exitMPI(), GetOffComp(), CheckList::idim_max, LargeList::ihfbit, LargeList::ilft, LargeList::irght, BindStruct::Large, list_1, list_1buf, list_2_1, list_2_2, LargeList::mode, myrank, DefineList::Tpow, and v1buf.
Referenced by child_general_int_spin_MPIdouble(), expec_cisajscktalt_SpinHalf(), and mltplyHalfSpin().
   {
 #ifdef MPI
   int mask1, mask2, state1, state2, ierr, origin;
   unsigned long int idim_max_buf, j, ioff;
   MPI_Status statusMPI;
   double complex Jint, dmv, dam_pr;
   mask1 = (int)X->Def.Tpow[org_isite1];
   mask2 = (int)X->Def.Tpow[org_isite3];
   origin = myrank ^ (mask1 + mask2);
   state1 = (origin & mask1) / mask1;
   state2 = (origin & mask2) / mask2;
   if (state1 == org_ispin2 && state2 == org_ispin4) {
     Jint = tmp_J;
   }
   else if (state1 == org_ispin1 && state2 == org_ispin3) {
     Jint = conj(tmp_J);
     if (X->Large.mode == M_CORR || X->Large.mode == M_CALCSPEC) {
       Jint = 0;
     }
   }
   else return 0;
   ierr = MPI_Sendrecv(&X->Check.idim_max, 1, MPI_UNSIGNED_LONG, origin, 0,
                       &idim_max_buf,      1, MPI_UNSIGNED_LONG, origin, 0, MPI_COMM_WORLD, &statusMPI);
   if (ierr != 0) exitMPI(-1);
   ierr = MPI_Sendrecv(list_1, X->Check.idim_max + 1, MPI_UNSIGNED_LONG, origin, 0,
                       list_1buf,   idim_max_buf + 1, MPI_UNSIGNED_LONG, origin, 0, MPI_COMM_WORLD, &statusMPI);
   if (ierr != 0) exitMPI(-1);
   ierr = MPI_Sendrecv(tmp_v1, X->Check.idim_max + 1, MPI_DOUBLE_COMPLEX, origin, 0,
                        v1buf,      idim_max_buf + 1, MPI_DOUBLE_COMPLEX, origin, 0, MPI_COMM_WORLD, &statusMPI);
   if (ierr != 0) exitMPI(-1);
   dam_pr = 0.0;
   if (X->Large.mode == M_MLTPLY || X->Large.mode == M_CALCSPEC) {
 #pragma omp parallel for default(none) reduction(+:dam_pr) private(j, dmv, ioff) \
   firstprivate(idim_max_buf, Jint, X) shared(list_2_1, list_2_2, list_1buf, v1buf, tmp_v1, tmp_v0)
     for (j = 1; j <= idim_max_buf; j++) {
       GetOffComp(list_2_1, list_2_2, list_1buf[j],
         X->Large.irght, X->Large.ilft, X->Large.ihfbit, &ioff);
       dmv = Jint * v1buf[j];
       tmp_v0[ioff] += dmv;
       dam_pr += conj(tmp_v1[ioff]) * dmv;
     }/*for (j = 1; j <= idim_max_buf; j++)*/
   }/*if (X->Large.mode == M_MLTPLY || X->Large.mode == M_CALCSPEC)*/
   else {
 #pragma omp parallel for default(none) reduction(+:dam_pr) private(j, dmv, ioff) \
   firstprivate(idim_max_buf, Jint, X) shared(list_2_1, list_2_2, list_1buf, v1buf, tmp_v1, tmp_v0)
     for (j = 1; j <= idim_max_buf; j++) {
       GetOffComp(list_2_1, list_2_2, list_1buf[j],
         X->Large.irght, X->Large.ilft, X->Large.ihfbit, &ioff);
       dmv = Jint * v1buf[j];
       dam_pr += conj(tmp_v1[ioff]) * dmv;
     }/*for (j = 1; j <= idim_max_buf; j++)*/
   }/*if (! (X->Large.mode == M_MLTPLY || X->Large.mode == M_CALCSPEC))*/
   return dam_pr;
 #endif
 }/*double complex X_child_general_int_spin_MPIdouble*/
double complex X_child_general_int_spin_MPIsingle (int org_isite1, int org_ispin1, int org_ispin2, int org_isite3, int org_ispin3, int org_ispin4, double complex tmp_J, struct BindStruct * X, double complex * tmp_v0, double complex * tmp_v1)
Parameters
[in] org_isite1 Site 1
[in] org_ispin1 Spin 1
[in] org_ispin2 Spin 2
[in] org_isite3 Site 3
[in] org_ispin3 Spin 3
[in] org_ispin4 Spin 4
[in] tmp_J Copupling constatnt
[in,out] X
[in,out] tmp_v0 \({\bf v}_0=H {\bf v}_1\)
[in] tmp_v1 Vector to be producted
Definition at line 218 of file mltplyMPISpin.c.
References BindStruct::Check, BindStruct::Def, exitMPI(), GetOffComp(), CheckList::idim_max, LargeList::ihfbit, LargeList::ilft, LargeList::irght, BindStruct::Large, list_1, list_1buf, list_2_1, list_2_2, LargeList::mode, myrank, DefineList::Tpow, and v1buf.
Referenced by child_general_int_spin_MPIsingle(), expec_cisajscktalt_SpinHalf(), mltplyHalfSpin(), and totalspin_Spin().
   {
 #ifdef MPI
   int mask2, state2, ierr, origin;
   unsigned long int mask1, idim_max_buf, j, ioff, state1, jreal, state1check;
   MPI_Status statusMPI;
   double complex Jint, dmv, dam_pr;
   /*
   Prepare index in the inter PE
   */
   mask2 = (int)X->Def.Tpow[org_isite3];
   origin = myrank ^ mask2;
   state2 = (origin & mask2) / mask2;
   if (state2 == org_ispin4) {
     state1check = (unsigned long int) org_ispin2;
     Jint = tmp_J;
   }
   else if (state2 == org_ispin3) {
     state1check = (unsigned long int) org_ispin1;
     Jint = conj(tmp_J);
     if (X->Large.mode == M_CORR || X->Large.mode == M_CALCSPEC) {
       Jint = 0;
     }
   }
   else return 0;
   ierr = MPI_Sendrecv(&X->Check.idim_max, 1, MPI_UNSIGNED_LONG, origin, 0,
                       &idim_max_buf,      1, MPI_UNSIGNED_LONG, origin, 0,
                       MPI_COMM_WORLD, &statusMPI);
   if (ierr != 0) exitMPI(-1);
   ierr = MPI_Sendrecv(list_1, X->Check.idim_max + 1, MPI_UNSIGNED_LONG, origin, 0,
                       list_1buf,   idim_max_buf + 1, MPI_UNSIGNED_LONG, origin, 0,
                       MPI_COMM_WORLD, &statusMPI);
   if (ierr != 0) exitMPI(-1);
   ierr = MPI_Sendrecv(tmp_v1, X->Check.idim_max + 1, MPI_DOUBLE_COMPLEX, origin, 0,
                       v1buf,       idim_max_buf + 1, MPI_DOUBLE_COMPLEX, origin, 0,
                       MPI_COMM_WORLD, &statusMPI);
   if (ierr != 0) exitMPI(-1);
   /*
   Index in the intra PE
   */
   mask1 = X->Def.Tpow[org_isite1];
   dam_pr = 0.0;
   if (X->Large.mode == M_MLTPLY || X->Large.mode == M_CALCSPEC) {
 #pragma omp parallel for default(none) reduction(+:dam_pr) private(j, dmv, ioff, jreal, state1) \
 firstprivate(idim_max_buf, Jint, X, mask1, state1check, org_isite1) \
 shared(list_2_1, list_2_2, list_1buf, v1buf, tmp_v1, tmp_v0)
     for (j = 1; j <= idim_max_buf; j++) {
       jreal = list_1buf[j];
       state1 = (jreal & mask1) / mask1;
       if (state1 == state1check) {
         GetOffComp(list_2_1, list_2_2, jreal ^ mask1,
           X->Large.irght, X->Large.ilft, X->Large.ihfbit, &ioff);
         dmv = Jint * v1buf[j];
         tmp_v0[ioff] += dmv;
         dam_pr += conj(tmp_v1[ioff]) * dmv;
       }
     }
   }
   else if (X->Large.mode == M_TOTALS) {
 #pragma omp parallel for default(none) reduction(+:dam_pr) private(j, dmv, ioff, jreal, state1) \
 firstprivate(idim_max_buf, Jint, X, mask1, state1check, org_isite1) \
 shared(list_2_1, list_2_2, list_1buf, v1buf, tmp_v1, tmp_v0)
     for (j = 1; j <= idim_max_buf; j++) {
       jreal = list_1buf[j];
       state1 = (jreal & mask1) / mask1;
       if (state1 == state1check) {
         GetOffComp(list_2_1, list_2_2, jreal ^ mask1,
           X->Large.irght, X->Large.ilft, X->Large.ihfbit, &ioff);
         dmv = Jint * v1buf[j];
         dmv = 0.5 * v1buf[j];
         dam_pr += conj(tmp_v1[ioff]) * dmv;
       }/*if (state1 == state1check)*/
     }/*for (j = 1; j <= idim_max_buf; j++)*/
   }/*if (X->Large.mode == M_TOTALS)*/
   else {
 #pragma omp parallel for default(none) reduction(+:dam_pr) private(j, dmv, ioff, jreal, state1) \
 firstprivate(idim_max_buf, Jint, X, mask1, state1check, org_isite1) \
 shared(list_2_1, list_2_2, list_1buf, v1buf, tmp_v1, tmp_v0)
     for (j = 1; j <= idim_max_buf; j++) {
       jreal = list_1buf[j];
       state1 = (jreal & mask1) / mask1;
       if (state1 == state1check) {
         GetOffComp(list_2_1, list_2_2, jreal ^ mask1,
           X->Large.irght, X->Large.ilft, X->Large.ihfbit, &ioff);
         dmv = Jint * v1buf[j];
         dam_pr += conj(tmp_v1[ioff]) * dmv;
       }/*if (state1 == state1check)*/
     }/*for (j = 1; j <= idim_max_buf; j++)*/
   }
   return dam_pr;
 #endif
 }/*double complex X_child_general_int_spin_MPIsingle*/
double complex X_child_general_int_spin_TotalS_MPIdouble (int org_isite1, int org_isite3, struct BindStruct * X, double complex * tmp_v0, double complex * tmp_v1)
Exchange term in Spin model When both site1 and site2 are in the inter process region.
Returns
\(\langle v_1| H_{\rm this} | v_1 \rangle\)
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] org_isite1 site 1
[in] org_isite3 site 3
[in,out] X
[in,out] tmp_v0 \({\bf v}_0=H {\bf v}_1\)
[in] tmp_v1 Vector to be producted
Definition at line 138 of file mltplyMPISpin.c.
References BindStruct::Check, BindStruct::Def, exitMPI(), GetOffComp(), CheckList::idim_max, LargeList::ihfbit, LargeList::ilft, LargeList::irght, BindStruct::Large, list_1, list_1buf, list_2_1, list_2_2, myrank, DefineList::Tpow, and v1buf.
Referenced by totalspin_Spin().
  {
 #ifdef MPI
   int mask1, mask2, num1_up, num2_up, ierr, origin;
   unsigned long int idim_max_buf, j, ioff, ibit_tmp;
   MPI_Status statusMPI;
   double complex dmv, dam_pr;
   mask1 = (int)X->Def.Tpow[org_isite1];
   mask2 = (int)X->Def.Tpow[org_isite3];
   if (mask1 == mask2) origin = myrank ^ mask1;
   else origin = myrank ^ (mask1 + mask2);
   num1_up = (origin & mask1) / mask1;
   num2_up = (origin & mask2) / mask2;
   ibit_tmp = (num1_up) ^ (num2_up);
   if (ibit_tmp == 0) return 0;
   ierr = MPI_Sendrecv(&X->Check.idim_max, 1, MPI_UNSIGNED_LONG, origin, 0,
                       &idim_max_buf,      1, MPI_UNSIGNED_LONG, origin, 0,
                       MPI_COMM_WORLD, &statusMPI);
   if (ierr != 0) exitMPI(-1);
   ierr = MPI_Sendrecv(list_1, X->Check.idim_max + 1, MPI_UNSIGNED_LONG, origin, 0,
                       list_1buf,   idim_max_buf + 1, MPI_UNSIGNED_LONG, origin, 0,
                       MPI_COMM_WORLD, &statusMPI);
   if (ierr != 0) exitMPI(-1);
   ierr = MPI_Sendrecv(tmp_v1, X->Check.idim_max + 1, MPI_DOUBLE_COMPLEX, origin, 0,
                       v1buf,       idim_max_buf + 1, MPI_DOUBLE_COMPLEX, origin, 0,
                       MPI_COMM_WORLD, &statusMPI);
   if (ierr != 0) exitMPI(-1);
   dam_pr = 0.0;
 #pragma omp parallel for default(none) reduction(+:dam_pr) private(j, dmv, ioff) \
     firstprivate(idim_max_buf,  X) shared(list_2_1, list_2_2, list_1buf, v1buf, tmp_v1, tmp_v0)
   for (j = 1; j <= idim_max_buf; j++) {
     GetOffComp(list_2_1, list_2_2, list_1buf[j],
       X->Large.irght, X->Large.ilft, X->Large.ihfbit, &ioff);
     dmv = 0.5 * v1buf[j];
     dam_pr += conj(tmp_v1[ioff]) * dmv;
   }/*for (j = 1; j <= idim_max_buf; j++)*/
   return dam_pr;
 #endif
 }/*double complex X_child_general_int_spin_MPIdouble*/