HΦ: output_list.c File Reference
output_list.c File Reference
#include "output_list.h"
#include "FileIO.h"
#include "wrapperMPI.h"
Functions
int output_list (struct BindStruct *X)
Function Documentation
int output_list (struct BindStruct * X)
Parameters
X
Returns
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Definition at line 29 of file output_list.c.
References cFileNameListModel, BindStruct::Check, childfopenMPI(), cProEndOutputList, cProStartOutputList, D_FileNameMax, BindStruct::Def, fprintf(), DefineList::iCalcModel, CheckList::idim_max, list_1, DefineList::Ndown, DefineList::Ne, DefineList::Nsite, DefineList::Nup, and stdoutMPI.
Referenced by main().
{
   FILE *fp;
   char sdt[D_FileNameMax];
   int i,i_max;
   fprintf(stdoutMPI, "%s", cProStartOutputList);
   i_max=X->Check.idim_max;
   switch(X->Def.iCalcModel){
   case HubbardGC:
   case Hubbard:
   case Spin:
   case SpinGC:
   sprintf(sdt, cFileNameListModel, X->Def.Nsite,X->Def.Nup,X->Def.Ndown);
   break;
   case Kondo:
   case KondoGC:
     sprintf(sdt, "ListForKondo_Ns%d_Ncond%d", X->Def.Nsite,X->Def.Ne);
     break;
   default:
     return -1;
   }
   if(childfopenMPI(sdt,"w",&fp)!=0){
     return -1;
   }
   for(i=1;i<=i_max;i++){
     fprintf(fp," %lu \n",list_1[i]);
   }
   fclose(fp);
   fprintf(stdoutMPI, "%s", cProEndOutputList);
   return 0;
 }