HΦ: output.c File Reference
output.c File Reference
#include "output.h"
#include "FileIO.h"
#include "wrapperMPI.h"
Functions
int output (struct BindStruct *X)
output function for FullDiag mode
int outputHam (struct BindStruct *X)
output Hamiltonian only used for FullDiag mode
Function Documentation
int output (struct BindStruct * X)
output function for FullDiag mode
Parameters
[in] X Struct to get information about file header names, dimension of hirbert space, calc type, physical quantities.
Return values
0 normally finished.
-1 abnormally finished.
Definition at line 27 of file output.c.
References PhysList::all_doublon, PhysList::all_energy, PhysList::all_num_down, PhysList::all_num_up, PhysList::all_s2, PhysList::all_sz, DefineList::CDataFileHead, cFileNamePhys_FullDiag, cFileNamePhys_FullDiag_GC, BindStruct::Check, childfopenMPI(), D_FileNameMax, BindStruct::Def, DefineList::iCalcModel, DefineList::iCalcType, CheckList::idim_max, DefineList::Ndown, DefineList::Nup, BindStruct::Phys, and stdoutMPI.
Referenced by CalcByFullDiag().
{
   FILE *fp;
   char sdt[D_FileNameMax];
   long int i, i_max;
   i_max = X->Check.idim_max;
   if (X->Def.iCalcType == FullDiag) {
     switch (X->Def.iCalcModel) {
       case Spin:
       case Hubbard:
       case Kondo:
         sprintf(sdt, cFileNamePhys_FullDiag, X->Def.CDataFileHead, X->Def.Nup, X->Def.Ndown);
         break;
       case SpinGC:
       case HubbardGC:
       case KondoGC:
         sprintf(sdt, cFileNamePhys_FullDiag_GC, X->Def.CDataFileHead);
         break;
       default:
         break;
     }
     if (childfopenMPI(sdt, "w", &fp) != 0) {
       return -1;
     }
     fprintf(fp, "  <H>         <N>        <Sz>       <S2>       <D> \n");
     for (i = 0; i < i_max; i++) {
       fprintf(fp, " %10lf %10lf %10lf %10lf %10lf\n", X->Phys.all_energy[i], X->Phys.all_num_up[i]+X->Phys.all_num_down[i], X->Phys.all_sz[i],
               X->Phys.all_s2[i], X->Phys.all_doublon[i]);
     }
     fclose(fp);
   }
   else{
     fprintf(stdoutMPI, "Error: output function is used only for FullDiag mode.");
     return -1;
   }
   return 0;
 }
int outputHam (struct BindStruct * X)
output Hamiltonian only used for FullDiag mode
Note
global: [in] Ham
Parameters
[in] X Struct to get information about file header names, dimension of hirbert space.
Return values
0 normally finished.
-1 abnormally finished.
Definition at line 73 of file output.c.
References DefineList::CDataFileHead, cFileNamePhys_FullDiag_Ham, BindStruct::Check, childfopenMPI(), D_FileNameMax, BindStruct::Def, Ham, and CheckList::idim_max.
Referenced by CalcByFullDiag().
{
   long int i=0;
   long int j=0;
   long int imax = X->Check.idim_max;
   long int ihermite=0;
   char cHeader[256];
   FILE *fp;
   char sdt[D_FileNameMax];
 #pragma omp parallel for default(none) reduction(+:ihermite) firstprivate(imax) private(i, j) shared(Ham)
   for (i=1; i<=imax; i++){
     for (j=1; j<=i; j++){
       if(cabs(Ham[i][j])>1.0e-13){
         ihermite += 1;
       }
     }
   }
   strcpy(cHeader, "%%%%MatrixMarket matrix coordinate complex hermitian\n");
   sprintf(sdt,cFileNamePhys_FullDiag_Ham, X->Def.CDataFileHead);
   if(childfopenMPI(sdt,"w",&fp)!=0){
     return -1;
   }
   fprintf(fp, "%s", cHeader);
   fprintf(fp, "%ld %ld %ld \n", imax, imax, ihermite);
   for (i=1; i<=imax; i++){
     for (j=1; j<=i; j++){
       if(cabs(Ham[i][j])>1.0e-13){
         fprintf(fp, "%ld %ld %lf %lf\n",i,j,creal(Ham[i][j]),cimag(Ham[i][j]));
       }
     }
   }
   fclose(fp);
   return 0;
 }