HΦ: splash.c File Reference
splash.c File Reference
Print logo mark and version number.
#include <stdio.h>
#include "wrapperMPI.h"
#include "version_major.h"
#include "version_miner.h"
#include "version_patch.h"
Functions
void splash ()
Print logo mark and version number.
Detailed Description
Print logo mark and version number.
Definition in file splash.c.
Function Documentation
void splash ()
Print logo mark and version number.
Definition at line 25 of file splash.c.
References fprintf(), and stdoutMPI.
Referenced by InitializeMPI(), and main().
              {
    int ver_maj =
 #include "version_major.h"
 ;
    int ver_min =
 #include "version_miner.h"
 ;
    int ver_pat =
 #include "version_patch.h"
 ;
   fprintf(stdoutMPI, "                                                                \n");
   fprintf(stdoutMPI, "      ,ammmmmmmmmmmmmmb,,        Welcome to the                 \n");
   fprintf(stdoutMPI, "    ,@@` dm          mb  ===m                                    \n");
   fprintf(stdoutMPI, "  ,@@` d@@@@@@@@@@@@@@@@b Pm,    @@          @@        @@       \n");
   fprintf(stdoutMPI, " d@  d@@@ @@@ @@@@@@ @@@@b ~@a   @@          @@     @@@@@@@@    \n");
   fprintf(stdoutMPI, "d@   @@@@ ^^^ @@@@ m m @@@   @,  @@          @@   @@@  @@  @@@  \n");
   fprintf(stdoutMPI, "@    @@@@_@@@_@@@@mm mm@@@   @|  @@mmmmmmmmmm@@  @@    @@    @@ \n");
   fprintf(stdoutMPI, "P@    9@@@@@@@@@@@@@@@@@P    @~  @@@@@@@@@@@@@@  @@    @@    @@ \n");
   fprintf(stdoutMPI, " @@      ~~9@@@@@@PPP~      @P   @@          @@   @@@  @@  @@@  \n");
   fprintf(stdoutMPI, "  ~@@b      @@@@@@@      ,@@~    @@          @@     @@@@@@@@    \n");
   fprintf(stdoutMPI, "    ~@@@m,,@@@@@@@@@  ,m@~`      @@          @@        @@       \n");
   fprintf(stdoutMPI, "        ~~9@@@@@@@@@  ~                                         \n");
   fprintf(stdoutMPI, "           9@P~~~9@P             Version %d.%d.%d    \n", ver_maj, ver_min, ver_pat);
   fprintf(stdoutMPI, "                                                                \n");
 }/*void splash()*/