HΦ: wrapperMPI.c File Reference
wrapperMPI.c File Reference
MPI wrapper for init, finalize, bcast, etc.
#include <mpi.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "wrapperMPI.h"
#include <math.h>
#include <complex.h>
#include "splash.h"
#include "global.h"
Functions
void InitializeMPI (int argc, char *argv[])
MPI initialization wrapper Process ID (myrank), Number of processes (nproc), Number of threads (nthreads), and pointer to the standard output (stdoutMPI) are specified here.
void FinalizeMPI ()
MPI Finitialization wrapper.
void exitMPI (int errorcode)
MPI Abortation wrapper.
FILE * fopenMPI (const char *FileName, const char *mode)
MPI file I/O (open) wrapper. Only the root node (myrank = 0) should be open/read/write (small) parameter files.
char * fgetsMPI (char *InputString, int maxcount, FILE *fp)
MPI file I/O (get a line, fgets) wrapper. Only the root node (myrank = 0) reads and broadcast string.
void BarrierMPI ()
MPI barrier wrapper.
unsigned long int MaxMPI_li (unsigned long int idim)
MPI wrapper function to obtain maximum unsigned long integer across processes.
double MaxMPI_d (double dvalue)
MPI wrapper function to obtain maximum Double across processes.
double complex SumMPI_dc (double complex norm)
MPI wrapper function to obtain sum of Double complex across processes.
double SumMPI_d (double norm)
MPI wrapper function to obtain sum of Double across processes.
unsigned long int SumMPI_li (unsigned long int idim)
MPI wrapper function to obtain sum of unsigned long integer across processes.
int SumMPI_i (int idim)
MPI wrapper function to obtain sum of integer across processes.
unsigned long int BcastMPI_li (int root, unsigned long int idim)
MPI wrapper function to broadcast unsigned long integer across processes.
double NormMPI_dc (unsigned long int idim, double complex *_v1)
Compute norm of process-distributed vector \(|{\bf v}_1|^2\).
double complex VecProdMPI (long unsigned int ndim, double complex *v1, double complex *v2)
Compute conjugate scaler product of process-distributed vector \({\bf v}_1^* \cdot {\bf v}_2\).
Detailed Description
MPI wrapper for init, finalize, bcast, etc.
Definition in file wrapperMPI.c.
Function Documentation
void BarrierMPI ()
MPI barrier wrapper.
Author
Mitsuaki Kawamura (The University of Tokyo)
Definition at line 160 of file wrapperMPI.c.
                  {
 #ifdef MPI
   MPI_Barrier(MPI_COMM_WORLD);
 #endif
 }/*void BarrierMPI()*/
unsigned long int BcastMPI_li (int root, unsigned long int idim)
MPI wrapper function to broadcast unsigned long integer across processes.
Returns
Broadcasted value across processes.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] root The source process of the broadcast
[in] idim Value to be broadcasted
Definition at line 273 of file wrapperMPI.c.
Referenced by Initialize_wave(), Lanczos_EigenVector(), and SetInitialVector().
   {
   unsigned long int idim0;
   idim0 = idim;
 #ifdef MPI
     MPI_Bcast(&idim0, 1, MPI_UNSIGNED_LONG, root, MPI_COMM_WORLD);
 #endif
   return(idim0);
 }/*unsigned long int BcastMPI_li*/
void exitMPI (int errorcode)
MPI Abortation wrapper.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] errorcode Error-code to be returned as that of this program
Definition at line 86 of file wrapperMPI.c.
Referenced by CalcByLanczos(), CalcByLOBPCG(), CalcByTEM(), CalcByTPQ(), CalcSpectrum(), CalcSpectrumByBiCG(), CalcSpectrumByTPQ(), CheckMPI(), dsfmt_chk_init_by_array(), dsfmt_chk_init_gen_rand(), Initialize_wave(), InitializeMPI(), main(), MakeExcitedList(), MaxMPI_d(), MaxMPI_li(), Output_restart(), phys(), Read_sz(), ReadDefFileIdxPara(), SumMPI_d(), SumMPI_dc(), SumMPI_i(), SumMPI_li(), sz(), X_Ajt_MPI(), X_child_CisAit_GeneralSpin_MPIdouble(), X_child_CisAit_spin_MPIdouble(), X_child_CisAitCjuAjv_GeneralSpin_MPIdouble(), X_child_CisAitCjuAjv_GeneralSpin_MPIsingle(), X_child_CisAjt_MPIdouble(), X_child_CisAjt_MPIsingle(), X_child_CisAjtCkuAku_Hubbard_MPI(), X_child_CisAjtCkuAlv_Hubbard_MPI(), X_child_general_hopp_MPIdouble(), X_child_general_hopp_MPIsingle(), X_child_general_int_spin_MPIdouble(), X_child_general_int_spin_MPIsingle(), X_child_general_int_spin_TotalS_MPIdouble(), X_Cis_MPI(), X_GC_Ajt_MPI(), X_GC_child_CisAisCjuAjv_GeneralSpin_MPIdouble(), X_GC_child_CisAisCjuAjv_GeneralSpin_MPIsingle(), X_GC_child_CisAisCjuAjv_spin_MPIdouble(), X_GC_child_CisAisCjuAjv_spin_MPIsingle(), X_GC_child_CisAit_GeneralSpin_MPIdouble(), X_GC_child_CisAit_spin_MPIdouble(), X_GC_child_CisAitCiuAiv_spin_MPIdouble(), X_GC_child_CisAitCiuAiv_spin_MPIsingle(), X_GC_child_CisAitCjuAju_GeneralSpin_MPIdouble(), X_GC_child_CisAitCjuAju_spin_MPIdouble(), X_GC_child_CisAitCjuAjv_GeneralSpin_MPIdouble(), X_GC_child_CisAitCjuAjv_GeneralSpin_MPIsingle(), X_GC_child_CisAjt_Hubbard_MPI(), X_GC_child_CisAjtCkuAku_Hubbard_MPI(), X_GC_child_CisAjtCkuAlv_Hubbard_MPI(), X_GC_child_general_hopp_MPIdouble(), X_GC_child_general_hopp_MPIsingle(), and X_GC_Cis_MPI().
 {
   int ierr;
   fflush(stdout);
 #ifdef MPI
   fprintf(stdout,"\n\n #######  [HPhi] You DO NOT have to WORRY about the following MPI-ERROR MESSAGE.  #######\n\n");
   ierr = MPI_Abort(MPI_COMM_WORLD, errorcode);
   ierr = MPI_Finalize();
   if (ierr != 0) fprintf(stderr, "\n  MPI_Finalize() = %d\n\n", ierr);
 #endif
   exit(errorcode);
 }/*void exitMPI*/
char* fgetsMPI (char * InputString, int maxcount, FILE * fp)
MPI file I/O (get a line, fgets) wrapper. Only the root node (myrank = 0) reads and broadcast string.
Returns
The same as that of fgets
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[out] InputString read line.
[in] maxcount Length of string
[in] fp file pointer
Definition at line 122 of file wrapperMPI.c.
References myrank.
Referenced by GetFileName(), inputHam(), Read_sz(), ReadcalcmodFile(), ReadDefFileIdxPara(), ReadDefFileNInt(), ReadTMComponents(), ReadTMComponents_BiCG(), and SetOmega().
  {
   int inull;
   char *ctmp;
   ctmp = InputString;
   inull = 0;
   if (myrank == 0) {
     ctmp = fgets(InputString, maxcount, fp);
     if (ctmp == NULL){
       inull = 1;
     }
     while(*InputString == '\n' || strncmp(InputString, "#", 1)==0){
       ctmp = fgets(InputString, maxcount, fp);
       if (ctmp == NULL){
     inull=1;
     break;
       }
     }
   }
 #ifdef MPI
   MPI_Bcast(InputString, maxcount, MPI_CHAR, 0, MPI_COMM_WORLD);
   MPI_Bcast(&inull, 1, MPI_INT, 0, MPI_COMM_WORLD);
 #endif
   if (myrank != 0 && inull == 1) {
     ctmp = NULL;
   }
   return ctmp;
 }/*char* fgetsMPI*/
void FinalizeMPI ()
MPI Finitialization wrapper.
Author
Mitsuaki Kawamura (The University of Tokyo)
Definition at line 74 of file wrapperMPI.c.
References myrank, and stdoutMPI.
Referenced by main(), and MakeExcitedList().
                   {
   int ierr;
 #ifdef MPI
   ierr = MPI_Finalize();
   if (ierr != 0) fprintf(stderr, "\n  MPI_Finalize() = %d\n\n", ierr);
 #endif
   if (myrank != 0) fclose(stdoutMPI);
 }
FILE* fopenMPI (const char * FileName, const char * mode)
MPI file I/O (open) wrapper. Only the root node (myrank = 0) should be open/read/write (small) parameter files.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] FileName Input/output file
[in] mode "w", "r", etc.
Definition at line 105 of file wrapperMPI.c.
References myrank.
Referenced by childfopenMPI(), GetFileName(), ReadcalcmodFile(), ReadDefFileIdxPara(), and ReadDefFileNInt().
  {
   FILE* fp;
   if (myrank == 0) fp = fopen(FileName, mode);
   else fp = fopen("/dev/null", "w");
   return fp;
 }/*FILE* fopenMPI*/
void InitializeMPI (int argc, char * argv[])
MPI initialization wrapper Process ID (myrank), Number of processes (nproc), Number of threads (nthreads), and pointer to the standard output (stdoutMPI) are specified here.
Author
Mitsuaki Kawamura (The University of Tokyo)
Definition at line 43 of file wrapperMPI.c.
References exitMPI(), myrank, nproc, nthreads, splash(), and stdoutMPI.
Referenced by main().
{
   int ierr;
 #ifdef MPI
   ierr = MPI_Init(&argc, &argv);
   ierr = MPI_Comm_size(MPI_COMM_WORLD, &nproc);
   ierr = MPI_Comm_rank(MPI_COMM_WORLD, &myrank);
   if(ierr != 0) exitMPI(ierr);
 #else
   nproc = 1;
   myrank = 0;
 #endif
   if (myrank == 0) stdoutMPI = stdout;
   else stdoutMPI = fopen("/dev/null", "w");
   splash();
 #pragma omp parallel default(none) shared(nthreads)
 #pragma omp master
 #ifdef _OPENMP
   nthreads = omp_get_num_threads();
 #else
   nthreads=1;
 #endif
   fprintf(stdoutMPI, "\n\n#####  Parallelization Info.  #####\n\n");
   fprintf(stdoutMPI, "  OpenMP threads : %d\n", nthreads);
   fprintf(stdoutMPI, "  MPI PEs : %d \n\n", nproc);
 }/*void InitializeMPI(int argc, char *argv[])*/
double MaxMPI_d (double dvalue)
MPI wrapper function to obtain maximum Double across processes.
Returns
Maximum value across processes.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] dvalue Value to be maximized
Definition at line 188 of file wrapperMPI.c.
References exitMPI().
Referenced by check().
  {
 #ifdef MPI
   int ierr;
   ierr = MPI_Allreduce(MPI_IN_PLACE, &dvalue, 1,
     MPI_DOUBLE, MPI_MAX, MPI_COMM_WORLD);
   if(ierr != 0) exitMPI(-1);
 #endif
   return(dvalue);
 }/*double MaxMPI_d*/
unsigned long int MaxMPI_li (unsigned long int idim)
MPI wrapper function to obtain maximum unsigned long integer across processes.
Returns
Maximum value across processes.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] idim Value to be maximized
Definition at line 171 of file wrapperMPI.c.
References exitMPI().
Referenced by check(), GetPairExcitedStateGeneralSpin(), GetPairExcitedStateHalfSpin(), GetPairExcitedStateHubbard(), GetSingleExcitedStateHubbard(), GetSingleExcitedStateHubbardGC(), and setmem_large().
  {
 #ifdef MPI
   int ierr;
   ierr = MPI_Allreduce(MPI_IN_PLACE, &idim, 1,
     MPI_UNSIGNED_LONG, MPI_MAX, MPI_COMM_WORLD);
   if(ierr != 0) exitMPI(-1);
 #endif
   return(idim);
 }/*unsigned long int MaxMPI_li*/
double NormMPI_dc (unsigned long int idim, double complex * _v1)
Compute norm of process-distributed vector \(|{\bf v}_1|^2\).
Returns
Norm \(|{\bf v}_1|^2\)
Parameters
[in] idim Local dimension of vector
[in] _v1 [idim] vector to be producted
Definition at line 289 of file wrapperMPI.c.
References SumMPI_dc().
Referenced by CalcSpectrum().
  {
   double complex cdnorm=0;
   double dnorm =0;
   unsigned long int i;
   //DEBUG
 #pragma omp parallel for default(none) private(i) firstprivate(myrank) shared(_v1, idim) reduction(+: cdnorm)
   for(i=1;i<=idim;i++){
     cdnorm += conj(_v1[i])*_v1[i];
   }
 #ifdef MPI
   cdnorm = SumMPI_dc(cdnorm);
 #endif
   dnorm=creal(cdnorm);
   dnorm=sqrt(dnorm);
   return dnorm;
 }/*double NormMPI_dc*/
double SumMPI_d (double norm)
MPI wrapper function to obtain sum of Double across processes.
Returns
Sumed value across processes.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] norm Value to be summed
Definition at line 222 of file wrapperMPI.c.
References exitMPI().
Referenced by CG_EigenVector(), expec_energy_flct_GeneralSpinGC(), expec_energy_flct_HalfSpinGC(), expec_energy_flct_Hubbard(), expec_energy_flct_HubbardGC(), Lanczos_EigenVector(), and PowerLanczos().
  {
 #ifdef MPI
   int ierr;
   ierr = MPI_Allreduce(MPI_IN_PLACE, &norm, 1,
     MPI_DOUBLE_PRECISION, MPI_SUM, MPI_COMM_WORLD);
   if(ierr != 0) exitMPI(-1);
 #endif
   return(norm);
 }/*double SumMPI_d*/
double complex SumMPI_dc (double complex norm)
MPI wrapper function to obtain sum of Double complex across processes.
Returns
Sumed value across processes.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] norm Value to be summed
Definition at line 205 of file wrapperMPI.c.
References exitMPI().
Referenced by CG_EigenVector(), expec_cisajs_Hubbard(), expec_cisajs_HubbardGC(), expec_cisajs_SpinGCGeneral(), expec_cisajs_SpinGCHalf(), expec_cisajs_SpinGeneral(), expec_cisajs_SpinHalf(), expec_cisajscktalt_Hubbard(), expec_cisajscktalt_HubbardGC(), expec_cisajscktalt_SpinGCGeneral(), expec_cisajscktalt_SpinGCHalf(), expec_cisajscktalt_SpinGeneral(), expec_cisajscktalt_SpinHalf(), expec_energy_flct(), Lanczos_EigenValue(), Lanczos_EigenVector(), Lanczos_GetTridiagonalMatrixComponents(), mltply(), Multiply(), MultiplyForTEM(), NormMPI_dc(), PowerLanczos(), SetDiagonalTEChemi(), SetDiagonalTEInterAll(), SetDiagonalTETransfer(), SetInitialVector(), totalspin_Spin(), totalspin_SpinGC(), totalSz_HubbardGC(), totalSz_SpinGC(), and VecProdMPI().
  {
 #ifdef MPI
   int ierr;
   ierr = MPI_Allreduce(MPI_IN_PLACE, &norm, 1,
     MPI_DOUBLE_COMPLEX, MPI_SUM, MPI_COMM_WORLD);
   if(ierr != 0) exitMPI(-1);
 #endif
   return(norm);
 }/*double complex SumMPI_dc*/
int SumMPI_i (int idim)
MPI wrapper function to obtain sum of integer across processes.
Returns
Sumed value across processes.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] idim Value to be summed
Definition at line 256 of file wrapperMPI.c.
References exitMPI().
Referenced by CheckMPI_Summary().
   {
 #ifdef MPI
   int ierr;
   ierr = MPI_Allreduce(MPI_IN_PLACE, &idim, 1,
                        MPI_INT, MPI_SUM, MPI_COMM_WORLD);
   if(ierr != 0) exitMPI(-1);
 #endif
   return(idim);
 }/*int SumMPI_i*/
unsigned long int SumMPI_li (unsigned long int idim)
MPI wrapper function to obtain sum of unsigned long integer across processes.
Returns
Sumed value across processes.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] idim Value to be summed
Definition at line 239 of file wrapperMPI.c.
References exitMPI().
Referenced by CheckMPI_Summary(), Initialize_wave(), Lanczos_EigenValue(), Lanczos_EigenVector(), Lanczos_GetTridiagonalMatrixComponents(), and SetInitialVector().
  {
 #ifdef MPI
   int ierr;
   ierr = MPI_Allreduce(MPI_IN_PLACE, &idim, 1,
     MPI_UNSIGNED_LONG, MPI_SUM, MPI_COMM_WORLD);
   if(ierr != 0) exitMPI(-1);
 #endif
   return(idim);
 }/*unsigned long int SumMPI_li*/
double complex VecProdMPI (long unsigned int ndim, double complex * v1, double complex * v2)
Compute conjugate scaler product of process-distributed vector \({\bf v}_1^* \cdot {\bf v}_2\).
Returns
Conjugate scaler product \({\bf v}_1^* \cdot {\bf v}_2\)
Parameters
[in] ndim Local dimension of vector
[in] v1 [ndim] vector to be producted
[in] v2 [ndim] vector to be producted
Definition at line 314 of file wrapperMPI.c.
References SumMPI_dc().
Referenced by CalcSpectrumByBiCG(), Initialize_wave(), InitShadowRes(), and LOBPCG_Main().
  {
   long unsigned int idim;
   double complex prod;
   prod = 0.0;
 #pragma omp parallel for default(none) shared(v1,v2,ndim) private(idim) reduction(+: prod)
   for (idim = 1; idim <= ndim; idim++) prod += conj(v1[idim]) * v2[idim];
   prod = SumMPI_dc(prod);
   return(prod);
 }/*double complex VecProdMPI*/