HΦ: xfreemem_large.c File Reference
xfreemem_large.c File Reference
#include "xfreemem_large.h"
Functions
d_free1 (X.Bind.Large.v0, X.Bind.Check.idim_max+1)
fprintf (stdoutMPI,"LARGE Free FINISH !\n")
Function Documentation
d_free1 (X.Bind.Large. v0, X.Bind.Check.idim_max+ 1)
Referenced by CalcSpectrumByTPQ(), Lanczos_EigenValue(), and LOBPCG_Main().
fprintf (stdoutMPI , "LARGE Free FINISH !\n")
Referenced by CalcByFullDiag(), CalcByLanczos(), CalcByLOBPCG(), CalcByTPQ(), CalcSpectrum(), CalcSpectrumByBiCG(), CalcSpectrumByLanczos(), CalcSpectrumByTPQ(), CG_EigenVector(), check(), CheckFormatForKondoInt(), CheckFormatForSpinInt(), CheckInterAllHermite(), CheckModPara(), CheckMPI(), CheckMPI_Summary(), CheckOutputMode(), CheckSpinIndexForInterAll(), CheckSpinIndexForTrans(), CheckTotal2Sz(), CheckTransferHermite(), childfopenALL(), childfopenMPI(), diagonalcalc(), dsfmt_chk_init_by_array(), dsfmt_chk_init_gen_rand(), exitMPI(), expec_cisajs(), expec_cisajs_Hubbard(), expec_cisajs_HubbardGC(), expec_cisajs_SpinGCGeneral(), expec_cisajs_SpinGCHalf(), expec_cisajs_SpinGeneral(), expec_cisajs_SpinHalf(), expec_cisajscktalt_Hubbard(), expec_cisajscktalt_HubbardGC(), expec_cisajscktalt_SpinGCGeneral(), expec_cisajscktalt_SpinGCHalf(), expec_cisajscktalt_SpinGeneral(), expec_cisajscktalt_SpinHalf(), expec_cisajscktaltdc(), expec_energy_flct(), FinalizeMPI(), geometry_W90(), GetCalcSpectrumTPQ(), GetDiagonalInterAll(), GetExcitedState(), GetFileName(), GetKWWithIdx(), GetPairExcitedStateGeneralSpin(), GetPairExcitedStateGeneralSpinGC(), GetPairExcitedStateHalfSpin(), GetPairExcitedStateHalfSpinGC(), GetSplitBit(), GetSplitBitByModel(), GetSplitBitForGeneralSpin(), HPhiTrans(), Initialize_wave(), InitializeMPI(), inputHam(), JudgeDefType(), Lanczos_EigenValue(), Lanczos_EigenVector(), lapack_diag(), LOBPCG_Main(), main(), MakeExcitedList(), mltplyGeneralSpinGC(), mltplyHalfSpinGC(), output(), output_list(), Output_restart(), outputHam(), OutputLanczosVector(), OutputSpectrum(), OutputTimer(), OutputTMComponents(), OutputTMComponents_BiCG(), phys(), PowerLanczos(), Print1Green(), Print2Green(), PrintCalcMod(), PrintExcitation(), PrintInteractions(), PrintLocSpin(), PrintModPara(), PrintNamelist(), PrintTrans(), Read_sz(), read_W90(), ReadcalcmodFile(), ReadDefFileError(), ReadDefFileIdxPara(), ReadDefFileNInt(), ReadInitialVector(), ReadTMComponents_BiCG(), SetDiagonalChemi(), SetDiagonalCoulombInter(), SetDiagonalCoulombIntra(), SetDiagonalHund(), SetDiagonalInterAll(), SetInitialVector(), setmem_large(), SetOmega(), splash(), StampTime(), StdFace_Chain(), StdFace_Chain_Boost(), StdFace_exit(), StdFace_FCOrtho(), StdFace_Honeycomb(), StdFace_Honeycomb_Boost(), StdFace_InitSite(), StdFace_InputCoulombV(), StdFace_InputHopp(), StdFace_InputSpin(), StdFace_InputSpinNN(), StdFace_Kagome(), StdFace_Kagome_Boost(), StdFace_Ladder(), StdFace_Ladder_Boost(), StdFace_main(), StdFace_MallocInteractions(), StdFace_NotUsed_c(), StdFace_NotUsed_d(), StdFace_NotUsed_i(), StdFace_Orthorhombic(), StdFace_PrintGeometry(), StdFace_PrintVal_c(), StdFace_PrintVal_d(), StdFace_PrintVal_dd(), StdFace_PrintVal_i(), StdFace_PrintXSF(), StdFace_Pyrochlore(), StdFace_RequiredVal_i(), StdFace_SetLabel(), StdFace_Tetragonal(), StdFace_Triangular(), StdFace_Wannier90(), StoreWithCheckDup_c(), StoreWithCheckDup_d(), StoreWithCheckDup_i(), StoreWithCheckDup_s(), StoreWithCheckDup_sl(), sz(), TimeKeeper(), TimeKeeperWithRandAndStep(), TimeKeeperWithStep(), UnsupportedSystem(), and vec12().