name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1,15 * *' # JST 9:00 on 1st and 15th every month

jobs:
  ctest:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-24.04]
        mpisize: [1, 3, 4, 9, 16]
        ompsize: [1]
        include:
          - os: ubuntu-24.04
            mpisize: 1
            ompsize: 3
          - os: macos-latest
            mpisize: 1
            ompsize: 1
      fail-fast: false

    env:
      MPIRUN: "mpiexec --oversubscribe -np ${{ matrix.mpisize }}"
      OMP_NUM_THREADS: ${{ matrix.ompsize }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: apt
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt update
          sudo apt install libblas-dev liblapack-dev openmpi-bin libopenmpi-dev libscalapack-openmpi-dev

      - name: brew
        if: ${{ runner.os == 'macOS' }}
        run: |
          brew install openmpi scalapack

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.11"

      - name: pip
        run: |
          python3 -m pip install numpy

      - name: make workspace
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: cmake
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: |
          if [ ${{ runner.os }} = "macOS" ] ; then
            export FC=gfortran-15
          fi
          cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_POLICY_VERSION_MINIMUM=3.5 $GITHUB_WORKSPACE

      - name: build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build ./ -j4

      - name: ctest
        if: ${{ matrix.mpisize == 1 }}
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ctest -V -E lobcg_hubbard_szunconserv

      - name: ctest
        if: ${{ matrix.mpisize == 3 || matrix.mpisize == 9 }}
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ctest -V -R spinone

      - name: ctest
        if: ${{ matrix.mpisize == 4 || matrix.mpisize == 16 }}
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ctest -V -E "spinone|lobcg_hubbard_szunconserv"
